### ISSUE TITLE
convert: eXIf: CRC error and convert: eXIf: incorrect byte-order specifier

### ISSUE THREAD

**Issue by benpptung** [ImageMagick/ImageMagick#862] opened 2017-11-15 16:25 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Following please find the error while convert png files to jpg

```
# convert test-1.png test.jpg
convert: eXIf: CRC error `test-1.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: eXIf: incorrect byte-order specifier `test-1.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: Expected 2454597 bytes; found 985 bytes `test-1.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: Read Exception `test-1.png' @ error/png.c/MagickPNGErrorHandler/1711
```

There is no problem in mac ( ImageMagick 6.8.7-0 2013-11-20 ) 
and my old box FreeBSD 9.2 ( ImageMagick 6.8.9-4 Q16 amd64),
but it happened on 
FreeBSD 11.1(  ImageMagick 7.0.7-4 Q16 amd64 2017-11-15 ) or
FreeBSD 11.1(  ImageMagick 6.9.9-15 Q16 amd64 2017-11-13 )

The jpg files still generated, but I have to ignore these error in my codes.

### Steps to Reproduce

download a psd file
```
curl -O https://s3.amazonaws.com/icartoonme-free/Happy-New-Year-Winter.psd
```

convert the psd file to png
```
convert Happy-New-Year-Winter.psd test.png
```

convert the test-x.png to jpg, that said, test-2.png
```
convert test-2.png test.jpg
```

Then, we'll got the following error 

```
convert: eXIf: CRC error `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: eXIf: incorrect byte-order specifier `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: Expected 2454597 bytes; found 982 bytes `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: Read Exception `test-2.png' @ error/png.c/MagickPNGErrorHandler/1711.
```

### System Configuration

- ImageMagick version:
ImageMagick 7.0.7-4 Q16 amd64 2017-11-15
ImageMagick 6.9.9-15 Q16 amd64 2017-11-13

- Environment (Operating system, version and so on):
FreeBSD 11.0, FreeBSD 11.1

- Additional information:
There is no problem on my mac and old box  FreeBSD 9.2 ( ImageMagick 6.8.9-4 Q16 amd64),
however, I have no way to downgrade, because software always changes for no reason.

**Comment by dlemstra** [comment] 2017-11-16 06:24
@glennrp Could you take a look at this?

**Comment by urban-warrior** [comment] 2017-11-22 01:45
Unfortunately we cannot reproduce this problem, We're using IM 7.0.7-11 and ImageMagick 6.9.9-23 and libpng16.  The image converts without complaint.  What version of libpng are you using?

**Comment by benpptung** [comment] 2017-11-22 07:21
Hi urban-warrior, 

Thank you for reply :) 
Following please find the information:

```
# convert -list format | grep PNG
      JNG* PNG       rw-   JPEG Network Graphics
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.34+apng)
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.34+apng)
           See http://www.libpng.org/ for details about the PNG format.
    PNG00* PNG       rw-   PNG inheriting bit-depth, color-type from original if possible
    PNG24* PNG       rw-   opaque or binary transparent 24-bit RGB (zlib 1.2.8)
    PNG32* PNG       rw-   opaque or transparent 32-bit RGBA
    PNG48* PNG       rw-   opaque or binary transparent 48-bit RGB
    PNG64* PNG       rw-   opaque or transparent 64-bit RGBA
     PNG8* PNG       rw-   8-bit indexed with optional binary transparency
```

and this is my current ports installed in FreeBSD 11.0, 
( I'm sorry, FreeBSD 11.1 with IM7, and IM6 were removed, since they have similar warnings)

```
# portmaster -L
===>>> Root ports (No dependencies, not depended on)
===>>> bigreqsproto-1.1.2
===>>> dialog4ports-0.1.6
===>>> dri3proto-1.0
===>>> ec2-scripts-1.10
===>>> firstboot-freebsd-update-1.2
===>>> firstboot-pkgs-1.5
===>>> inputproto-2.3.2
===>>> nasm-2.13.01,1
===>>> pkg-1.10.1
===>>> portmaster-3.17.10
===>>> presentproto-1.1
===>>> xcmiscproto-1.2.2
===>>> xf86bigfontproto-1.2.0
===>>> xorg-macros-1.19.1
===>>> xtrans-1.3.5
===>>> 15 root ports

===>>> Trunk ports (No dependencies, are depended on)
===>>> autoconf-wrapper-20131203
===>>> automake-wrapper-20131203
===>>> boehm-gc-7.6.0
===>>> ca_root_nss-3.32.1
===>>> damageproto-1.2.1
===>>> db5-5.3.28_6
===>>> dri2proto-2.8
===>>> expat-2.2.1
===>>> fixesproto-5.0
===>>> freetype2-2.8_1
===>>> giflib-5.1.4
===>>> glproto-1.4.17
===>>> gnome_subr-1.0
===>>> gsfonts-8.11_8
===>>> html2text-1.3.2a
===>>> icu-60.1,1
===>>> indexinfo-0.3.1
===>>> jbigkit-2.1_1
===>>> jpeg-turbo-1.5.2
===>>> jsoncpp-1.8.1_2
===>>> kbproto-1.0.7
===>>> libdaemon-0.14_1
===>>> libedit-3.1.20170329_2,1
===>>> libiconv-1.14_11
===>>> libltdl-2.4.6
===>>> liblz4-1.8.0,1
===>>> libpaper-1.1.24.4
===>>> libpthread-stubs-0.4
===>>> libunwind-20170113_1
===>>> libuv-1.16.1
===>>> libxml2-2.9.4
===>>> libyaml-0.1.6_2
===>>> lzo2-2.10_1
===>>> pciids-20171011
===>>> pcre-8.40_1
===>>> perl5-5.24.3
===>>> pixman-0.34.0
===>>> pkgconf-1.3.10,1
===>>> png-1.6.34
===>>> renderproto-0.11.1
===>>> rhash-1.3.5
===>>> svgalib-1.4.3_7
===>>> xextproto-7.3.0
===>>> xf86vidmodeproto-2.3.1
===>>> xmlcatmgr-2.2_2
===>>> xproto-7.0.31
===>>> 46 trunk ports

===>>> Branch ports (Have dependencies, are depended on)
===>>> apr-1.6.3.1.6.1
===>>> autoconf-2.69_1
===>>> avahi-app-0.6.31_5
===>>> bash-4.4.12_3
===>>> cups-2.2.6
===>>> curl-7.56.1
===>>> dbus-1.10.16_1
===>>> dbus-glib-0.108
===>>> docbook-1.5
===>>> docbook-sgml-4.5_1
===>>> docbook-xml-5.0_3
===>>> docbook-xsl-1.76.1_3
===>>> fftw3-3.3.6.p2_2
===>>> fontconfig-2.12.1,1
===>>> gdbm-1.13_1
===>>> getopt-1.1.6
===>>> gettext-runtime-0.19.8.1_1
===>>> ghostscript9-agpl-base-9.16_5
===>>> glib-2.50.2_7,1
===>>> gmp-6.1.2
===>>> gnutls-3.5.16
===>>> gobject-introspection-1.50.0,1
===>>> iso8879-1986_3
===>>> jbig2dec-0.14
===>>> lcms2-2.8
===>>> libICE-1.0.9_1,1
===>>> libSM-1.2.2_3,1
===>>> libX11-1.6.5,1
===>>> libXau-1.0.8_3
===>>> libXdamage-1.1.4_3
===>>> libXdmcp-1.1.2
===>>> libXext-1.3.3_1,1
===>>> libXfixes-5.0.3
===>>> libXrender-0.9.10
===>>> libXxf86vm-1.1.4_1
===>>> libarchive-3.3.2,1
===>>> libdrm-2.4.88,1
===>>> libffi-3.2.1_1
===>>> libgcrypt-1.8.1
===>>> libgpg-error-1.27
===>>> libidn-1.33_1
===>>> libidn2-2.0.4
===>>> liblqr-1-0.4.2
===>>> libpciaccess-0.13.5
===>>> libraw-0.18.5
===>>> libtasn1-4.12
===>>> libunistring-0.9.7
===>>> libwmf-nox11-0.2.8.4_15
===>>> libxcb-1.12_2
===>>> libxshmfence-1.2_2
===>>> libxslt-1.1.29_1
===>>> lua52-5.2.4
===>>> m4-1.4.18,1
===>>> mesa-libs-17.2.4
===>>> nettle-3.3
===>>> openjpeg-2.3.0
===>>> p11-kit-0.23.9
===>>> p5-Authen-SASL-2.16_1
===>>> p5-Digest-HMAC-1.03_1
===>>> p5-Error-0.17025
===>>> p5-GSSAPI-0.28_1
===>>> p5-IO-Socket-SSL-2.051
===>>> p5-Locale-gettext-1.07
===>>> p5-Mozilla-CA-20160104
===>>> p5-Net-SSLeay-1.82
===>>> p5-XML-Parser-2.44
===>>> py27-Babel-2.3.4
===>>> py27-Jinja2-2.9.5
===>>> py27-MarkupSafe-1.0
===>>> py27-alabaster-0.7.6
===>>> py27-botocore-1.7.36
===>>> py27-colorama-0.3.7
===>>> py27-dateutil-2.6.1
===>>> py27-docutils-0.14
===>>> py27-futures-3.1.1
===>>> py27-imagesize-0.7.1
===>>> py27-jmespath-0.9.0_1
===>>> py27-pyasn1-0.3.7
===>>> py27-pygments-2.2.0
===>>> py27-pystemmer-1.3.0_1
===>>> py27-pytz-2017.2,1
===>>> py27-rsa-3.4.2
===>>> py27-s3transfer-0.1.11
===>>> py27-setuptools-36.5.0
===>>> py27-six-1.11.0
===>>> py27-snowballstemmer-1.2.0_1
===>>> py27-sphinx_rtd_theme-0.2.4
===>>> py27-yaml-3.11_2
===>>> python2-2_3
===>>> python27-2.7.14_1
===>>> readline-7.0.3_1
===>>> sdocbook-xml-1.1_2,2
===>>> serf-1.3.9_1
===>>> sqlite3-3.21.0_1
===>>> subversion-1.9.7
===>>> tiff-4.0.8
===>>> tpm-emulator-0.7.4_2
===>>> trousers-0.3.14_1
===>>> w3m-0.5.3.20170102
===>>> webp-0.6.0_4
===>>> xcb-util-0.4.0_2,1
===>>> xcb-util-renderutil-0.3.9_1
===>>> xmlcharent-0.3_2
===>>> 103 branch ports

===>>> Leaf ports (Have dependencies, not depended on)
===>>> ImageMagick-nox11-6.9.9.15,1
===>>> asciidoc-8.6.9_5
===>>> automake-1.15.1
===>>> awscli-1.11.178
===>>> binutils-2.28,1
===>>> bison-3.0.4,1
===>>> cairo-1.14.8_1,2
===>>> check-0.12.0
===>>> cmake-3.9.4
===>>> gettext-tools-0.19.8.1
===>>> git-2.15.0
===>>> gmake-4.2.1_1
===>>> help2man-1.47.5
===>>> intltool-0.51.0_1
===>>> libatomic_ops-7.6.0_1
===>>> libtool-2.4.6
===>>> llvm40-4.0.1_3
===>>> minixmlto-0.0.2_1
===>>> mpfr-3.1.6
===>>> ninja-1.8.2,2
===>>> node4-4.8.6_1
===>>> p5-IO-Socket-IP-0.39
===>>> p5-Net-SMTP-SSL-1.04
===>>> p5-Socket-2.024
===>>> portdowngrade-1.6
===>>> py27-enum34-1.1.6
===>>> py27-sphinx-1.4.8_2,1
===>>> ruby-2.3.5,1
===>>> scons-2.5.1_1
===>>> swig30-3.0.12
===>>> texinfo-6.5,1
===>>> xcb-proto-1.12
===>>> xmlto-0.0.28
===>>> 33 leaf ports
```

On FreeBSD 11.0 with ImageMagick 6.9.9, the warnings are:
```
test: eXIf: CRC error `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: eXIf: incorrect byte-order specifier `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: Expected 2454597 bytes; found 982 bytes `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: Read Exception `test-2.png' @ error/png.c/MagickPNGErrorHandler/1639.
test: eXIf: CRC error `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: eXIf: incorrect byte-order specifier `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: Expected 2454597 bytes; found 982 bytes `test-2.png' @ warning/png.c/MagickPNGWarningHandler/1665.
test: Read Exception `test-2.png' @ error/png.c/MagickPNGErrorHandler/1639.
```

**Comment by benpptung** [comment] 2017-11-22 07:34
Additional Information,

If you want to see the generated test-2.png during the above process, you can find it here:
https://s3.amazonaws.com/icartoonme-free/test-2.png

It's weird because my mac ImageMagick can convert test-x.png to test.jpg without complain, and
if I generate test-x.png in my mac, and upload it to the new box to convert to jpg, it can handle them without complain too. 

It only complains when the test-x.png are generated by itself.

**Comment by dlemstra** [comment] 2017-11-25 23:13
Fixed in: https://github.com/ImageMagick/ImageMagick/commit/271a1bf9143bc8feb4312990b32c7c5650f11268 and https://github.com/ImageMagick/ImageMagick/commit/56596b797ec27544a4a5095f726e0f35b94bf2bc. Will be available in the beta sometime tomorrow.

**Closed** 2017-11-25 23:13 UTC
Labels: bug

**Comment by benpptung** [comment] 2018-01-13 15:59
Interesting.. 

Although this bug is fixed. But now, I got another error which was not exist when I submit this issue. I am sorry, I think ImageMagick is very buggy now.

convert xxx.png -thumbnail x250 -background white -flatten xxx.jpg


 eXIf: CRC error `/www/storages/kekko/fx/pf/e6/kekko-84d22b-4fjrf6-0.png\' @ warning/png.c/MagickPNGWarningHandler/1665.\nfile.icartoon.me: eXIf: incorrect byte-order specifier `/www/storages/kekko/fx/pf/e6/kekko-84d22b-4fjrf6-0.png\' @ warning/png.c/MagickPNGWarningHandler/1665.\nfile.icartoon.me: Expected 2454597 bytes; found 962 bytes `/www/storages/kekko/fx/pf/e6/kekko-84d22b-4fjrf6-0.png\' @ warning/png.c/MagickPNGWarningHandler/1665.\nfile.icartoon.me: Read Exception `/www/storages/kekko/fx/pf/e6/kekko-84d22b-4fjrf6-0.png\' @ error/png.c/MagickPNGErrorHandler/1639.\nfile.icartoon.me: no images defined `/www/storages/ictfile1/zi/xu/kw/ictfile1-09c003-heakuu.jpg\' @ error/convert.c/ConvertImageCommand/3258.\n
