### ISSUE TITLE
CR3 to JPG Produces Pink Shading

### ISSUE THREAD

**Issue by preebhatt** [ImageMagick/ImageMagick#5508] opened 2022-08-31 06:28 UTC
### ImageMagick version

 ImageMagick 7.1.0-47 Q16-HDRI x86_64

### Operating system

MacOS

### Operating system, version and so on

Monterey version 12.3 

### Description

CR3 to JPG image conversion adds a pink shade to the output image.

### Steps to Reproduce

Ran the following command : `convert cr3:original.cr3 output.jpg` which added pink shade to the output image.

<img width="1671" alt="Screenshot 2022-08-31 at 11 55 33 AM" src="https://user-images.githubusercontent.com/109717822/187608475-9598943d-c490-428e-ba92-12366888ad2d.png">
Original file can be found at : https://drive.google.com/file/d/1CusvHErh87jhyxJnTPKZuyjOeOPpdi2_/view?usp=sharing

This seems to be related to https://github.com/ImageMagick/ImageMagick/issues/1497

**Comment by preebhatt** [comment] 2022-08-31 09:47
I found a related issue for libraw as well: https://github.com/dlemstra/Magick.NET/issues/866
but I am able to reproduce it on the latest version of imagemagick that ships with the latest libRAW.

**Comment by dlemstra** [comment] 2022-08-31 14:05
Adding a zipped version of the file for future reference

[original.zip.001.zip](https://github.com/ImageMagick/ImageMagick/files/9462131/original.zip.001.zip)
[original.zip.002.zip](https://github.com/ImageMagick/ImageMagick/files/9462134/original.zip.002.zip)
[original.zip.003.zip](https://github.com/ImageMagick/ImageMagick/files/9462137/original.zip.003.zip)

**Comment by dlemstra** [comment] 2022-08-31 14:09
This is an issue with the libraw library and it has been resolved. On Windows we are using a commit of the repository instead of an  release and that is why this bug was fixed in Magick.NET. With the latest version of ImageMagick on Windows I am also unable to reproduce your issue.

To solve this issue you will either need to build libraw from source or wait for their next release. And if I remember correctly they are  planning to do a new release in mid September.

**Closed by dlemstra** 2022-08-31 14:09 UTC
