### ISSUE TITLE
Magick limits settings and magick resource usage

### ISSUE THREAD

**Issue by AlexSunnyMan** [ImageMagick/ImageMagick#6610] opened 2023-08-31 10:50 UTC
### ImageMagick version

7.1.1-11

### Operating system

Linux

### Operating system, version and so on

Arch

### Description

Hi!

Limits. From manual https://imagemagick.org/script/command-line-options.php#limit:
Use [-list resource](https://imagemagick.org/script/command-line-options.php#list) to list the current limits. For example, our system shows these limits:
-> identify -list resource
Resource limits:
  Width: 100MP
  Height: 100MP
  Area: 25.181GB
  Memory: 11.726GiB
  Map: 23.452GiB
  Disk: unlimited
  File: 768
  Thread: 12
  Throttle: 0
  Time: unlimited

My identify -list resource returns this:
Resource limits:
  Width: 461.169PP
  Height: 461.169PP
  Area: 66.3442GP
  List length: unlimited
  Memory: 15.447GiB
  Map: 30.8939GiB
  Disk: unlimited
  File: 768
  Thread: 8
  Throttle: 0
  Time: unlimited

When I run magick, it uses one thread however limit is 8! When i set environment variable (https://imagemagick.org/script/resources.php#environment) MAGICK_THREAD_LIMIT to 8 (same 8 as above) magick uses all 8 cores. 
Seems to magick -list Resource, when limits not set (environment or flags), shows maximum resources available magick from the system, bun not actual defaults that magick uses. So when maximum threads not set magick -list Resources shows maximum available threads but uses one. It little bit confuse.

Needs an additional list called Limits: magick -list Limits. 
When called it shows:
-default limits if it is not set throught flags or environment (1 thread default) and indicates this,
-current limit setting if it set throught cmd flag or environment.
-security policy maximum (not relaxed)

For example:
magick -list Limits.
  Width: 10000P           (env)
  Height: 10000P          (env)
  Area: 100000000P      (env)
  List length: unlimited (default)
  Memory: 1GiB            (flag)
  Map: 8GiB                  (flag)
  Disk: 8GiB                  (flag)
  File: 1000                   (flag)
  Thread: 1                   (default)
  Throttle: 0                  (policy limited)
  Time: unlimited         (default)

This list are similar to Resources list, but magick 100% uses values from this list. 
Need define which setting is applied: setting through flags or environment when the same setting is given both through flags and through the environment.

### Steps to Reproduce

See description

### Images

See description

**Comment by dlemstra** [comment] 2023-08-31 11:07
Closing as duplicate of #6609

**Closed by dlemstra** 2023-08-31 11:07 UTC
