### ISSUE TITLE
imagemagick studio library and utility programs has stopped working by using magick command to convert a svg to png

### ISSUE THREAD

**Issue by oneone1995** [ImageMagick/ImageMagick#840] opened 2017-10-15 14:04 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I use the command ```magick``` to convert the ```.svg``` to ```.png```. Than ImageMagick crashed and I get an error message "ImageMagick Studio library and utility programs has stopped working" .However, the ```.png``` convert successfully.
![screengif](https://user-images.githubusercontent.com/12215935/31585447-5d5b63ea-b1f4-11e7-9eb3-c62077ea4e7e.gif)

### Steps to Reproduce

1. this file ```hello.svg```

[hello.zip](https://github.com/ImageMagick/ImageMagick/files/1385918/hello.zip)

2.  type the command:
```shell
magick hello.svg hello.png
```
### System Configuration

- ImageMagick version:ImageMagick-7.0.7-7-Q16-x64-dll
- Environment (Operating system, version and so on):Microsoft Windows 10 Pro
- Additional information:

**Comment by dlemstra** [comment] 2017-10-15 15:51
Your hello.zip file includes the png file?

**Comment by oneone1995** [comment] 2017-10-15 23:56
@dlemstra oh sorry, my mistake. I  upload again.
[hello.zip](https://github.com/ImageMagick/ImageMagick/files/1385918/hello.zip)

**Comment by dlemstra** [comment] 2017-10-16 05:29
Thanks for the correct file. I can reproduce the issue. This looks like something inside glib/librsvg. We will need to investigate this to figure out what is causing this.

**Comment by dlemstra** [comment] 2017-10-17 19:39
This appears to be a bug created by me. When I updated the Pango library to the latest version I forgot to include this fix in the changes we made to the pango library. I just pushed a fix for this to our github repository and this will be resolved in the next release.

**Comment by oneone1995** [comment] 2017-10-19 06:46
@dlemstra  thanks

**Closed** 2017-11-04 09:13 UTC
Labels: bug
