### ISSUE TITLE
make failure since version 7.1.1-24

### ISSUE THREAD

**Issue by slyfox1186** [ImageMagick/ImageMagick#7002] opened 2024-01-04 11:15 UTC
### ImageMagick version

7.1.1-24

### Operating system

Linux

### Operating system, version and so on

Debian 12

### Description

```
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/dng.c:42:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
../coders/dng.c: In function 'SetLibRawParams':
../coders/dng.c:337:13: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  337 |   raw_info->rawparams.max_raw_memory_mb=8192;
      |             ^~~~~~~~~
      |             params
../coders/dng.c:340:15: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  340 |     raw_info->rawparams.max_raw_memory_mb=(unsigned int)
      |               ^~~~~~~~~
      |               params
make[1]: *** [Makefile:10711: coders/dng_la-dng.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/ora.c:45:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/otb.c:41:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/pango.c:42:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/pattern.c:42:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /home/jman/tmp/magick-build-script/workspace/include/CL/cl.h:20,
                 from ../MagickCore/studio.h:149,
                 from ../coders/palm.c:44:
/home/jman/tmp/magick-build-script/workspace/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
make: *** [Makefile:6239: all] Error 2
```

This starts happens in versions 7.1.1-24 & 7.1.1-25.
It does not happen in version 7.1.1-23 or below.

### Steps to Reproduce

run make and this error occurs.

I build opencl headers from the official github repo and source them accordingly during the build.

**Comment by dlemstra** [comment] 2024-01-04 12:37
Duplicate of #6969.

**Closed by dlemstra** 2024-01-04 12:37 UTC
