### ISSUE TITLE
convert -resize leads to core dumped

### ISSUE THREAD

**Issue by moritzschepp** [ImageMagick/ImageMagick#1444] opened 2019-01-08 21:45 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I can't currently convert images and get an error "core dumped", see below. I have tried downgrading to 7.0.8.21 but the error persists.

### Steps to Reproduce
~~~bash
$ curl "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Selfportrait_%28Rembrandt_Harmensz._van_Rijn%29_-_Nationalmuseum_-_22374.tif/lossy-page1-484px-Selfportrait_%28Rembrandt_Harmensz._van_Rijn%29_-_Nationalmuseum_-_22374.tif.jpg" > x.jpg
$ convert x.jpg -resize "80x80>" y.jpg
zsh: abort (core dumped)  convert x.jpg -resize "80x80>" y.jpg
$ 
~~~

### System Configuration

- ImageMagick version:
~~~
Version: ImageMagick 7.0.8-23 Q16 x86_64 2019-01-04 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
~~~
- Environment (Operating system, version and so on): arch linux (updated an hour ago)

Let me know if I can provide more information.

**Comment by dlemstra** [comment] 2019-01-08 22:15
I cannot reproduce the issue with the latest version of ImageMagick under Windows. Is it possible that libjpeg was also updated and that is creating the core dump? Could you check with gdb where the problem is happening?

**Comment by fmw42** [comment] 2019-01-08 22:24
In IM 7 use magick not convert (and not magick convert). Your command as written:

magick x.jpg -resize "80x80>" y.jpg

works fine for me on IM 7.0.8.23 Q16 Mac OSX in a **bash shell** after renaming the downloaded file to x.jpg.

My version is:

`magick -version
Version: ImageMagick 7.0.8-23 Q16 x86_64 2019-01-02 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr png ps raw rsvg tiff webp x xml zlib`

Note I do not have OpenCL installed. I do not know if that will make a difference.

**Comment by dlemstra** [comment] 2019-01-29 21:22
This is most likely an OpenCL issue but I don't really get an extra information from the gdb output. Will close this issue because I don't think we can assist you any further.

**Closed by dlemstra** 2019-01-29 21:22 UTC

**Comment by moritzschepp** [comment] 2019-01-30 08:21
Of course, no problem. Thanks for taking the time to look into this!

**Comment by baack** [comment] 2023-10-31 14:24
I have the same issue with `convert` png to smaller png. Original PNG file is big, like 300+ MiB. What should be done to process such files if I have enough free memory on the PC (GNU/Linux)?
