### ISSUE TITLE
invalid colormap index error

### ISSUE THREAD

**Issue by aghtragh** [ImageMagick/ImageMagick#1477] opened 2019-02-10 21:30 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am getting this error:
```invalid colormap index `a.gif' @ error/colormap-private.h/ConstrainColormapIndex/35```
when I try to use the image, such as:
```magick identify -verbose a.gif```

### Steps to Reproduce
```magick identify -verbose a.gif```

### System Configuration

- ImageMagick version: ImageMagick 7.0.8-27 Q16 x86_64 2019-02-09
- Environment (Operating system, version and so on): CentOS Linux release 7.6.1810
- Additional information:
![a](https://user-images.githubusercontent.com/45968268/52539817-1681a080-2d48-11e9-9d21-2c6c2b8966f7.gif)

**Comment by urban-warrior** [comment] 2019-02-12 12:18
ImageMagick is behaving properly.  The image colormap has 64 entries and one of the indexes exceeds this limit. Due to the image being corrupt, an exception is thrown.

**Comment by aghtragh** [comment] 2019-02-13 03:57
This error has occurred for hundreds of different GIF images while trying to use ImageMagick to extract image information from a large set of images. Those images display fine and other applications do not have problems with these GIF files.

I downloaded the program gifsicle to try and get more information about the colormap of the GIF file. 
Running
```
gifsicle --color-info a.gif
```
gives
```
* a.gif 15 images
  logical screen 1280x960
  global color table [64]
  |   0: #FFFFFF      16: #E9E9E9      32: #D7D7D7      48: #4E4E4E
  |   1: #C3C3C3      17: #A3A3A3      33: #8C8C8C      49: #E7E7E7
  |   2: #DBDBDB      18: #E5E5E5      34: #A7A7A7      50: #E3E3E3
  |   3: #D3D3D3      19: #020202      35: #6E6E6E      51: #7A7A7A
  |   4: #868686      20: #B1B1B1      36: #DEDEDE      52: #828282
  |   5: #767676      21: #9A9A9A      37: #9F9F9F      53: #D9D9D9
  |   6: #676767      22: #929292      38: #5E5E5E      54: #D5D5D5
  |   7: #565656      23: #BDBDBD      39: #D0D0D0      55: #AFAFAF
  |   8: #ACACAC      24: #E1E1E1      40: #C0C0C0      56: #FAFAFA
  |   9: #464646      25: #CDCDCD      41: #969696      57: #F7F7F7
  |  10: #F5F5F5      26: #C8C8C8      42: #FDFDFD      58: #898989
  |  11: #363636      27: #B9B9B9      43: #F3F3F3      59: #3E3E3E
  |  12: #F1F1F1      28: #B5B5B5      44: #CBCBCB      60: #8F8F8F
  |  13: #FBFBFB      29: #F8F8F8      45: #EFEFEF      61: #BBBBBB
  |  14: #EDEDED      30: #161616      46: #EBEBEB      62: #A9A9A9
  |  15: #272727      31: #7E7E7E      47: #C5C5C5      63: #A5A5A5
  background 1
  loop forever
  extensions 1
  + image #0 1280x960
    disposal asis delay 0.30s
  + image #1 453x763 at 827,197 transparent 64
    disposal asis delay 0.30s
  + image #2 397x345 at 681,447 transparent 64
    disposal asis delay 0.30s
  + image #3 533x762 at 747,198 transparent 64
    disposal asis delay 0.30s
  + image #4 431x762 at 849,198 transparent 64
    disposal asis delay 0.30s
  + image #5 350x762 at 930,198 transparent 64
    disposal asis delay 0.20s
  + image #6 233x433 at 1047,527 transparent 1
    disposal asis delay 0.20s
  + image #7 147x66 at 586,454 transparent 64
    disposal asis delay 0.20s
  + image #8 133x73 at 505,440 transparent 64
    disposal asis delay 0.20s
  + image #9 197x59 at 360,440 transparent 64
    disposal asis delay 0.20s
  + image #10 417x381 at 0,249 transparent 64
    disposal asis delay 0.20s
  + image #11 308x725 at 0,235 transparent 64
    disposal asis delay 0.30s
  + image #12 308x864 at 0,96 transparent 64
    disposal asis delay 0.40s
  + image #13 316x162 at 0,308 transparent 64
    disposal asis delay 0.60s
  + image #14 1280x960 transparent 64
    disposal asis delay 0.60s
```
Which verifies that the GIF has one global colormap with 64 entries.
And when I look through the results of 
```
magick identify -verbose a.gif
```
Some of the frames of the GIF have 65 colormap entries:
```
  Colors: 64
  Histogram:
      1077: (  2,  2,  2,255) #020202FF srgba(2,2,2,1)
       415: ( 22, 22, 22,255) #161616FF srgba(22,22,22,1)
       637: ( 39, 39, 39,255) #272727FF srgba(39,39,39,1)
       498: ( 54, 54, 54,255) #363636FF grey21
       397: ( 62, 62, 62,255) #3E3E3EFF srgba(62,62,62,1)
       468: ( 70, 70, 70,255) #464646FF srgba(70,70,70,1)
       481: ( 78, 78, 78,255) #4E4E4EFF srgba(78,78,78,1)
       486: ( 86, 86, 86,255) #565656FF srgba(86,86,86,1)
       541: ( 94, 94, 94,255) #5E5E5EFF grey37
       492: (103,103,103,255) #676767FF srgba(103,103,103,1)
       510: (110,110,110,255) #6E6E6EFF grey43
       370: (118,118,118,255) #767676FF srgba(118,118,118,1)
       255: (122,122,122,255) #7A7A7AFF grey48
       288: (126,126,126,255) #7E7E7EFF gray
       252: (130,130,130,255) #828282FF grey51
       222: (134,134,134,255) #868686FF srgba(134,134,134,1)
       225: (137,137,137,255) #898989FF srgba(137,137,137,1)
       196: (140,140,140,255) #8C8C8CFF grey55
       239: (143,143,143,255) #8F8F8FFF grey56
       266: (146,146,146,255) #929292FF srgba(146,146,146,1)
       257: (150,150,150,255) #969696FF grey59
       314: (154,154,154,255) #9A9A9AFF srgba(154,154,154,1)
       326: (159,159,159,255) #9F9F9FFF srgba(159,159,159,1)
       251: (163,163,163,255) #A3A3A3FF grey64
       159: (165,165,165,255) #A5A5A5FF srgba(165,165,165,1)
       156: (167,167,167,255) #A7A7A7FF srgba(167,167,167,1)
       183: (169,169,169,255) #A9A9A9FF DarkGray
       240: (172,172,172,255) #ACACACFF srgba(172,172,172,1)
       190: (175,175,175,255) #AFAFAFFF srgba(175,175,175,1)
       218: (177,177,177,255) #B1B1B1FF srgba(177,177,177,1)
       333: (181,181,181,255) #B5B5B5FF grey71
       282: (185,185,185,255) #B9B9B9FF srgba(185,185,185,1)
       150: (187,187,187,255) #BBBBBBFF srgba(187,187,187,1)
       192: (189,189,189,255) #BDBDBDFF grey74
       263: (192,192,192,255) #C0C0C0FF silver
       221: (195,195,195,255) #C3C3C3FF srgba(195,195,195,1)
       241: (197,197,197,255) #C5C5C5FF srgba(197,197,197,1)
       284: (200,200,200,255) #C8C8C8FF srgba(200,200,200,1)
       249: (203,203,203,255) #CBCBCBFF srgba(203,203,203,1)
       254: (205,205,205,255) #CDCDCDFF srgba(205,205,205,1)
       305: (208,208,208,255) #D0D0D0FF srgba(208,208,208,1)
       255: (211,211,211,255) #D3D3D3FF LightGray
       211: (213,213,213,255) #D5D5D5FF srgba(213,213,213,1)
       201: (215,215,215,255) #D7D7D7FF srgba(215,215,215,1)
       237: (217,217,217,255) #D9D9D9FF grey85
       298: (219,219,219,255) #DBDBDBFF grey86
       381: (222,222,222,255) #DEDEDEFF grey87
       334: (225,225,225,255) #E1E1E1FF srgba(225,225,225,1)
       266: (227,227,227,255) #E3E3E3FF grey89
       281: (229,229,229,255) #E5E5E5FF grey90
       287: (231,231,231,255) #E7E7E7FF srgba(231,231,231,1)
       279: (233,233,233,255) #E9E9E9FF srgba(233,233,233,1)
       313: (235,235,235,255) #EBEBEBFF grey92
       362: (237,237,237,255) #EDEDEDFF grey93
       385: (239,239,239,255) #EFEFEFFF srgba(239,239,239,1)
       401: (241,241,241,255) #F1F1F1FF srgba(241,241,241,1)
       438: (243,243,243,255) #F3F3F3FF srgba(243,243,243,1)
       508: (245,245,245,255) #F5F5F5FF grey96
       426: (247,247,247,255) #F7F7F7FF grey97
       517: (248,248,248,255) #F8F8F8FF srgba(248,248,248,1)
      1012: (250,250,250,255) #FAFAFAFF grey98
      3326: (251,251,251,255) #FBFBFBFF srgba(251,251,251,1)
      7697: (253,253,253,255) #FDFDFDFF srgba(253,253,253,1)
    313841: (255,255,255,255) #FFFFFFFF white
  Colormap entries: 65
  Colormap:
         0: (255,255,255,255) #FFFFFFFF white
         1: (195,195,195,255) #C3C3C3FF srgba(195,195,195,1)
         2: (219,219,219,255) #DBDBDBFF grey86
         3: (211,211,211,255) #D3D3D3FF LightGray
         4: (134,134,134,255) #868686FF srgba(134,134,134,1)
         5: (118,118,118,255) #767676FF srgba(118,118,118,1)
         6: (103,103,103,255) #676767FF srgba(103,103,103,1)
         7: ( 86, 86, 86,255) #565656FF srgba(86,86,86,1)
         8: (172,172,172,255) #ACACACFF srgba(172,172,172,1)
         9: ( 70, 70, 70,255) #464646FF srgba(70,70,70,1)
        10: (245,245,245,255) #F5F5F5FF grey96
        11: ( 54, 54, 54,255) #363636FF grey21
        12: (241,241,241,255) #F1F1F1FF srgba(241,241,241,1)
        13: (251,251,251,255) #FBFBFBFF srgba(251,251,251,1)
        14: (237,237,237,255) #EDEDEDFF grey93
        15: ( 39, 39, 39,255) #272727FF srgba(39,39,39,1)
        16: (233,233,233,255) #E9E9E9FF srgba(233,233,233,1)
        17: (163,163,163,255) #A3A3A3FF grey64
        18: (229,229,229,255) #E5E5E5FF grey90
        19: (  2,  2,  2,255) #020202FF srgba(2,2,2,1)
        20: (177,177,177,255) #B1B1B1FF srgba(177,177,177,1)
        21: (154,154,154,255) #9A9A9AFF srgba(154,154,154,1)
        22: (146,146,146,255) #929292FF srgba(146,146,146,1)
        23: (189,189,189,255) #BDBDBDFF grey74
        24: (225,225,225,255) #E1E1E1FF srgba(225,225,225,1)
        25: (205,205,205,255) #CDCDCDFF srgba(205,205,205,1)
        26: (200,200,200,255) #C8C8C8FF srgba(200,200,200,1)
        27: (185,185,185,255) #B9B9B9FF srgba(185,185,185,1)
        28: (181,181,181,255) #B5B5B5FF grey71
        29: (248,248,248,255) #F8F8F8FF srgba(248,248,248,1)
        30: ( 22, 22, 22,255) #161616FF srgba(22,22,22,1)
        31: (126,126,126,255) #7E7E7EFF gray
        32: (215,215,215,255) #D7D7D7FF srgba(215,215,215,1)
        33: (140,140,140,255) #8C8C8CFF grey55
        34: (167,167,167,255) #A7A7A7FF srgba(167,167,167,1)
        35: (110,110,110,255) #6E6E6EFF grey43
        36: (222,222,222,255) #DEDEDEFF grey87
        37: (159,159,159,255) #9F9F9FFF srgba(159,159,159,1)
        38: ( 94, 94, 94,255) #5E5E5EFF grey37
        39: (208,208,208,255) #D0D0D0FF srgba(208,208,208,1)
        40: (192,192,192,255) #C0C0C0FF silver
        41: (150,150,150,255) #969696FF grey59
        42: (253,253,253,255) #FDFDFDFF srgba(253,253,253,1)
        43: (243,243,243,255) #F3F3F3FF srgba(243,243,243,1)
        44: (203,203,203,255) #CBCBCBFF srgba(203,203,203,1)
        45: (239,239,239,255) #EFEFEFFF srgba(239,239,239,1)
        46: (235,235,235,255) #EBEBEBFF grey92
        47: (197,197,197,255) #C5C5C5FF srgba(197,197,197,1)
        48: ( 78, 78, 78,255) #4E4E4EFF srgba(78,78,78,1)
        49: (231,231,231,255) #E7E7E7FF srgba(231,231,231,1)
        50: (227,227,227,255) #E3E3E3FF grey89
        51: (122,122,122,255) #7A7A7AFF grey48
        52: (130,130,130,255) #828282FF grey51
        53: (217,217,217,255) #D9D9D9FF grey85
        54: (213,213,213,255) #D5D5D5FF srgba(213,213,213,1)
        55: (175,175,175,255) #AFAFAFFF srgba(175,175,175,1)
        56: (250,250,250,255) #FAFAFAFF grey98
        57: (247,247,247,255) #F7F7F7FF grey97
        58: (137,137,137,255) #898989FF srgba(137,137,137,1)
        59: ( 62, 62, 62,255) #3E3E3EFF srgba(62,62,62,1)
        60: (143,143,143,255) #8F8F8FFF grey56
        61: (187,187,187,255) #BBBBBBFF srgba(187,187,187,1)
        62: (169,169,169,255) #A9A9A9FF DarkGray
        63: (165,165,165,255) #A5A5A5FF srgba(165,165,165,1)
        64: (  0,  0,  0,  0) #00000000 none
```
and some have both 65 colors and 65 colormap entries:
```
  Colors: 65
  Histogram:
     88586: (  0,  0,  0,  0) #00000000 none
       422: (  2,  2,  2,255) #020202FF srgba(2,2,2,1)
       126: ( 22, 22, 22,255) #161616FF srgba(22,22,22,1)
       147: ( 39, 39, 39,255) #272727FF srgba(39,39,39,1)
        96: ( 54, 54, 54,255) #363636FF grey21
        80: ( 62, 62, 62,255) #3E3E3EFF srgba(62,62,62,1)
        80: ( 70, 70, 70,255) #464646FF srgba(70,70,70,1)
        81: ( 78, 78, 78,255) #4E4E4EFF srgba(78,78,78,1)
        89: ( 86, 86, 86,255) #565656FF srgba(86,86,86,1)
       110: ( 94, 94, 94,255) #5E5E5EFF grey37
        90: (103,103,103,255) #676767FF srgba(103,103,103,1)
       102: (110,110,110,255) #6E6E6EFF grey43
        66: (118,118,118,255) #767676FF srgba(118,118,118,1)
        49: (122,122,122,255) #7A7A7AFF grey48
        55: (126,126,126,255) #7E7E7EFF gray
        44: (130,130,130,255) #828282FF grey51
        50: (134,134,134,255) #868686FF srgba(134,134,134,1)
        41: (137,137,137,255) #898989FF srgba(137,137,137,1)
        33: (140,140,140,255) #8C8C8CFF grey55
        37: (143,143,143,255) #8F8F8FFF grey56
        53: (146,146,146,255) #929292FF srgba(146,146,146,1)
        43: (150,150,150,255) #969696FF grey59
        73: (154,154,154,255) #9A9A9AFF srgba(154,154,154,1)
        56: (159,159,159,255) #9F9F9FFF srgba(159,159,159,1)
        55: (163,163,163,255) #A3A3A3FF grey64
        24: (165,165,165,255) #A5A5A5FF srgba(165,165,165,1)
        26: (167,167,167,255) #A7A7A7FF srgba(167,167,167,1)
        37: (169,169,169,255) #A9A9A9FF DarkGray
        34: (172,172,172,255) #ACACACFF srgba(172,172,172,1)
        39: (175,175,175,255) #AFAFAFFF srgba(175,175,175,1)
        44: (177,177,177,255) #B1B1B1FF srgba(177,177,177,1)
        54: (181,181,181,255) #B5B5B5FF grey71
        46: (185,185,185,255) #B9B9B9FF srgba(185,185,185,1)
        31: (187,187,187,255) #BBBBBBFF srgba(187,187,187,1)
        43: (189,189,189,255) #BDBDBDFF grey74
        36: (192,192,192,255) #C0C0C0FF silver
        51: (195,195,195,255) #C3C3C3FF srgba(195,195,195,1)
        40: (197,197,197,255) #C5C5C5FF srgba(197,197,197,1)
        45: (200,200,200,255) #C8C8C8FF srgba(200,200,200,1)
        27: (203,203,203,255) #CBCBCBFF srgba(203,203,203,1)
        46: (205,205,205,255) #CDCDCDFF srgba(205,205,205,1)
        61: (208,208,208,255) #D0D0D0FF srgba(208,208,208,1)
        50: (211,211,211,255) #D3D3D3FF LightGray
        36: (213,213,213,255) #D5D5D5FF srgba(213,213,213,1)
        40: (215,215,215,255) #D7D7D7FF srgba(215,215,215,1)
        43: (217,217,217,255) #D9D9D9FF grey85
        63: (219,219,219,255) #DBDBDBFF grey86
        66: (222,222,222,255) #DEDEDEFF grey87
        57: (225,225,225,255) #E1E1E1FF srgba(225,225,225,1)
        41: (227,227,227,255) #E3E3E3FF grey89
        54: (229,229,229,255) #E5E5E5FF grey90
        47: (231,231,231,255) #E7E7E7FF srgba(231,231,231,1)
        46: (233,233,233,255) #E9E9E9FF srgba(233,233,233,1)
        52: (235,235,235,255) #EBEBEBFF grey92
        68: (237,237,237,255) #EDEDEDFF grey93
        59: (239,239,239,255) #EFEFEFFF srgba(239,239,239,1)
        74: (241,241,241,255) #F1F1F1FF srgba(241,241,241,1)
        82: (243,243,243,255) #F3F3F3FF srgba(243,243,243,1)
        79: (245,245,245,255) #F5F5F5FF grey96
        81: (247,247,247,255) #F7F7F7FF grey97
       115: (248,248,248,255) #F8F8F8FF srgba(248,248,248,1)
       191: (250,250,250,255) #FAFAFAFF grey98
       706: (251,251,251,255) #FBFBFBFF srgba(251,251,251,1)
      1436: (253,253,253,255) #FDFDFDFF srgba(253,253,253,1)
     42131: (255,255,255,255) #FFFFFFFF white
  Colormap entries: 65
  Colormap:
         0: (255,255,255,255) #FFFFFFFF white
         1: (195,195,195,255) #C3C3C3FF srgba(195,195,195,1)
         2: (219,219,219,255) #DBDBDBFF grey86
         3: (211,211,211,255) #D3D3D3FF LightGray
         4: (134,134,134,255) #868686FF srgba(134,134,134,1)
         5: (118,118,118,255) #767676FF srgba(118,118,118,1)
         6: (103,103,103,255) #676767FF srgba(103,103,103,1)
         7: ( 86, 86, 86,255) #565656FF srgba(86,86,86,1)
         8: (172,172,172,255) #ACACACFF srgba(172,172,172,1)
         9: ( 70, 70, 70,255) #464646FF srgba(70,70,70,1)
        10: (245,245,245,255) #F5F5F5FF grey96
        11: ( 54, 54, 54,255) #363636FF grey21
        12: (241,241,241,255) #F1F1F1FF srgba(241,241,241,1)
        13: (251,251,251,255) #FBFBFBFF srgba(251,251,251,1)
        14: (237,237,237,255) #EDEDEDFF grey93
        15: ( 39, 39, 39,255) #272727FF srgba(39,39,39,1)
        16: (233,233,233,255) #E9E9E9FF srgba(233,233,233,1)
        17: (163,163,163,255) #A3A3A3FF grey64
        18: (229,229,229,255) #E5E5E5FF grey90
        19: (  2,  2,  2,255) #020202FF srgba(2,2,2,1)
        20: (177,177,177,255) #B1B1B1FF srgba(177,177,177,1)
        21: (154,154,154,255) #9A9A9AFF srgba(154,154,154,1)
        22: (146,146,146,255) #929292FF srgba(146,146,146,1)
        23: (189,189,189,255) #BDBDBDFF grey74
        24: (225,225,225,255) #E1E1E1FF srgba(225,225,225,1)
        25: (205,205,205,255) #CDCDCDFF srgba(205,205,205,1)
        26: (200,200,200,255) #C8C8C8FF srgba(200,200,200,1)
        27: (185,185,185,255) #B9B9B9FF srgba(185,185,185,1)
        28: (181,181,181,255) #B5B5B5FF grey71
        29: (248,248,248,255) #F8F8F8FF srgba(248,248,248,1)
        30: ( 22, 22, 22,255) #161616FF srgba(22,22,22,1)
        31: (126,126,126,255) #7E7E7EFF gray
        32: (215,215,215,255) #D7D7D7FF srgba(215,215,215,1)
        33: (140,140,140,255) #8C8C8CFF grey55
        34: (167,167,167,255) #A7A7A7FF srgba(167,167,167,1)
        35: (110,110,110,255) #6E6E6EFF grey43
        36: (222,222,222,255) #DEDEDEFF grey87
        37: (159,159,159,255) #9F9F9FFF srgba(159,159,159,1)
        38: ( 94, 94, 94,255) #5E5E5EFF grey37
        39: (208,208,208,255) #D0D0D0FF srgba(208,208,208,1)
        40: (192,192,192,255) #C0C0C0FF silver
        41: (150,150,150,255) #969696FF grey59
        42: (253,253,253,255) #FDFDFDFF srgba(253,253,253,1)
        43: (243,243,243,255) #F3F3F3FF srgba(243,243,243,1)
        44: (203,203,203,255) #CBCBCBFF srgba(203,203,203,1)
        45: (239,239,239,255) #EFEFEFFF srgba(239,239,239,1)
        46: (235,235,235,255) #EBEBEBFF grey92
        47: (197,197,197,255) #C5C5C5FF srgba(197,197,197,1)
        48: ( 78, 78, 78,255) #4E4E4EFF srgba(78,78,78,1)
        49: (231,231,231,255) #E7E7E7FF srgba(231,231,231,1)
        50: (227,227,227,255) #E3E3E3FF grey89
        51: (122,122,122,255) #7A7A7AFF grey48
        52: (130,130,130,255) #828282FF grey51
        53: (217,217,217,255) #D9D9D9FF grey85
        54: (213,213,213,255) #D5D5D5FF srgba(213,213,213,1)
        55: (175,175,175,255) #AFAFAFFF srgba(175,175,175,1)
        56: (250,250,250,255) #FAFAFAFF grey98
        57: (247,247,247,255) #F7F7F7FF grey97
        58: (137,137,137,255) #898989FF srgba(137,137,137,1)
        59: ( 62, 62, 62,255) #3E3E3EFF srgba(62,62,62,1)
        60: (143,143,143,255) #8F8F8FFF grey56
        61: (187,187,187,255) #BBBBBBFF srgba(187,187,187,1)
        62: (169,169,169,255) #A9A9A9FF DarkGray
        63: (165,165,165,255) #A5A5A5FF srgba(165,165,165,1)
        64: (  0,  0,  0,  0) #00000000 none
```
But the extra colormap entries and extra color entries are not colors.
```
(  0,  0,  0,  0) #00000000  #none
```
So shouldn't ImageMagick ignore colors/colormap entries that are not describing colors? The image is perfectly valid but ImageMagick sees the extra faux colormap entry and thinks that it is corrupt, when in reality it is not referencing an extra color so it is a nonissue. 
I found this brought up previously in an issue in another repository:
>IM is incorrect here and I prefer that Gifsicle’s optimization stand. A transparent color **isn’t really in the colormap**: the color value doesn’t matter. I have seen this optimization in GIFs produced by other tools as well.
kohler/gifsicle#113

**Comment by yoya** [comment] 2019-02-14 15:25
It's probably a bug that the identify command displays 65 colors.
it has been fixed in ImageMagick-7.0.8-19.
- https://github.com/ImageMagick/ImageMagick/commit/c807b69de68a33b42fc8725486d5ac81688afd16#diff-9ca9150287325d6210601d883fb559a9

```
% ~/ImageMagick/7.0.8-18/bin/identify -verbose 52539817-1681a080-2d48-11e9-9d21-2c6c2b8966f7.gif | grep Colors | grep 65
  Colors: 65
  Colors: 65
% ~/ImageMagick/7.0.8-19/bin/identify -verbose 52539817-1681a080-2d48-11e9-9d21-2c6c2b8966f7.gif | grep Colors | grep 65
identify: invalid colormap index `52539817-1681a080-2d48-11e9-9d21-2c6c2b8966f7.gif' @ error/colormap-private.h/ConstrainColormapIndex/35.
```
(ImageMagick-7.0.8-18 cause a compile error, I built it with 1 line patch applied)

**Comment by yoya** [comment] 2019-02-14 16:02
The attached GIF file has some frames that refers to the color palette with index:64.
I painted the place of index:64 with gray.

<table>
<tr ><th> 2 </th> <th> 3 </th> <th> 13 </th> <th> 14 </th <tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/26040/52797648-a3ff2080-30b9-11e9-977d-cdb66091c227.png" /></td>
<td><img src="https://user-images.githubusercontent.com/26040/52797662-abbec500-30b9-11e9-9a8d-7f94da8d5144.png" /></td>
<td><img src="https://user-images.githubusercontent.com/26040/52797669-afeae280-30b9-11e9-837a-6803b361cb77.png" /></td>
<td><img src="https://user-images.githubusercontent.com/26040/52797674-b37e6980-30b9-11e9-9a31-730455df6e02.png" /></td>
</tr>
</table>

It seems that interpretation differs depending on implementation depending on the color of pixels of this gray place. (It is undocumented GIF spec, isn's it?)

ImageMagick treats out-range index value as 0. In this case, 0 corresponds to #ffffff so It's painted white.
<table>
<tr> <th> 3 </th> <th> 14 </th> <tr>
<tr>
<td> <img src="https://user-images.githubusercontent.com/26040/52798758-eb86ac00-30bb-11e9-94fb-0815a55445d7.png"> </td>
<td> <img src="https://user-images.githubusercontent.com/26040/52798780-f80b0480-30bb-11e9-95ba-2e4d7b8c1bd6.png"> </td>
</tr>
</table>

For example. macOS preview.app display images that we expected.
I think that an implementation that does not overwrite.
This probably uses the color of the previous frame pixel unchanged.
<table>
<tr> <th> 3 </th> <th> 14 </th> <tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/26040/52799278-db230100-30bc-11e9-9ef1-163a553d3dd9.png"></td>
<td><img src="https://user-images.githubusercontent.com/26040/52799304-ea09b380-30bc-11e9-90a8-735cd6b71fd3.png"> <td>
</tr>
</table>

**Comment by aghtragh** [comment] 2019-02-15 11:22
When I run
```magick identify -verbose 52539817-1681a080-2d48-11e9-9d21-2c6c2b8966f7.gif```
the number of colors is never above the number of colormap entries for any of the frames. So it should be OK, but still gives an exception? I think the identify command output does not match what is happening internally. Or I am misinterpreting the output.

I think the problem is "#00000000 none". ImageMagick is treating it as a color (and falling back to white) instead of ignoring it and keeping those pixels from the previous frame.

Here are some more random GIFs which generate the same exception for me:
![1](https://user-images.githubusercontent.com/45968268/52852066-441a7100-30dd-11e9-99f8-25d71d02c567.gif)
![2](https://user-images.githubusercontent.com/45968268/52852067-441a7100-30dd-11e9-8f56-0f49676cf684.gif)
![4](https://user-images.githubusercontent.com/45968268/52852069-441a7100-30dd-11e9-9394-443940d9bc60.gif)
![5](https://user-images.githubusercontent.com/45968268/52852070-441a7100-30dd-11e9-805a-b457aefc0218.gif)
![6](https://user-images.githubusercontent.com/45968268/52852071-441a7100-30dd-11e9-915a-eecc0eb6fec5.gif)
![7](https://user-images.githubusercontent.com/45968268/52852072-44b30780-30dd-11e9-9b75-c1e98b41309a.gif)
![8](https://user-images.githubusercontent.com/45968268/52852218-95c2fb80-30dd-11e9-95ea-c5fb84e80a8f.gif)

**Comment by yoya** [comment] 2019-02-15 16:37
I examined the attached GIF files. Each file has some index values out of the palette.

identify command aggregates not the indices directly in the GIF file but the indices imported into ImageMagick internal representation via the GIF coder.

![image](https://user-images.githubusercontent.com/26040/52868396-8a77da80-3186-11e9-8e0d-d254bc185758.png)

If ImageMagick finds an index value out of the palette in the GIF file, it issues a warning with exception and takes it as 0.
Since ImageMagick aggregates indices after it falls within the range, 64 is displayed.

**Comment by urban-warrior** [comment] 2019-02-16 12:02
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Closed** 2019-02-18 13:53 UTC
