### ISSUE TITLE
ZUGFeRD (Factur-X) invoices cannot be converted with ImageMagick

### ISSUE THREAD

**Issue by Choppel** [ImageMagick/ImageMagick#7567] opened 2024-08-19 09:08 UTC
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Linux Mint

### Description

Converting an e-invoice in ZUGFeRD format results in the message `convert-im6.q16: undefined variable `ConformanceLevel' @ error/fx.c/FxGetSymbol/1135.`

The image is created, but the command line call returns 1 which is bad for automatization.

### Steps to Reproduce

Download [MustangGnuaccountingBeispielRE-20201121_508.pdf](https://github.com/user-attachments/files/16658159/MustangGnuaccountingBeispielRE-20201121_508.pdf)
and call `convert MustangGnuaccountingBeispielRE-20201121_508.pdf PNG32:test.png` 

### Images

![grafik](https://github.com/user-attachments/assets/f94e47a7-352f-4b63-87e0-822a1ae4f689)

**Comment by snibgo** [comment] 2024-08-19 10:51
With IM 7.1.1-20, the problem does not occur, whether using just `magick` or `magick convert`.

With `convert` v6.1.12-72, the problem does occur:
```
convert.exe: undefined variable `ConformanceLevel' @ error/fx.c/FxGetSymbol/1139.
```
This is an old `fx.c`. After I re-wrote it, it no longer has a function `FxGetSymbol()`.

I notice that the PDF file contains the following:
```
      <rdf:Description xmlns:fx="urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#"
                       rdf:about="">
         <fx:ConformanceLevel>EN 16931</fx:ConformanceLevel>
         <fx:DocumentType>INVOICE</fx:DocumentType>
         <fx:DocumentFileName>factur-x.xml</fx:DocumentFileName>
         <fx:Version>1.0</fx:Version>
      </rdf:Description>
```
It seems that IM sees `<fx:ConformanceLevel>` and, for some reason, calls IM `fx:` processing. It should not do this. I suspect the problem is somewhere in `coders/pdf.c`.

**Comment by snibgo** [comment] 2024-08-19 12:45
Even more weirdly, the problem occurs when writing to PNG, but not to TIFF:
```
C:\web\im>%IM%convert -background White MustangGnuaccountingBeispielRE-20201121_508.pdf -layers flatten x.png
convert.exe: undefined variable `ConformanceLevel' @ error/fx.c/FxGetSymbol/1139.

C:\web\im>%IM%convert -background White MustangGnuaccountingBeispielRE-20201121_508.pdf -layers flatten x.tiff
[Succeeds]
```

**Comment by snibgo** [comment] 2024-08-19 14:51
`-debug all` shows the error message is generated within the execution of png.c/WriteOnePNGImage:
```
convert -debug all MustangGnuaccountingBeispielRE-20201121_508.pdf x.png
```
This creates exceptions:
```
color.c/GetColorCompliance/1057/Exception
  unrecognized color `ConformanceLevel'
2024-08-19T13:53:19+00:00 0:00.118 0.109u 6.9.12 Exception convert.exe[10060]: fx.c/FxGetSymbol/1139/Exception
  undefined variable `ConformanceLevel'
```
I don't know why WriteOnePNGImage() has any record of "ConformanceLevel", or why it thinks this may be a colour or an fx expression.

I'm looking into this, but have low confidence that I will track down the bug.

**Comment by urban-warrior** [comment] 2024-08-19 16:04
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Closed** 2024-08-19 16:05 UTC

**Comment by Choppel** [comment] 2025-01-29 09:29
The problem still persists. Was this really fixed?

I just noticed that this project is for version 7 of imagemagick. I am using version 6 (as stated above). Should I open another issue at https://github.com/ImageMagick/ImageMagick6  ?
