### ISSUE TITLE
command line tools change 'pause' statement

### ISSUE THREAD

**Issue by cweller70** [ImageMagick/ImageMagick#6547] opened 2023-08-06 15:55 UTC
### ImageMagick version

7.1.1-15 (ImageMagick-7.1.1-15-portable-Q16-x64.zip)

### Operating system

Windows

### Operating system, version and so on

Windows 7 64bit Professional (German version)

### Description

After using any of the command line tools (e. g. magick.exe) the windows-specific 'pause' command does not create output anymore.

### Steps to Reproduce

1. open a windows command prompt in ImageMagick folder
2. execute 'pause' to verify that the pause statement works as expected, i. e. it displays the usual 'press any key to continue' message
3. execute 'magick.exe -version'
4. execute 'pause' again and observe the behavior, i. e. it does not display anything (but it still requires a key to be pressed)

### Images

![output](https://github.com/ImageMagick/ImageMagick/assets/141572509/fce55579-bb3f-4bd8-844a-5b1fcb916dbf)

**Comment by dlemstra** [comment] 2023-08-06 17:48
I cannot reproduce your issue on Windows. I suspect this is caused by something on your own system.

**Comment by snibgo** [comment] 2023-08-06 18:25
I can't reproduce the problem with Windows 11 [Version 10.0.22621.1992] and IM v7.1.1-15.

**Comment by cweller70** [comment] 2023-08-07 18:13
It might be the case that it happends only on windows 7. I can reproduce it using the "ImageMagick-7.1.1-15-portable-Q16-x64.zip" variant even on a fresh Windows 7 installation.

I can't reproduce it on Windows 10 version 22H2.

**Comment by dlemstra** [comment] 2023-08-07 20:51
Windows 7 is EOL so I will close this issue because I cannot reproduce this on a recent windows version.

**Closed by dlemstra** 2023-08-07 20:51 UTC
