### ISSUE TITLE
Compiling from source fail on Ubuntu Trusty

### ISSUE THREAD

**Issue by redserpent7** [ImageMagick/ImageMagick#155] opened 2016-03-27 14:25 UTC
I am trying to compile and install from source on Ubuntu 14.04 but make gets interrupted with the following error:

```/bin/grep: /usr/lib/x86_64-linux-gnu/libjpeg.la: No such file or directory
/bin/sed: can't read /usr/lib/x86_64-linux-gnu/libjpeg.la: No such file or directory
libtool:   error: '/usr/lib/x86_64-linux-gnu/libjpeg.la' is not a valid libtool archive
make[1]: *** [MagickCore/libMagickCore-7.Q16HDRI.la] Error 1
make[1]: Leaving directory `/home/ubuntu/JImages/ImageMagick/imagemagick/ImageMagick-master'
make: *** [all] Error 2```


I checked and I do not have libjpeg.la on my system and it seems that it no longer installs with libjpeg-ve

Is there another way around this?

**Comment by mikayla-grace** [comment] 2016-04-28 23:40
The problem is associated with your release of libjpeg.  Do you have an upgrade path?  Is so, try the latest release of libjpeg.  Otherwise you need to correct the problem with libjpeg.la or configure ImageMagick with the --without-jpeg option.

**Comment by dlemstra** [comment] 2016-05-29 08:47
Are you still getting this build error @redserpent7 or can we/you close this issue?

**Closed** 2016-06-24 18:45 UTC
