### ISSUE TITLE
Error: convert-im6.q16: improper image header

### ISSUE THREAD

**Issue by Luccio96** [ImageMagick/ImageMagick#4661] opened 2022-01-04 07:23 UTC
### ImageMagick version

ImageMagick 6.9.10-23 Q16 x86_64 20190101 

### Operating system

Linux

### Operating system, version and so on

Debian 9 - Linux 4.19.208-1

### Description

I'm trying to convert a multi channel psd file, however every time ImageMagick returns: "convert-im6.q16: improper image header"

Even using: "identify -verbose" I got the same error.

I can open the file with photoshop without any issue.
[test.zip](https://github.com/ImageMagick/ImageMagick/files/7805951/test.zip)

The psd file is attached.

### Steps to Reproduce

`convert "test.psd" -flatten  -thumbnail 256x256 "test.jpg"`

**Comment by dlemstra** [comment] 2022-01-04 07:44
Duplicate of #4656.

**Closed by dlemstra** 2022-01-04 07:44 UTC
