### ISSUE TITLE
SVG text with font issue (Type 1)

### ISSUE THREAD

**Issue by GitS7** [ImageMagick/ImageMagick#5127] opened 2022-05-06 12:45 UTC
### ImageMagick version

7.1.0-32

### Operating system

Windows

### Operating system, version and so on

Windows 7, Windows 10

### Description

SVG file with text command with font is rendered incorrectly. Example:

```
<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
  <text x="20" y="35" font-size="12">Normal</text>
  <text x="20" y="55" font-size="12" font-family="Helvetica">Helvetica</text>
  <text x="20" y="75" font-size="12" font-family="'Helvetica'">'Helvetica'</text>
</svg>

```
When converting SVG to TIFF, the text with Helvetica font is displayed incorrectly (image 1). With an earlier version 7.0.10, the text is displayed correctly (image 2).

### Steps to Reproduce

Render the SVG-Code to TIFF:

[helvetica.svg](https://user-images.githubusercontent.com/105055946/167133781-5e173d6e-ce46-4043-95ec-043e50cd98a4.svg)

### Images

Image 1:
![image1](https://user-images.githubusercontent.com/105055946/167133424-08674d96-16e3-4cd3-892a-6dea95a1fc46.png)
Image 2:
![image2](https://user-images.githubusercontent.com/105055946/167133468-83c8edaa-38f0-4d26-b0ed-a4675187ce02.png)

**Comment by urban-warrior** [comment] 2022-05-06 13:07
Add `-debug annotate` to your command-line for 7.1.10 and 7.0.10.  Can you spot any difference in the font it settles on to render Helvetica?  If the debugging looks like gibberish to you, post the output from both releases here so we can review.

**Comment by GitS7** [comment] 2022-05-06 15:18
With the new ImageMagick version 7.1.0 an internal message appears with the parameter `-debug All`:

* (process:5092): WARNING **: 17:10:45.346: Invalid UTF-8 string passed to pango_layout_set_text()
2022-05-06T15:10:45+00:00 0:00.064 0.063u 7.1.0 Pixel convert.exe[5092]: pixel.c/SetPixelChannelMask/6293/Pixel

Without the debug parameter, no error message appears.

**Comment by urban-warrior** [comment] 2022-05-06 16:10
The problem may be with Pango then.  We need to be able to reproduce the issue before we can comment further.  Post a method to reproduce the issue here.

**Comment by GitS7** [comment] 2022-05-06 18:55
steps to reproduce;
1. use ImageMagick latest version 7.1.0-32 portable q16 x86: https://imagemagick.org/script/download.php ([ImageMagick-7.1.0-portable-Q16-x86.zip](https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-portable-Q16-x86.zip)), extract the zip file anywhere.
2. copy this svg file to the ImageMagic-folder: [helvetica.svg](https://user-images.githubusercontent.com/105055946/167198951-62166870-55a4-4166-9350-9bbc391bd6f3.svg)
3. launch terminal, go to the ImageMagic folder
4. execute this command: `convert.exe helvetica.svg helevtica.tif`
5. I have to correct myself. The warning from above appears ion the console.

**Comment by fmw42** [comment] 2022-05-06 19:15
The convert seems to work fine for me on either Imagemagick 6.9.12-47 or Imagemagick  7.1.0-32 on Mac OSX Monterey with Inkscape installed as the SVG renderer and when using IM 7, using magick not convert.

I get these two TIFF images for IM 6 and IM 7

[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/8643140/Archive.zip)

What SVG renderer are you using: the internal Imagemagick MSVG, the RSVG delegate, or Inkscape?

**Comment by dlemstra** [comment] 2022-05-06 19:15
It must be something with your system. I am unable to reproduce this issue. I am getting a different warning message though:

> ** (process:51400): WARNING **: 21:13:28.118: couldn't load font "Helvetica Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.

> ** (process:51400): WARNING **: 21:13:28.126: couldn't load font "'Helvetica' Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.

But the output looks like this:

![helevtica](https://user-images.githubusercontent.com/10426229/167203293-4d562a84-d428-4a35-8076-ed8905b8163a.png)

**Comment by urban-warrior** [comment] 2022-05-07 00:51
We tried portable versions of ImageMagick under Windows and Linux and they returned expected results.   Your version may be using a different font than us.  Type `magick.exe -list font` to display which fonts ImageMagick sees on your system.  Add `-debug annotate` to see the specific font.  If your version of ImageMagick utilizes `pango`, the issue could be with `pango`.

**Comment by GitS7** [comment] 2022-05-07 06:45
> The convert seems to work fine for me on either Imagemagick 6.9.12-47 or Imagemagick 7.1.0-32 on Mac OSX Monterey with Inkscape installed as the SVG renderer and when using IM 7, using magick not convert.
> 
> I get these two TIFF images for IM 6 and IM 7
> 
> [Archive.zip](https://github.com/ImageMagick/ImageMagick/files/8643140/Archive.zip)
> 
> What SVG renderer are you using: the internal Imagemagick MSVG, the RSVG delegate, or Inkscape?

An external SVG renderer is not used. Thus, the ImageMagic internal SVG renderer is in use.

**Comment by GitS7** [comment] 2022-05-07 07:08
> It must be something with your system. I am unable to reproduce this issue. I am getting a different warning message though:
> 
> > ** (process:51400): WARNING **: 21:13:28.118: couldn't load font "Helvetica Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.
> 
> > ** (process:51400): WARNING **: 21:13:28.126: couldn't load font "'Helvetica' Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.
> 
> But the output looks like this:
> 
> ![helevtica](https://user-images.githubusercontent.com/10426229/167203293-4d562a84-d428-4a35-8076-ed8905b8163a.png)

The same system was used for the test with version 7.0.10 and version 7.1.0. Success with 7.0.10 and failure with 7.1.0. The Helvetica font is not required for the test.

**Comment by GitS7** [comment] 2022-05-07 07:57
I have performed the test exactly according to the above instructions on another system. The result is the same.
Note: To reproduce, please use only the indicated portable version. Use Windows 10. Do not use any other software like SVG renderer.

**Comment by GitS7** [comment] 2022-05-07 08:06
> We tried portable versions of ImageMagick under Windows and Linux and they returned expected results. Your version may be using a different font than us. Type `magick.exe -list font` to display which fonts ImageMagick sees on your system. Add `-debug annotate` to see the specific font. If your version of ImageMagick utilizes `pango`, the issue could be with `pango`.

On the test system, Helvetica was installed but not included in the ImageMagick font list. The problem is that the text is replaced by boxes. Not necessarily in the rendering of the exact font.

**Comment by dlemstra** [comment] 2022-05-07 09:11
As I said before I am unable to reproduce your issue. I was using the same portable version to test this. I downloaded your file and executed the command you provided. I then got the output image that I posted earlier. So it most be something on your system or maybe some strange file encoding in your test file?

**Comment by GitS7** [comment] 2022-05-07 10:14
> As I said before I am unable to reproduce your issue. I was using the same portable version to test this. I downloaded your file and executed the command you provided. I then got the output image that I posted earlier. So it most be something on your system or maybe some strange file encoding in your test file?

I just ran the test again on an older system, Windows 7, almost original fonts. Here the test was successful. The UTF-8 warning also appeared, but text appeared in the image.
But a portable application should be system independent. In my current systems, version 7.1.0 does not work successfully. However, the old version 7.0.10 works. See topic.

**Comment by GitS7** [comment] 2022-05-07 10:59
Would it be possible to enable DEBUGGING of pango via the -debug parameter? The corresponding commands PING are already included in the source code, but reserved for conditional compilation.

**Comment by dlemstra** [comment] 2022-05-07 11:36
This seems to be something on your system that is causing this issue. System independent doesn't it works on every machine. Something on your machine is causing this issue. We will have to leave it up to you to find the cause since we don't have/want access to your machine. If you want to debug this it would probably be a good idea to build ImageMagick from source and then debug through the application to find the issue.

**Comment by GitS7** [comment] 2022-05-08 07:38
With version 7.0.10, the ImageMagick version I have been using until now, everything works fine on all machines. 
With the new version 7.1.0 it does not work anymore! **This version has a dependency on the system.** The version 7.1.0 is NOT portable anymore. 
To all involved: Did you have the UTF-8 warning on the console?

**Comment by GitS7** [comment] 2022-05-08 08:06
> using magick not convert.

So that we can see your results, here the PNGs:
![helvetica6.png](https://user-images.githubusercontent.com/105055946/167287355-65ac6b4d-ff7c-4386-923f-e606779274af.png)
![helvetica7.png](https://user-images.githubusercontent.com/105055946/167287375-3ea784d1-e61e-441d-b580-0f646f07aac6.png)

**Comment by GitS7** [comment] 2022-05-08 08:12
> The convert seems to work fine for me on either Imagemagick 6.9.12-47 or Imagemagick 7.1.0-32 on Mac OSX Monterey with Inkscape installed as the SVG renderer and when using IM 7, using magick not convert.
> 
> I get these two TIFF images for IM 6 and IM 7
> 
> [Archive.zip](https://github.com/ImageMagick/ImageMagick/files/8643140/Archive.zip)
> 
> What SVG renderer are you using: the internal Imagemagick MSVG, the RSVG delegate, or Inkscape?

So that we can see your result, here the PNGs:

![helvetica6.png](https://user-images.githubusercontent.com/105055946/167287482-df8a35d9-bb03-4f36-a528-f0ff20482539.png)
![helvetica7.png](https://user-images.githubusercontent.com/105055946/167287486-4b0fe0d5-1814-4086-89ce-737278997a00.png)
The first line is printed in Serif in my case (see above), but here in Sans Serif.
The second and third line appear OK.

**Comment by GitS7** [comment] 2022-05-08 08:23
Testing of the fonts:

[helvetica2.svg](https://user-images.githubusercontent.com/105055946/167287671-52b15a4b-3d60-43fd-9bb4-e79577840b4f.svg)

Your Browser:

![helvetica2.svg](https://user-images.githubusercontent.com/105055946/167287671-52b15a4b-3d60-43fd-9bb4-e79577840b4f.svg)

Code:

```
<svg viewBox="0 0 400 160" xmlns="http://www.w3.org/2000/svg">
  <text x="20" y="30" font-size="20" font-family="Sans">(GR) Sans</text>
  <text x="20" y="60" font-size="20" font-family="Arial">(GR) Arial</text>
  <text x="20" y="90" font-size="20" font-family="Helvetica">(GR) Helvetica</text>
  <text x="20" y="120" font-size="20" font-family="'Helvetica'">(GR) 'Helvetica'</text>
</svg>

```
To recognize the correct representation of the fonts, the bracket with (GR) was inserted.

![helvetica2_7-0-10](https://user-images.githubusercontent.com/105055946/167287785-d44bde19-3ec6-48d4-b595-3e71c2a7acd0.png)

Result of the portable version 7.1.0-32 for Windows:

![helvetica2_7-1-0](https://user-images.githubusercontent.com/105055946/167287855-13ffc1ab-c75a-4423-80a4-5bd4b3931b36.png)

**Comment by urban-warrior** [comment] 2022-05-08 12:28
We tried with portable ImageMagick 7.1.0-33 for Windows and we are getting expected results.  The font rendering looks fine.

**Comment by GitS7** [comment] 2022-05-08 12:46
Please render helvetica2.svg as PNG and post it.  Please also tell if the UTF-8 warning appears. Thank you very much for your efforts.

[helvetica2.svg](https://user-images.githubusercontent.com/105055946/167296791-58e4ec76-92cf-4ba6-a0e2-725b3ed35fde.svg)

**Comment by fmw42** [comment] 2022-05-08 15:02
Works fine for me with no error messages using Inkscape in Imagemagick as the SVG renderer. 

`magick -density 300 167296791-58e4ec76-92cf-4ba6-a0e2-725b3ed35fde.svg x.png`


![x](https://user-images.githubusercontent.com/13458218/167302346-b66b5bcb-ce47-4df0-b228-760ac8d95a22.png)

**Comment by GitS7** [comment] 2022-05-27 13:37
I would be happy to examine the code and compile the portable application myself. 

For this I used a fresh Windows 10 and the Visual Studio 2022 Community. 

a) I followed the instructions (https://imagemagick.org/script/install-source.php, Install from Windows Source), but without success.

b) After that, I tried compiling again according to the instructions (https://github.com/ImageMagick/ImageMagick-Windows). Also without success.

Are there any other dependencies in the source code that I need to install first? 

Perl, Python, or other software?

**Comment by GitS7** [comment] 2022-06-13 11:26
The cause of the problem has been found. The pango package has removed support for Type 1 fonts. If the Helvetica font was installed as a Type 1 font, pango reads this font but cannot process it. This is a bug in pango. 

pangowin32-fontmap.c, function create_standard_family

Change
```  
  new_family->faces = g_slist_append (new_family->faces, new_face);
```
to
```
  if (new_face->has_cmap)
  {
    new_family->faces = g_slist_append (new_family->faces, new_face);
  }
```
and it will work.

Of course, the Helvetica font must be available as an supported font, for example OTF.

**Comment by dlemstra** [comment] 2023-07-02 18:43
Closing this issue because this should be reported upstream.

**Closed by dlemstra** 2023-07-02 18:43 UTC
