### ISSUE TITLE
JPEG processed by convert has disallowed "density" 0x0

### ISSUE THREAD

**Issue by johnwhitington** [ImageMagick/ImageMagick#7120] opened 2024-02-21 18:38 UTC
### ImageMagick version

7.1.1-28

### Operating system

Linux

### Operating system, version and so on

MacOS 14.3.1

### Description

I am doing some automatic processing of JPEGs to reduce their quality. Consider the attached file 512x1 file:

```
$ file convertin.jpg
convertin.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1], baseline, precision 8, 512x1, components 3
```

Now, we run

```
convert convertin.jpg -quality 65% convertout.jpg
```

And the result is:

```
$ file convertout.jpg
convertout.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 0x0, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1], baseline, precision 8, 512x1, components 3
```

Note that density 0x0 is not allowed here: Xdensity and YDensity must both be non-zero. See the bottom paragraph on page 7 of the spec here:

https://www.w3.org/Graphics/JPEG/jfif3.pdf

This causes programs which place the JPEG file on the page (e.g PDF) to miscalculate and misrender.

Hunch: this is a miscalculation in imagemagick due to the file only being 1 pixel high.

![convertin](https://github.com/ImageMagick/ImageMagick/assets/1702581/c040b1b5-371b-4ea6-90e7-f47f9e18fad0)
![convertout](https://github.com/ImageMagick/ImageMagick/assets/1702581/9484552f-690b-461f-a0dd-5e955c9ba104)

### Steps to Reproduce

As above.

**Comment by fmw42** [comment] 2024-02-21 20:04
Possibly happens because the file does not have the units specified.  Try adding -units pixelsperinch to your convert command. Also I recommend using magick rather than convert on Imagemagick 7.

**Comment by snibgo** [comment] 2024-02-21 23:25
> Consider the attached file 512x1 file

I can't see an attached file.

I can reproduce the problem:

```
D:\temp>%IMG7%magick x.jpg -verbose info:

D:\temp>file x.jpg
x.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 0x0, segment length 16, baseline, precision 8, 1x1, components 1
```
When there is no density, IM seems to set Xdensity and Ydensity to zero.

**Comment by johnwhitington** [comment] 2024-02-21 23:39
Because they are JPEGs, Github shows them inline, unhelpfully in this case. Happy to send them another way - just let me know.

**Comment by fmw42** [comment] 2024-02-21 23:52
You can zip them and post the zip file on this forum or upload to some free hosting service and put the URL in a comment

**Comment by dlemstra** [comment] 2024-02-22 05:57
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Closed** 2024-03-10 15:35 UTC
