### ISSUE TITLE
Gray background while converting pdf on Mac OS

### ISSUE THREAD

**Issue by Zzzenk** [ImageMagick/ImageMagick#4811] opened 2022-02-05 08:58 UTC
### ImageMagick version

7.1.0-22

### Operating system

MacOS

### Operating system, version and so on

12.2

### Description

I try to convert .pdf to .png and output files have gray background instead of white.
On Windows imagick convert with white background.

[HSK_3.19-3.pdf](https://github.com/ImageMagick/ImageMagick/files/8007673/HSK_3.19-3.pdf)

```
Version: ImageMagick 7.1.0-22 Q16-HDRI x86_64 2022-01-29 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0) 
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Compiler: gcc (4.2)

```

### Steps to Reproduce

```
$imagick = new Imagick();
$imagick->setResolution(150, 150);
$imagick->readImage($row);
$imagick->setImageFormat("png");
$imagick->writeImages($uploaddir . uniqid($filename) . ".png", true);
```

I also tried to convert via command line with different options of -alpha
`convert HSK.3.19-3.pdf[0] -background white -alpha background -alpha off x.png`

### Images

![152240443-2e1f6b39-9c2a-4fbe-95f5-bfca60a54b0c](https://user-images.githubusercontent.com/2630902/152635164-f98b0426-f7cc-4d18-b22f-bc46d8ce9a38.png)

**Comment by dlemstra** [comment] 2022-02-05 09:02
Please don't create a duplicate of your discussion.

**Closed by dlemstra** 2022-02-05 09:02 UTC
