### ISSUE TITLE
After updated imagick from 6.9.3-7 to 7.0.7-11 ImagickDraw::setClipPath not working anymore.

### ISSUE THREAD

**Issue by by12** [ImageMagick/ImageMagick#1506] opened 2019-03-11 14:45 UTC
After updated imagick from 6.9.3-7 to 7.0.7-11 ImagickDraw::setClipPath not working anymore.

i am using window 7. php 7.3 and had php 7.0 before.
with php 7.0 and imagick 6.9.3-7 ImagickDraw::setClipPath was working as expected.
with php 7.3 and imagick 7.0.7-11 it's not clipping the object anymore.

please help! 

see http://php.net/manual/de/imagickdraw.setclippath.php for an example.

**Comment by dlemstra** [comment] 2019-03-11 15:09
Can you reproduce your issue with the latest version?

**Comment by urban-warrior** [comment] 2019-03-15 23:08
We'll need a full working example that illustrates the problem.  The link you provided is not a complete example.   Once we can reproduce the problem, we should be able to discover and fix it in short order.

**Comment by djenric** [comment] 2019-03-16 16:25
Hello, here is an working example:

`<?php

$draw = new \ImagickDraw();
$draw->setStrokeColor('black');
$draw->setFillColor('red');
$draw->setStrokeOpacity(1);
$draw->setStrokeWidth(2);

$clipPathName = 'testClipPath';

$draw->pushClipPath($clipPathName);
$draw->rectangle(0, 0, 250, 250);
$draw->popClipPath();
$draw->setClipPath($clipPathName);
$draw->rectangle(100, 100, 400, 400);

$imagick = new \Imagick();
$imagick->newImage(500, 500, 'yellow');
$imagick->setImageFormat("png");

$imagick->drawImage($draw);

header("Content-Type: image/png");
echo `$imagick->getImageBlob();`

Red rectangle should be clipped, but has been drawn completely. With old version it was working. It seems that clipping is drawn white instead.

**Comment by urban-warrior** [comment] 2019-03-16 16:48
We get this result for the latest releases of ImageMagick 7.0.8-34 and 6.9.10-34:

<img src="https://user-images.githubusercontent.com/12486802/54478442-87edbc80-47e8-11e9-8720-1fed2b5fe44a.png" alt="ImagickDraw::setClipPath" width="250"/>

Is that what you are expecting?  If not, how should the resulting image appear?

**Comment by djenric** [comment] 2019-03-16 20:06
I see that image:

![imagick](https://user-images.githubusercontent.com/17013405/54480861-27816e00-482e-11e9-8c4d-7c0abab4641c.png)

but it should be like your image. In 6.9.3-7 i have the right behaviour. But not in 7.0.7-11. The problem is that imagick till php 7.1 is compiled against 6.9.3-7 and since php 7.2 against 7.0.7-11. You can see it here:

https://mlocati.github.io/articles/php-windows-imagick.html

So i have no possibility to check it with 7.0.8-34 on windows so far i know. Are you testing on linux?

**Comment by djenric** [comment] 2019-03-19 19:52
As i have seen now, there is also rererence to 7.0.8-34 in phpinfo:

![env](https://user-images.githubusercontent.com/17013405/54637382-d1f4cd80-4a88-11e9-8cee-416d6e8765af.JPG)

Maybe this is helpfull?

**Comment by djenric** [comment] 2019-03-23 16:22
I tried now with imagemagick 7.0.8-34 installed on system and as you can see on image above and also 7.0.7-11 taken from https://mlocati.github.io/articles/php-windows-imagick.html. You can see here:

![imagick env2](https://user-images.githubusercontent.com/17013405/54868696-9b23fd80-4d8f-11e9-8c5c-6e6968a8be2d.JPG)

Only difference is that 7.0.7-11 ist using white to draw clipping and 7.0.7-34 is using flill color or black for transparent fill color.

But behauviour is same. I also tried Windows 7 and 10 with same result.

No more ideas what we can do?

**Comment by urban-warrior** [comment] 2019-03-23 19:25
ImageMagick version 7.0.7-11 may likely be in the php path suggesting even if you install 7.0.8-34, php will still use 7.0.7-11. As mentioned, we're using 7.0.8-34 and your script returns expected results.

**Comment by djenric** [comment] 2019-03-23 20:23
I compiled now also ImageMagick 7.0.8-34 and Imagick 3.4.3 from scratch. But still with same result.

![imagick env3](https://user-images.githubusercontent.com/17013405/54871251-76d91880-4db1-11e9-8651-39ac5803dddf.JPG)

I'am slowly out of ideas.

**Comment by urban-warrior** [comment] 2019-03-23 20:25
We're out of ideas too.  As you can see from the above image we posted, we are getting expected results with ImageMagick 7.0.8-34, imagick 3.4.3-8, and php 7.2.15.

**Comment by dlemstra** [comment] 2019-03-23 20:44
It looks like 716ec522cf4997a008905666610fe461840c5b48 broke this. I have the same problem with Magick.NET where the clip mask is also negated.

**Comment by djenric** [comment] 2019-03-23 20:56
After reverting these changes in source and compiling CORE_RL_MagickCore_.dll i have now this result:

![result](https://user-images.githubusercontent.com/17013405/54871554-23b59480-4db6-11e9-87fe-d4f94de9ccce.png)

So, he is clipping now, but still also drawing clip rect. Maybe this is part of the solution?

**Comment by djenric** [comment] 2019-03-23 23:57
So, i can not imagine how you can get the right result. I checked now the code from 7.0.8-34 against 6.9.3-7. From line 3239 we have following code:

```
if (LocaleCompare("clip-path",token) == 0)
{
char
  name[MaxTextExtent];

const char
  *clip_path;

GetNextToken(q,&q,extent,token);
(void) FormatLocaleString(name,MaxTextExtent,"%s",token);
clip_path=(const char *) GetValueFromSplayTree(macros,name);
if (clip_path != (const char *) NULL)
  (void) SetImageArtifact(image,name,clip_path);
break;
}
```

I took now the old code and modified it to work with new functions like that:

```
if (LocaleCompare("clip-path",token) == 0)
{
char
  name[MaxTextExtent];

const char
  *clip_path;

GetNextToken(q,&q,extent,token);
(void) FormatLocaleString(name,MaxTextExtent,"%s",token);
/*clip_path=(const char *) GetValueFromSplayTree(macros,name);
if (clip_path != (const char *) NULL)
  (void) SetImageArtifact(image,name,clip_path);*/
for (p = q; *q != '\0'; )
{
	GetNextToken(q, &q, extent, token);
	if (LocaleCompare(token, "pop") != 0)
		continue;
	GetNextToken(q, (const char **)NULL, extent, token);
	if (LocaleCompare(token, "clip-path") != 0)
		continue;
	break;
}
(void)CopyMagickString(token, p, (size_t)(q - p - 4 + 1));
(void)SetImageArtifact(image, name, token);
GetNextToken(q, &q, extent, token);
break;
}
```

I think GetValueFromSplayTree should replace the old code. But token pointer keeps now unchanged and clipping objects will additional be drawn.

Together with the hint from dlemstra it seems to work now. It would be nice to get it fixed.

**Comment by urban-warrior** [comment] 2019-03-24 00:28
We're working on the problem.  When we have a robust patch, we'll post here.

**Comment by djenric** [comment] 2019-03-28 09:12
Hi. Will the second part of the bug with drawing the clipping objects also be fixed in next time?

**Comment by urban-warrior** [comment] 2019-03-30 12:09
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Closed** 2019-04-14 15:58 UTC
Labels: bug
