### ISSUE TITLE
Cannot execute commands containing -fx

### ISSUE THREAD

**Issue by hellocatfood** [ImageMagick/ImageMagick#1367] opened 2018-10-24 12:08 UTC
### Description
I'm attempting to use the fx command on an image. In particular I'm attempting to run the example from here: http://www.imagemagick.org/Usage/quantize/#diy_symbols

```
  montage dpat_symbols.gif   -geometry +5+0 \
          -tile x1 -background none -mattecolor blue  -frame 3 \
          dpat_syms_images.gif
  convert eyes.gif -alpha off -colorspace sRGB -grayscale Average \
          +matte -scale 1600% -negate  \
          dpat_symbols.gif -virtual-pixel tile -fx 'u[floor(15.9999*u)+1]' \
          eyes_syms.gif
```

Input images:
- eyes.gif http://www.imagemagick.org/Usage/quantize/eyes.gif
- dpat_symbols.gif http://www.imagemagick.org/Usage/quantize/dpat_symbols.gif

When I run it I get the following error

`error: convert: no such image `u[floor(15.9999*u)+1]' @ error/fx.c/FxGetSymbol/1400.`

It seems like ImageMagick is replacing the first ' with a ` (backtick) and it's trying to treat it as an image. I've tried this with some other commands using fx and I'm getting the same result.

### System Configuration
- Ubuntu 18.10
- ImageMagick 7.0.8-14 (compiled from commit #66c3d77

**Comment by dlemstra** [comment] 2018-10-24 12:10
Duplicate of: https://imagemagick.org/discourse-server/viewtopic.php?f=3&t=34920

**Comment by hellocatfood** [comment] 2018-10-24 12:12
> Duplicate of: https://imagemagick.org/discourse-server/viewtopic.php?f=3&t=34920

Yes it is! I asked about it there and then reported it here.

**Comment by dlemstra** [comment] 2018-10-24 13:10
@hellocatfood Not a problem, just put it there for reference.

**Closed** 2018-11-15 18:32 UTC

**Comment by hellocatfood** [comment] 2018-11-17 15:47
So, I worked out what was the "problem". Since either a later version of Imagemagick 6 and/or Imagemagick 7 the code is more strict. in `'u[floor(15.9999*u)+1]'` the 15.9999 refers to the number of input images to use for the repeating tiles, which in dpat_symbols.gif is 16. If the number of input images is less than this number the script fails.

In previous versions this was allowed but since the later versions of Imagemagick it isn't, which I guess is a good thing.
