### ISSUE TITLE
WEBP define target-size has no effect

### ISSUE THREAD

**Issue by aybli** [ImageMagick/ImageMagick#4931] opened 2022-03-10 20:00 UTC
### ImageMagick version

7.1.0-27

### Operating system

Windows

### Operating system, version and so on

Windows 10 64-bit 21H2

### Description

All of these commands produce the same image:

```
magick image.jpg -define webp:target-size=50000 image1.webp
magick convert image.jpg image2.webp
magick image.jpg -define webp:target-size=100 image3.webp
```

It's the same for "target-psnr=value".

No problem with cwebp.exe -size 50000 image.jpg -o image.webp

### Steps to Reproduce

1. Download [ImageMagick-7.1.0-27-Q16-HDRI-x64-dll.exe](https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-27-Q16-HDRI-x64-dll.exe)
2. Run commands listed above on any image or the one attached below.

### Images

![image](https://user-images.githubusercontent.com/30201386/157744709-49e0c80f-5a0c-4b2f-9b04-2e542923b117.jpg)

**Comment by dlemstra** [comment] 2022-03-10 23:10
Duplicate of #4923.

**Closed by dlemstra** 2022-03-10 23:10 UTC

**Comment by aybli** [comment] 2022-03-10 23:16
> Duplicate of #4923.

Is this problem not reproducible? Since I'm using the latest build I thought this is not an issue specific to my install.

**Comment by dlemstra** [comment] 2022-03-11 04:22
There is no need to create a discussion and an issue.

**Comment by dlemstra** [comment] 2022-06-02 18:52
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
