### ISSUE TITLE
please reopen issue #3165 , NEF color space conversion still corrupted

### ISSUE THREAD

**Issue by Simon566** [ImageMagick/ImageMagick#5857] opened 2022-12-07 09:34 UTC
### ImageMagick version

7.1.0-53

### Operating system

Windows

### Operating system, version and so on

Win 10 latest updates ( think 22H2 )

### Description

converting NEF images still leaves colors heavily corrupted ! i can give example NEFs ( along with the related JPGs that were converted using Nikon Tools ) the image is way too dark also colors drift off

i cant seem to be able to attach a NEF here

### Steps to Reproduce

convert the NEF to avif using image magick, no special options

### Images

![DSC_1245](https://user-images.githubusercontent.com/43811457/206142004-b76f1eaf-d816-4e67-80c4-561cbee3f4bd.jpg)

**Comment by dlemstra** [comment] 2022-12-07 11:58
Closing this as a duplicate of #3165. Please continue the conversation there.

**Closed by dlemstra** 2022-12-07 11:58 UTC

**Comment by ValZapod** [comment] 2022-12-27 08:29
>i cant seem to be able to attach a NEF here

You could zip it and then attach.

**Comment by Simon566** [comment] 2022-12-28 12:24
ok attached it here. what do you mean about the nikon color profile ?
[DSC_1245.zip](https://github.com/ImageMagick/ImageMagick/files/10314189/DSC_1245.zip)

**Comment by ValZapod** [comment] 2022-12-28 12:25
Jpeg file has ICC profile for sRGB.

**Comment by Simon566** [comment] 2022-12-28 12:29
do i need to do something special in order to get image magick to convert the colors correctly ? some more on command line parameters ?
