### ISSUE TITLE
identify -format functions erroring

### ISSUE THREAD

**Issue by jim-VT** [ImageMagick/ImageMagick#7491] opened 2024-07-17 19:27 UTC
### ImageMagick version

7.1.1-35

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22lts

### Description

Hello, with the latest version of identify on Ubuntu22 we are seeing errors when attempting to use the `%[fx:w]`  and `%[fx:h]` format functions against images of multiple types. This error was not present in version 7.1.1-34, and our images are nothing special.

Example:
```
identify -format "%[fx:w]x%[fx:h]" /tmp/image.png 
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
```

The same error persists with .jpg media files as well:
```
identify -format "%[fx:w] by %[fx:h]" /tmp/smiley.jpg 
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
```

### Steps to Reproduce

1. From an Ubuntu 22lts terminal, run  `magick identify -format "%[fx:w] by %[fx:h] inches" smiley.jpg`

### Images

![smiley](https://github.com/user-attachments/assets/d18a6ee0-9509-4c7f-ac68-69f4d8ba9a4f)

**Comment by fmw42** [comment] 2024-07-17 19:35
I get the same error on Mac OSX Ventura with IM 7.1.1.35

```
magick identify -format "%[fx:w] by %[fx:h] inches" smiley.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
 by  inches
```

However, this works fine

```
magick identify -format "%wx%h inches" smiley.jpg
1189x1189 inches
```

**Comment by snibgo** [comment] 2024-07-17 20:40
Using `magick identify`, this works fine with IM v7.1.1-20 and 7.1.1-27.
```
D:\temp>%IM7DEV%magick identify -format "%[fx:w]x%[fx:h]" toes.png
267x233
```
So it seems to be a bug introduced since then.

**Comment by fmw42** [comment] 2024-07-17 20:50
It works fine for me with IM 7.1.1.34 but not 7.1.1.35

**Comment by jim-VT** [comment] 2024-07-18 01:59
> It works fine for me on Mac OSX Ventura with IM 7.1.1.34 but not 7.1.1.35

That is the behavior I see as well on Ubuntu.

**Comment by dlemstra** [comment] 2024-07-18 04:54
This was caused by this commit: https://github.com/ImageMagick/ImageMagick/commit/a262192e38e5f4af52f93accd3dc96e65c0c9300.

**Comment by jim-VT** [comment] 2024-07-18 14:01
This may be obvious to everyone else, but this does appear to be affecting all `[fx:*]` expressions:

```
~$ identify -format "%[fx:360.0*2/n]" /tmp/smiley.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.

~$ identify -format "%[fx:t]" /tmp/smiley.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.

~$ identify -format "%[fx:s]" /tmp/smiley.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.

~$ identify -format "%[fx:mean]" /tmp/smiley.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
```

**Comment by dlemstra** [comment] 2024-07-18 15:40
It's a bug that should be fixed. But keep in mind that this is an open source project that we work on in our spare time. So it can take a while before we have time to fix this.

**Comment by snibgo** [comment] 2024-07-18 15:45
@jim-VT: please test it with a `magic` command:
```
magick /tmp/smiley.jpg -format "%[fx:t]" info:
```

fx requires that the image list contains at least one image. Currently this is checked by an `assert`, as is usual within IM.

**Comment by fmw42** [comment] 2024-07-18 16:04
On IM 7.1.1.35 Mac OSX Ventura, I get

```
magick smiley.jpg -format "%[fx:t]" info: 
0
```

**Comment by jim-VT** [comment] 2024-07-18 16:19
> It's a bug that should be fixed. But keep in mind that this is an open source project that we work on in our spare time. So it can take a while before we have time to fix this.

Of course, and I understand completely. I am happy to hear it being recognized as a bug rather than a deprecated feature, which was a big fear when submitting this issue. Were I anything approaching a C developer I would attempt to contribute the the IM project rather than only bringing issues. 


> @jim-VT: please test it with a `magic` command:
> 
> ```
> magick /tmp/smiley.jpg -format "%[fx:t]" info:
> ```
> 
> fx requires that the image list contains at least one image. Currently this is checked by an `assert`, as is usual within IM.

That does run successfully, and may be enough of a workaround for my needs. Thank you!

**Comment by snibgo** [comment] 2024-07-18 17:50
> That does run successfully, and may be enough of a workaround for my needs.

Ah, good. So that is a workaround. It also seems to confirm my suspicion that fx is being called with no images, or an image with no pixels. But I need to do more testing.

If that is the problem, then fx should give a more informative error. I'll also look into the more fundamental problem about *why* it is called with no images or no pixels.

(Incidentally, some fx expressions like `%[fx:h/2]` logically need an image but don't need pixels. Allowing this in fx would add complications, so the code doesn't allow it.)

**Comment by snibgo** [comment] 2024-07-18 21:00
Another workaround: use `+ping`:
```
magick identify +ping -format %[fx:123] toes.png
```
`+ping` should be the default. It should have no effect, except after a `-ping`.

Tested with 7.1.1-36 (Beta)  from source code downloaded today. imagemagick.org is still down, so I can't download the latest pre-built IM.

**Comment by snibgo** [comment] 2024-07-18 22:49
The fundamental problem seems to be in option.c, in this line:
```
    { "-format", 1L, ImageInfoOptionFlag | NeverInterpretArgsFlag, MagickFalse },
```
So the `-format` option, structure `option_info`, does not contain flags `SimpleOperatorFlag` or `ListOperatorFlag`. Hence the commit cited by dlemstra https://github.com/ImageMagick/ImageMagick/commit/a262192e38e5f4af52f93accd3dc96e65c0c9300 won't set `image_info->ping=MagickFalse` for the `-format` option. So the image won't be read, but only pinged.

I suppose the commit was made for performance, so `identify` and `magick identify` only read pixels when we have an option that needs them. Fair enough. But the `-format` may include an `%[fx:...]`, which might need pixels from an image or more than one image. So I think that `option.c` line should be changed to:
```
    { "-format", 1L, ListOperatorFlag | ImageInfoOptionFlag | NeverInterpretArgsFlag, MagickFalse },
```
With this change, the commands ...
```
magick identify -format %[fx:123] toes.png
magick identify -format %[fx:h] toes.png
magick identify -format %[fx:s] toes.png
```
... execute successfully. A search in the source code for `ListOperatorFlag` suggests it won't create other problems, but I can't guarantee that.

**Comment by snibgo** [comment] 2024-07-19 12:15
The error message that fx raises when it has no pixels is wrong. The following diff corrects this:
```
--- "magickcore\\fx71136b.c"	2024-07-18 20:20:32.317799500 +0100
+++ "magickcore\\fx.c"	2024-07-19 12:20:24.924367900 +0100
@@ -3208,7 +3208,7 @@
   if (p == (const Quantum *) NULL)
     {
       (void) ThrowMagickException (pfx->exception,GetMagickModule(),
-        OptionError,"GetHslInt failure","%lu %li,%li",(unsigned long)
+        OptionError,"Can't get virtual pixels","%lu %li,%li",(unsigned long)
         pfx->ImgNum,(long) imgx,(long) imgy);
       return(MagickFalse);
     }
```

For clarity, here is my proposed diff for option.c:
```
--- "magickcore\\option71136b.c"	2024-07-19 13:13:47.568416800 +0100
+++ "magickcore\\option.c"	2024-07-19 13:12:31.433754900 +0100
@@ -626,7 +626,7 @@
     { "+background", 0L, ImageInfoOptionFlag, MagickFalse },
     { "-background", 1L, ImageInfoOptionFlag, MagickFalse },
     { "+format", 0L, ImageInfoOptionFlag, MagickFalse },
-    { "-format", 1L, ImageInfoOptionFlag | NeverInterpretArgsFlag, MagickFalse },
+    { "-format", 1L, ListOperatorFlag | ImageInfoOptionFlag | NeverInterpretArgsFlag, MagickFalse },
     { "-quiet", 0L, GlobalOptionFlag | FireOptionFlag, MagickFalse },
     { "+quiet", 0L, GlobalOptionFlag | FireOptionFlag, MagickFalse },
     { "-regard-warnings", 0L, ImageInfoOptionFlag, MagickFalse },
```

**Comment by urban-warrior** [comment] 2024-07-20 13:52
@snibgo, we agree that -format is hybrid, both info and list operator.  We applied your recommended patch.  Thanks.

**Closed** 2024-07-20 13:53 UTC

**Comment by snibgo** [comment] 2024-07-21 00:06
Oh dear. My proposed patch to option.c is good for `magick identify` but messes up plain `magick`. Sorry, @urban-warrior .

`magick` without my patch works fine:
```
D:\temp>%IMG7%magick toes.png -format "%[fx:h]" info:
233
```

But `magick` with my patch fails:
```
D:\temp>%IM7DEV%magick toes.png -format "%[fx:h]" info:
magick: unrecognized option `-format' at CLI arg 2 @ error/operation.c/CLIListOperatorImages/4302.
```

**Comment by urban-warrior** [comment] 2024-07-21 00:23
That is what "beta" is for.  Experimentation.  I'll push a different patch in an hour. Test when you have a chance and let us know if it works.  Thanks.

**Comment by snibgo** [comment] 2024-07-26 15:27
> Test when you have a chance and let us know if it works.

Yes, the commit https://github.com/ImageMagick/ImageMagick/commit/7caf7a27ed4ed6436cb96d8efb1bbb9e98306f0a seems to do the trick, but I haven't tested it extensively.
