### ISSUE TITLE
out-of-bounds read in coders/viff.c:445 ReadVIFFImage

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#77] opened 2016-01-13 03:14 UTC
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533452

**Comment by dlemstra** [comment] 2016-01-13 09:49
This issue seems to link to an issue with the viff coder. We can reproduce that issue and we will work on a fix for this.

Did you add the wrong link or did you set the wrong title?

**Comment by moshekaplan** [comment] 2016-01-13 11:32
Likely the wrong title, My bad,

**Comment by urban-warrior** [comment] 2016-01-13 23:38
Grab the latest from GIT and let us know if the problem is resolved.

**Comment by moshekaplan** [comment] 2016-01-14 23:38
Still appears to be present. See poc2: https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533452/+attachment/4550180/+files/id%3A000071%2Csig%3A06%2Csrc%3A002008%2Cop%3Aflip1%2Cpos%3A580

**Comment by dlemstra** [comment] 2016-01-15 00:35
Can you give it another try?

**Comment by urban-warrior** [comment] 2016-01-15 00:54
We cannot reproduce the problem.  We have the address sanitizer enabled and it does not return an exception:

    convert id-000071,sig-06,src-002008,op-flip1,pos-580 null:
    convert: improper image header `id-000071,sig-06,src-002008,op-flip1,pos-580i==' @ error/viff.c/ReadVIFFImage/414.
    convert: no images defined `null:' @ error/convert.c/ConvertImageCommand/3241.

**Comment by moshekaplan** [comment] 2016-01-15 15:01
You're correct. It appears that this bug was fixed.

**Closed** 2016-01-15 15:23 UTC
