### ISSUE TITLE
Using LanczosRadius and other filters to enlarge by odd integer scale causes speckle artifact

### ISSUE THREAD

**Issue by exekutive** [ImageMagick/ImageMagick#7415] opened 2024-06-19 23:48 UTC
### ImageMagick version

7.1.1.15 up to current

### Operating system

Other (enter below)

### Operating system, version and so on

multiple platforms

### Description

Please see discussion topic https://github.com/ImageMagick/ImageMagick/discussions/7404 for complete description, steps and troubleshooting.

![340189406-090670b4-0b74-43a9-bc32-c963bdd16069](https://github.com/ImageMagick/ImageMagick/assets/4755215/afb971d3-fee7-4c5e-aa0f-bc852f2e56e7)

### Steps to Reproduce

`magick header_.png -filter LanczosRadius -distort Resize 500% speckle.png`

### Images

![header_](https://github.com/ImageMagick/ImageMagick/assets/4755215/d87431d4-306c-47aa-a3eb-f7cc4788f453)

**Comment by snibgo** [comment] 2024-06-20 13:35
The problem does not occur in IM v7.1.0-42 or 7.1.0-47 or 7.1.0-49 or 7.1.0-54 or 7.1.0-62, with HDRI, pre-built binary on Windows 11.

It does occur in v7.1.1-15, v7.1.1-20, 7.1.1-28.

This suggests the problem is a code bug introduced after 7.1.0-62 and before 7.1.1-15, and not a problem with the work by @nrobidoux.

Tested with this command:
```
magick c.png -filter LanczosRadius -distort Resize 500% -scale 1000% x.png
```
... where c.png is:
```
magick ^
  -fill Red -background Green ^
  caption:Hello ^
  -trim +repage ^
  +write c.png ^
```
c.png is:

![c](https://github.com/ImageMagick/ImageMagick/assets/33812368/5c7eb00f-f335-4583-a8b3-083a8ed0a469)

In `resize.c`, most of the changes after v7.1.0-52 are changing casts from implicit to explicit. Perhaps one of these is wrong, but I haven't found it yet.

**Comment by fmw42** [comment] 2024-06-20 23:28
I have tracked it down to

```
6.9.12.77 is good
6.9.12.78 is bad (has artifacts)
6.9.12.79 is bad
6.9.12.80 is bad
...
```

**Comment by urban-warrior** [comment] 2024-06-21 00:41
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Closed** 2024-06-23 22:33 UTC

**Comment by exekutive** [comment] 2024-06-28 08:48
Can confirm speckling is fixed. Thank you all.

<img width="820" alt="Screenshot 2024-06-28 at 01 47 29" src="https://github.com/ImageMagick/ImageMagick/assets/4755215/162e292e-aee4-4ab6-85e0-27da34f427a9">
