### ISSUE TITLE
Bug in -precision 5 -define identify:locate=maximum -define identify:limit=1

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7693] opened 2024-10-15 00:33 UTC
### ImageMagick version

7.1.1.39

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

Input:

![tmpS3](https://github.com/user-attachments/assets/a4837a8d-e650-43b9-990a-58b575dbae41)

This works in in IM 6.9.13-17:

identify -precision 5 -define identify:locate=maximum -define identify:limit=1 tmpS3.png
  Channel maximum locations:
  **Gray: 65535 (1) 320,320**  <-----
  Alpha: 0 (0) 0,0

But fails with IM 7.1.1.39:

magick identify -precision 5 -define identify:locate=maximum -define identify:limit=1 tmpS3.png
Channel maximum locations:
  **Gray: 0 (0) 0,0**  <-----
  Alpha: 0 (0) 0,0

P.S.  I get the same results if I remove -precision 5.

### Steps to Reproduce

See above

### Images

See above

**Comment by snibgo** [comment] 2024-10-15 10:44
I confirm the problem. With the supplied image named as `idBug.png`, v7.1.1-20 seems to be correct:
```
C:\web\im>%IMG7%magick identify -precision 5 -define identify:locate=maximum -define identify:limit=1 idBug.png
Channel maximum locations:
  Gray: 65535 (1) 320,320
  Alpha: 65535 (1) 0,0
```

But v7.1.1-38 is wrong:
```
C:\web\im>%IMG71138%magick identify -precision 5 -define identify:locate=maximum -define identify:limit=1 idBug.png
Channel maximum locations:
  Gray: 0 (0) 0,0
  Alpha: 0 (0) 0,0
```

**Comment by urban-warrior** [comment] 2024-10-17 00:05
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Closed by urban-warrior** 2024-10-17 00:05 UTC
