### ISSUE TITLE
"irot" is lost after heic=>heic convert

### ISSUE THREAD

**Issue by japheth-sh** [ImageMagick/ImageMagick#5647] opened 2022-10-11 06:20 UTC
### ImageMagick version

7.1.0-50

### Operating system

Linux

### Operating system, version and so on

amazon linux 2

### Description

"irot" box is lost after convert with heic:preserve-orientation while exif:orientation is kept. Thus the converted heic is displayed side-down.

### Steps to Reproduce

original heic: 
[2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic.zip](https://github.com/ImageMagick/ImageMagick/files/9751632/2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic.zip)

command: 
exiftool -v3 2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic > 2e.txt
convert -define heic:preserve-orientation=true 2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic -quality 40 2e.heic
exiftool -v3 2e.heic > 2e_.txt

result:
[2e.heic.zip](https://github.com/ImageMagick/ImageMagick/files/9751638/2e.heic.zip)
[2e.txt](https://github.com/ImageMagick/ImageMagick/files/9751651/2e.txt)
[2e_.txt](https://github.com/ImageMagick/ImageMagick/files/9751657/2e_.txt)

on Mac:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/43056596/195010936-1fede13c-d3ec-40d4-bee1-662501cd452e.png">
![image](https://user-images.githubusercontent.com/43056596/195011358-85f9f73c-3d8b-4d26-bfe9-c541327b9acd.png)
![image](https://user-images.githubusercontent.com/43056596/195011440-b242885b-3be6-48df-bfff-c8b3d3bed320.png)

**Comment by japheth-sh** [comment] 2022-10-13 12:10
Hi, will this be fixed in next release? Thanks~

**Comment by dlemstra** [comment] 2022-10-13 14:01
We will first need to investigate this before we can do anything. And I have a lot of things on my todo list so I cannot give you that information.

**Comment by jem-sh** [comment] 2022-10-28 06:48
@dlemstra If you get a chance, maybe you can take a look an issue in libheif [#677](https://github.com/strukturag/libheif/issues/677), which is the origin for this issue here. Appreciate your help!

**Comment by japheth-sh** [comment] 2022-12-05 01:52
@dlemstra I see -53 was released, is this fixed or I should still wait? Thanks~

**Comment by dlemstra** [comment] 2022-12-05 09:58
This issue will be updated when we have time to work on this issue.

**Comment by urban-warrior** [comment] 2022-12-11 17:36
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by japheth-sh** [comment] 2022-12-12 02:29
Thank you very much~~

**Comment by japheth-sh** [comment] 2022-12-19 06:59
@urban-warrior I installed the latest -55 version and looks like the issue is not solved yet.
![image](https://user-images.githubusercontent.com/43056596/208366200-294b179a-8a98-4304-8bae-8bd8b84674e1.png)
<img width="447" alt="image" src="https://user-images.githubusercontent.com/43056596/208366268-13cb38c2-cfb9-4820-9577-8de6c7e072a6.png">

**Comment by dlemstra** [comment] 2023-01-14 10:11
In the next release you should see the `irot` in the output image when you have libheif `.1.14.0` or higher.

**Comment by japheth-sh** [comment] 2023-01-16 04:11
Thank you @dlemstra , will have a try asap.

**Comment by japheth-sh** [comment] 2023-02-02 04:36
Sorry for late. I tried the same command "convert -define heic:preserve-orientation=true /work/2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic -quality 40 /work/2e.heic" for 7.1.0-57~7.1.0-60. Here is the result:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/43056596/216231319-50656e84-a293-4b66-9fce-cd11487dfe2d.png">
Looks like the results have wrong orientations. However I see the irot box now:
![image](https://user-images.githubusercontent.com/43056596/216231826-d728b6e6-6646-4911-8fef-f87a9fb8ff2c.png)
v58~v60 are same, attach one of them:
[2e_v60.heic.zip](https://github.com/ImageMagick/ImageMagick/files/10564727/2e_v60.heic.zip)
@dlemstra

**Comment by dlemstra** [comment] 2023-02-02 10:07
Are you sure this is not an issue with the software that you are using to view the image?

**Comment by japheth-sh** [comment] 2023-02-02 11:08
Maybe. I am using MacOS Preview. I will try other system/software tomorrow.
At least this one(https://strukturag.github.io/libheif/) is good:
![image](https://user-images.githubusercontent.com/43056596/216308477-af510e63-619a-4854-bf8c-ef6c20e1f67b.png)

**Comment by japheth-sh** [comment] 2023-02-03 06:41
@dlemstra Confirmed this is caused by incorrect 'ispe' box.
![image](https://user-images.githubusercontent.com/43056596/216529689-defd7ace-49d3-4448-a869-2edeb253aa58.png)
Looks like the width/height should be swapped after 'irot' set to 3 (or 1, I think).
I manually swapped them:
![image](https://user-images.githubusercontent.com/43056596/216529955-5b9c4d3f-a186-4605-bce3-3c810d4d0b44.png)
And then it looks good now:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/43056596/216530200-c07a800b-7ad4-4b24-b3c7-cd98847acff7.png">

**Comment by dlemstra** [comment] 2023-02-03 13:48
Are you sure that's not a bug in the viewer? The libheif library that we are using stores the rotated width/height and your viewer expects the unrotated width/height. If you can find some documentation somewhere that this is incorrect this should be reported to the libheif library.

**Comment by japheth-sh** [comment] 2023-02-21 00:21
@dlemstra Sorry for late, I was busy these days but I did some investigate on "ispe" yesterday:

**Comment by japheth-sh** [comment] 2023-02-21 00:40
@dlemstra Sorry for late, I was busy these days but I did some investigate on "ispe" yesterday:
[2e.txt](https://github.com/ImageMagick/ImageMagick/files/10788509/2e.txt) is the exiftool output for the original 2e.heic. You can see its "ispe" box and related rotate properties:
![image](https://user-images.githubusercontent.com/43056596/220217068-88b55b6d-da8f-4e30-b579-ea95c9b81a41.png)
![image](https://user-images.githubusercontent.com/43056596/220217097-c67cc3d6-37cc-48fa-8220-2817efd5e4e3.png)
But for the converted heic(convert -define heic:preserve-orientation=true 2e.heic -quality 40 2e-62.heic):
The output [2e-62.txt](https://github.com/ImageMagick/ImageMagick/files/10788532/2e-62.txt) says:
![image](https://user-images.githubusercontent.com/43056596/220217287-64ddc61a-dda5-491c-8229-ed91ae09cf21.png)
![image](https://user-images.githubusercontent.com/43056596/220217329-e8ebee5d-5d60-4cfe-9d33-b3c4e1b0facd.png)
And their "raw" image (without any metadata):
convert -define heic:preserve-orientation=true 2e.heic -strip raw.jpg 
![raw](https://user-images.githubusercontent.com/43056596/220217884-642f4a37-0908-47b2-8cd4-c4770985d3e4.jpg)
convert -define heic:preserve-orientation=true 2e-62.heic -strip raw-62.jpg
![raw-62](https://user-images.githubusercontent.com/43056596/220217925-a11ca950-4b63-4f9b-bcd9-30b935fb96ab.jpg)

As you can see, the Exif:Orientation and "irot" are not changed as well as the "raw" image, but the "ispe" width and height are swapped in the converted heic. Based on the original heic (its "raw" image is landscape and "ispe" is 4032x3024), I guess the "ispe" should contain the width/height before rotate. From another aspect, what I did (convert -define heic:preserve-orientation=true 2e.heic -quality 40 2e-62.heic) should only change the compression quality and touch nothing else, so looks like "ispe" should be also kept same. Could you kindly confirm this is libheif's issue?

**Comment by dlemstra** [comment] 2023-02-21 07:49
As I said before please find some documentation that proves your point so you can report this upstream.

**Comment by japheth-sh** [comment] 2023-05-03 01:06
@dlemstra I see libheif had fixed "ispe" bug in v1.16 so tried this again. The result is not correct but a valid heif. Could you help to check whether IM need upgrade to fix?

original heif:
irot: 3
exif orientation: 6
ispe: 4032x3024

result with IM7.1.0-62 + libheif v15:
irot: 3
exif orientation: 6
ispe: 3024x4032

result with IM7.1.0-62 + libheif v16:
irot: not present
exif orientation: 6
ispe: 4032x3024

convert -define heic:preserve-orientation=true /work/2e3dd605-c68b-48a5-bff1-c205c6b3a3c1.heic -quality 40 /work/2e_IM62_libheif16.heic
[2e_IM62_libheif16.txt](https://github.com/ImageMagick/ImageMagick/files/11378718/2e_IM62_libheif16.txt)
[2e_IM62_libheif16.heic.zip](https://github.com/ImageMagick/ImageMagick/files/11378720/2e_IM62_libheif16.heic.zip)

**Comment by dlemstra** [comment] 2023-07-02 18:56
Can you still reproduce this or can we close this issue?

**Comment by japheth-sh** [comment] 2023-07-03 01:52
@dlemstra sorry, no time to check whether the latest version has solved this. I guess not and need to check source code to investigate why it happens. Please keep this issue open and I will check ASAP.

**Closed** 2024-08-17 10:51 UTC
