### ISSUE TITLE
32 bit per channel PSD files

### ISSUE THREAD

**Issue by schille1992** [ImageMagick/ImageMagick#455] opened 2017-04-27 14:08 UTC
Is it possible for you to support the decoding of 32 bit per channel PSD files. 
My attachment file is commonly generated with Photoshop. 

The following error is thrown in "psd.c":
`if ((psd_info.depth != 1) && (psd_info.depth != 8 ) && (psd_info.depth != 16))
ThrowReaderException(CorruptImageError,"ImproperImageHeader");`

[32BitPSD.zip](https://github.com/ImageMagick/ImageMagick/files/961821/32BitPSD.zip)

**Comment by bermannoah** [comment] 2017-05-29 13:28
Hey there, just wanted to add a confirmation of the issue. Let me know if there's any info I can provide, but it's exactly the same error on my end as on the above user's. :)

**Comment by dlemstra** [comment] 2017-05-29 13:54
This is the expected behavior. We currently don't support 32 bit per channel PSD files. That is why I added those labels in April.

**Comment by bermannoah** [comment] 2017-05-29 14:03
@dlemstra understood! Thank you.

**Comment by dlemstra** [comment] 2017-11-23 20:50
@bermannoah Do you also have a file we can use to test this when we try to implement this?

**Comment by bermannoah** [comment] 2017-11-24 10:38
@dlemstra Yes! Here's a sample file that produces the same issue. https://we.tl/6Dlx7ZePYD
For what it's worth I'm running `Version: ImageMagick 6.9.8-10 Q16 x86_64 2017-06-16`. Thanks much!

**Comment by dlemstra** [comment] 2017-11-24 11:38
Thanks for the file 👍 I just ran in through a local build of ImageMagick where I applied some patches to read 32 bit channel files and I can see the bridge 😄 ! This feature will only become available in ImageMagick 7 after I do some more testing. And that means you will need to switch to ImageMagick 7 if you want to read 32 bit channel PSD files.

**Comment by dlemstra** [comment] 2017-11-25 08:50
@schille1992 and @bermannoah: I am getting some odd output on the layers of @schille1992 their test image. But I think this could be due to layer stuff that ImageMagick cannot handle. Would it be possible to share another test image with RLE compressed layers and another one with ZIP compressed layers?

**Comment by dlemstra** [comment] 2017-11-25 10:29
I think I found the issue. I need to figure out what to do with a packet size of 4 in this situation: https://github.com/ImageMagick/ImageMagick/blob/fb2f26c4b674f8b3a1c5b1dc4f7aedd00b0794fb/coders/psd.c#L1288-L1292

Would love to get some help with some documentation that explains what I need to do in that situation.

**Comment by dlemstra** [comment] 2017-12-03 17:29
I just pushed some changes that will add support for 32 bits per channel for the "merged image" and the layers that are NOT `ZipWithPrediction`. Support for layers that have `ZipWithPrediction` will be added in the future and I will keep this issue open for that.

**Comment by z2z** [comment] 2018-08-24 11:29
@dlemstra Is 32 bit per channel PSD supported now?

**Comment by dlemstra** [comment] 2018-08-24 12:28
@z2z: It is only supported for layers that are NOT `ZipWithPrediction`.

**Comment by z2z** [comment] 2018-08-28 12:36
Adding for just reference, link of other implementation.

https://github.com/PsdPlugin/PsdPlugin/search?q=prediction&unscoped_q=prediction

**Comment by WearyWanderer** [comment] 2019-07-30 15:49
@dlemstra I've recently built Magick++ (Q32, HDRI enabled) and taking a look in the write functionality for PSD files. I couldn't see support for writing 32 bit PSDs, but just found this issue from a quick search. Is writing only 8/16 bit currently?

**Comment by dlemstra** [comment] 2020-06-21 08:47
Going to close this issue now. Starting with ImageMagick 7.0.10-21 there will be support for reading 32 ZipWithPrediction.

And to finally answer @WearyWanderer their question. We won't be adding support for writing 32 bit PSD files any time soon. If you would still like support for this then please open up a new issue.

**Closed by dlemstra** 2020-06-21 08:47 UTC
Labels: enhancement, up for grabs
