### ISSUE TITLE
assertion failure in ReplaceImageInList

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#805] opened 2017-09-30 07:16 UTC
Here is the critical code : (in CLIListOperatorImages)
```
        swap=CloneImage(p,0,0,MagickTrue,_exception);                                //4580
        ReplaceImageInList(&p,CloneImage(q,0,0,MagickTrue,_exception));    
        ReplaceImageInList(&q,swap);                                                            //4582
```
CloneImage may return NULL to the "swap",and it was passed to ReplaceImageInList:
```
MagickExport void ReplaceImageInList(Image **images,Image *replace)        //1144
{
  assert(images != (Image **) NULL);
  assert(replace != (Image *) NULL);        //1147
```
If the "replace" is NULL,it will may cause assertion failure.

**Comment by mikayla-grace** [comment] 2017-09-30 14:25
Duplicate of #804.

**Closed** 2017-10-01 06:45 UTC
Labels: duplicate
