### ISSUE TITLE
[bug] -option does not work as help reads but in between the image.in and image.out 

### ISSUE THREAD

**Issue by freedom-foundation** [ImageMagick/ImageMagick#7800] opened 2024-11-22 03:28 UTC
### ImageMagick version

7.1.1-39

### Operating system

Linux

### Operating system, version and so on

Linux

### Description

You mayaswell send this straight to [Bug Report](https://github.com/ImageMagick/ImageMagick/issues/new?assignees=&labels=&projects=&template=bug-report.yml) 

     -option does not work as help reads but in between the image.in and image.out

_Originally posted by @freedom-foundation in https://github.com/ImageMagick/ImageMagick/discussions/7798#discussioncomment-11343668_

### Steps to Reproduce

try magick -monochrome image.in image.out NOT WORKING 
magick image.in -monochrome image.out WORKS

### Images

N/A

**Comment by fmw42** [comment] 2024-11-22 03:43
Your syntax is wrong. Read the input before -monochrome.  See https://usage.imagemagick.org/basics/#why

Imagemagick 6 was forgiving, but Imagemagick 7 is not.

**Comment by freedom-foundation** [comment] 2024-11-22 04:16
No. @fmw42 I already posted the --help from the bin. I was right. See
```$ magick --help
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}
> Your syntax is wrong. Read the input before -monochrome.

**Comment by freedom-foundation** [comment] 2024-11-22 05:30
> See https://usage.imagemagick.org/basics/#why

maybe version 7 is better but [ImageMagick](https://github.com/ImageMagick) need's to update the --help file

**Comment by dlemstra** [comment] 2024-11-22 08:00
Closing this issue because it's not a bug. With ImageMagick 7 the syntax has changed and is now less forgiving.

**Closed by dlemstra** 2024-11-22 08:00 UTC

**Comment by freedom-foundation** [comment] 2024-11-22 08:10
No you are baiting people onto github or website by leaving wrong help documentation built into the bin. I have already provided the illustration. This is already CONFIRMED bug. @dlemstra 

> Closing this issue because it's not a bug. With ImageMagick 7 the syntax has changed and is now less forgiving.

**Comment by dlemstra** [comment] 2024-11-22 08:13
We are the maintainers of this project this and we don't consider this a bug. You are of course more then welcome to improve our documentation if you think we should make this more clear.

**Comment by freedom-foundation** [comment] 2024-11-22 08:19
Or download untampered version before you picked it up on GitHub. 

> We are the maintainers of this project this and we don't consider this a bug. You are of course more then welcome to improve our documentation if you think we should make this more clear.
