### ISSUE TITLE
Impossible to build utilities with statically linked jxl

### ISSUE THREAD

**Issue by trzecieu** [ImageMagick/ImageMagick#4149] opened 2021-09-02 20:34 UTC
### ImageMagick version

7.1.0-5

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

JXL does support building static libraries with following config: 
```bash
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_STATIC=YES ..
```
When placed under jxl folder and image magic is configured with following: 
```bash
./configure \
	--disable-shared --enable-delegate-build \
	--enable-static  \
	--with-jxl=yes
```
It disables the jxl module as defined in the configure (line ~30710):
```bash
if test "$with_jxl" != 'yes'; then
    DISTCHECK_CONFIG_FLAGS="${DISTCHECK_CONFIG_FLAGS} --with-jxl=$with_jxl "
fi
if test "$enable_static" = 'yes'; then
    if test "$with_utilities" = 'yes'; then
        with_jxl='no'
    fi
fi
```

I tried to force configurator to include jxl, but still it links it dynamically.
I think I've bounced from config section commented with `# This check should be changed once we have a .pc file for the JPEG-XL library.` 

With the current config - is it possible to include jxl statically to the ImageMagick build? 

Thanks,
P

### Steps to Reproduce

* 
```bash
git clone --recursive https://github.com/libjxl/libjxl.git -b v0.5 jxl
cd jxl
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_STATIC=YES ..
cmake --build . -- -j$(nproc)
sudo cmake --install .
```

Then try to build image magic with:
```bash 
# simplified command
./configure \
	--disable-shared --enable-delegate-build \
	--enable-static  \
	--with-jxl=yes

make -j$(nproc)
```

**Comment by dlemstra** [comment] 2021-09-02 21:35
Duplicate of  #4029 so I will close this. And the TLDR is that you cannot do that right now.

**Closed by dlemstra** 2021-09-02 21:35 UTC
