### ISSUE TITLE
Unable to convert specific HECI file to both PDF and TIFF.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#7789] opened 2024-11-19 03:59 UTC
### ImageMagick version

 7.1.1-40

### Operating system

Windows

### Operating system, version and so on

Windows 10 and Windows 11.

### Description

Hi, 

We are unable to convert this attached HEIC file to both PDF and TIFF files. Could you please check this? We tried with ImageMagick version  7.1.1-40.

--
Thanks
Prasanth

### Steps to Reproduce

I used the below command to convert the attached HEIC file to  PDF and TIFF: 
magick.exe IMG_3952.HEIC IMG_3952.PDF
magick.exe IMG_3952.HEIC IMG_3952.TIFF

### Images

[IMG_3952.zip](https://github.com/user-attachments/files/17809142/IMG_3952.zip)
![MyOutput](https://github.com/user-attachments/assets/b899e99a-c3ac-4c7e-ba24-77874e3ca30c)

**Comment by dlemstra** [comment] 2024-11-19 06:08
Duplicate of #7778

**Closed by dlemstra** 2024-11-19 06:08 UTC
