### ISSUE TITLE
Data loss observed with ImageMagick v7.1.0-5 while converting a specific JPG file to a 200 DPI B/W output TIFF file using ImageMagick library APIs.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#4121] opened 2021-08-26 15:23 UTC
### ImageMagick version

7.1.0-5

### Operating system

Windows

### Operating system, version and so on

Any version of Windows OS.

### Description

Hi,

I have downloaded the latest version of ImageMagick (7.1.0-5), tested the previously reported issue in bug (https://github.com/ImageMagick/ImageMagick/issues/4059) and this issue is fixed.

We noticed another issue with this 7.1.0-5 version of ImageMagick with Q8 flavor. We tried to convert the attached input.jpg file (input.zip) to a 200x200 black and white tiff and observed that the output is blurred. But, when we tried this conversion using the previous version of ImageMagick (7.1.0-4), output was clear. We have also attached both the outputs here with for your reference (output_v7.1.0-4.zip and output_v7.1.0-5.zip). We are using ImageMagick library APIs for this conversion.

When we tried the same above conversion (input.jpg) with Q16 flavor, the output is a blank white TIFF file.

Could you please help us with this or let us know if we are missing anything here?

--
Thanks
Prasanth

### Steps to Reproduce

[ImageMagick_Sample.zip](https://github.com/ImageMagick/ImageMagick/files/7060797/ImageMagick_Sample.zip)

### Images

[input.zip](https://github.com/ImageMagick/ImageMagick/files/7060801/input.zip)
[output_v7.1.0-4.zip](https://github.com/ImageMagick/ImageMagick/files/7060807/output_v7.1.0-4.zip)
[output_v7.1.0-5.zip](https://github.com/ImageMagick/ImageMagick/files/7060808/output_v7.1.0-5.zip)

**Comment by urban-warrior** [comment] 2021-08-28 14:54
The previous color reduction algorithm uses a tree-merge algorithm which sometimes would end up with 1 merged color rather than 2.  We added the BiLevel() method call to ensure each image would end up with exactly 2 colors, except, when the original image only had one color or the colors parameter is 1.  A better solution may be to restore the previous behavior and try to perhaps enhance the color reduction algorithm to ensure we always get at least 2 colors when merging when the colors parameter is 2.

**Comment by fmw42** [comment] 2021-08-28 14:57
Perhaps a -define to allow the user to pick one of the two methods?

**Comment by urban-warrior** [comment] 2021-08-28 15:01
As you know,  few image processing algorithms return satisfactory results for all use cases.  Our goal is to capture the majority of the use cases and for the one-offs, have the user choose their own methods from the plethora of options available.

**Comment by fmw42** [comment] 2021-08-28 15:04
What about making the tree-merge method as a stand-alone threshold method. That way the use can pre-process the image with any way they want before output to compressed TIFF?

**Comment by urban-warrior** [comment] 2021-08-28 15:07
The tree-merge method is already captured in our color reduction algorithm @ https://imagemagick.org/script/quantize.php.

**Comment by fmw42** [comment] 2021-08-28 15:16
@urban-warrior  This does not reproduce his result.

`magick input.jpg -colorspace gray -colors 2 -compress group4 x.tif`

[x.tif.zip](https://github.com/ImageMagick/ImageMagick/files/7070898/x.tif.zip)

His previous result

[output_v7.1.0-4.tif.zip](https://github.com/ImageMagick/ImageMagick/files/7070900/output_v7.1.0-4.tif.zip)

His result is much smoother in apparent "gray".  So how can he reproduce that?  That is why I was suggesting a standalone method that does exactly that.  Perhaps you know how to modify my command above to get his result. If so, that would solve the issue.

**Comment by urban-warrior** [comment] 2021-08-28 15:26
Did you try @snibgo suggestion above?

**Comment by snibgo** [comment] 2021-08-28 15:29
An important point about "-colors 2" is that for a typical grayscale image it does _not_ transform to black and white. It transforms to a dark gray and a white gray. Any input areas with colours that were darker than that dark gray will become a solid black, and areas that were lighter than that light gray will become white. The only areas that show dithering will be those that were between the dark and light grays.

This may be reasonable for some uses and not for others, of course.

Personally, I don't care what "-type bilevel" does when saving TIFF files, because I prefer a lower-level control, eg "-threshold" or "-colors" or "-remap", with or without dithering, at my choice.

**Comment by snibgo** [comment] 2021-08-28 15:50
> We added the BiLevel() method call to ensure each image would end up with exactly 2 colors...

But v7.1.0-5 thresholds at QuantumLevel/2. If all the intensities are below this level the result is all black; if they are all above then the result is all white.

Instead we could threshold at the mid-point between the lightest and darkest. Or at the 50% point of a cumulative histogram, so half the pixels become white and the other half become black.

There are many possibilities. I'm not really in favour of a "-define". If the user cares about how an image is transformed to black and white, they should use explicit operations for that task.

**Comment by fmw42** [comment] 2021-08-28 15:51
The point was to reproduce the same method used in the older version of ImageMagick, not a close approximation.

**Comment by urban-warrior** [comment] 2021-08-28 15:53
The previous method had a flaw which we are currently investigating.  Certain images were reduced to 1 rather than 2 colors.

**Comment by snibgo** [comment] 2021-08-28 17:16
A useful operation would be "-colorsexact N" that reduced to exactly N colours, provided the input has at least N unique colours.

That would solve the problem with the 7.1.0-4 code, as well as providing a facility that users sometimes ask for.

I don't know if the current colour reduction code can be adapted for this, or if a new algorithm is needed.

**Comment by pprasanthk** [comment] 2021-08-30 10:18
@snibgo 
This 7.1.0-4 behavior/output is there with older versions of ImageMagick as well. Below is the command line that we tried: 
    convert.exe input.jpg -quality 50 -type bilevel -density 300 output.tiff
This is showing a different output when we compare with the older versions of ImageMagick.

It would be great to have the old 7.1.0-4 behavior with the latest 7.1.0-5 aw well. 

It would be great if we can have the required command line option or Magick API with ImageMagick v7.1.0-5, which would bring back the same output which we used to get with ImageMagick v7.1.0-4.

Could you please help us with this?

--
Thanks
Prasanth

**Comment by urban-warrior** [comment] 2021-08-30 23:50
We have a patch in ImageMagick 7.1.0-6 Beta (clone the Github master branch).  Give it a try and see if you get expected results.

**Comment by fmw42** [comment] 2021-08-31 00:25
The output on the 7.1.0.6 beta does not seem much different from the 7.1.0.5 release and is much "grainier" than the 7.1.0.4 version using the command:

`magick input.jpg -colorspace gray -colors 2 -compress group4 x.tif`

Is there a better command?

**Comment by urban-warrior** [comment] 2021-08-31 01:00
We compared the two releases-- and found them comparable :-).  7.1.0-6 gave a better rendition of the horses nose and legs as compared to 7.1.0-4.  We used  ImageMagick_Sample.cpp to produce the output image, not the ImageMagick command-line.   We still need to ensure that color reduction does not return just one color.

**Comment by fmw42** [comment] 2021-08-31 01:18
Perhaps the 7.1.0.6 beta that I downloaded does not have your change. I compare from my command above and what the OP provided from his download. However, I cannot reproduce his 7.1.0.4 result. I get a different result.

```
magick compare -metric rmse output_v7.1.0.-6.tif output_v7.1.0-4.tif null:
18126.1 (0.276587)
```

**Comment by pprasanthk** [comment] 2021-09-20 08:13
Hi, 

We downloaded the latest version of ImageMagick and noticed that dithering is still not properly applied for the following files as it used to get applied in v7.1.0-4. Could you please help us with this?

![ZeroDensity_Input](https://user-images.githubusercontent.com/79841943/133973087-3a911b9b-c5fb-4739-b555-9e8600dcb4c8.png)
![ColorEbenfurt](https://user-images.githubusercontent.com/79841943/133973101-1f5f6a21-425b-4bdf-acf1-0b3402dd732c.jpg)

--
Thanks
Prasanth

**Comment by urban-warrior** [comment] 2021-09-20 11:57
Try adding `-dither FloydSteinberg` to your command-line.   Does that help?  If not, post your command here with an example of expected results so we can investigate.

**Comment by pprasanthk** [comment] 2021-09-20 13:07
Hi urban-warrior, 

It looks like a different dithering algorithm is being used with 7.1.0-7, but it looks more like the output with 7.0.10-0.

Could you please clarify us the below questions: 
•	Which dithering algorithm is by used default?
•	What was changed between IM 7.0.10-0 and 7.1.0-7?

I have attached the outputs with both 7.0.10-0 and 7.1.0-7 (with the new command line **-dither FloydSteinberg** ) for your reference.

[outputs.zip](https://github.com/ImageMagick/ImageMagick/files/7195895/outputs.zip)

--
Thanks
Prasanth

**Comment by urban-warrior** [comment] 2021-09-20 15:48
Post a link to your original source image.  We will need to run some tests to see why the output results differ.   Its possible its a side-effect of a bug fix.  We'll need to perform forensic first to decide.

**Comment by pprasanthk** [comment] 2021-09-20 16:10
Please find the original source image below: 
[TestImage.zip](https://github.com/ImageMagick/ImageMagick/files/7197098/TestImage.zip)

**Comment by urban-warrior** [comment] 2021-09-20 23:16
Try this command:
```
magick TestImage.tiff -resize 2481x3508 -dither FloydSteinberg -compress group4 fax.tiff
```
It returns similar results to ImageMagick version 7.0.10-0 .

**Comment by pprasanthk** [comment] 2021-09-20 23:24
Hi urban-warrior, 

I will try this but I am more curious to know, 
• Which dithering algorithm is by used default?
• What was changed between IM 7.0.10-0 and 7.1.0-7?

**Comment by urban-warrior** [comment] 2021-09-21 01:34
The default dithering algorithm is Riemersma.  What changed?  The default dithering algorithm.    Explicitly set it to FloydSteinberg to restore previous behavior.

**Comment by pprasanthk** [comment] 2021-09-21 01:51
Hi urban-warrior, 

Thanks for the confirmation that the default dithering algorithm was changed from Riemersma to FloydSteinberg. I tried your last command and noticed that the command line **-resize 2481x3508** is mandatory to get the behavior similar to v7.0.10-0. 
Could you please clarify about the introduction of this new extra parameter **-resize 2481x3508,** which I believe is not there in v7.0.10-0.

--
Thanks
Prasanth

**Closed** 2022-04-30 12:59 UTC
