### ISSUE TITLE
Add AVIF (AV1 Image File Format) support

### ISSUE THREAD

**Issue by EwoutH** [ImageMagick/ImageMagick#1432] opened 2018-12-28 19:26 UTC
AVIF (AV1 Image File Format) is a new image format based on the AV1 video codec. It supports both lossless and lossy compression and [saves](https://calendar.perfplanet.com/2018/is-avif-the-future-of-images-on-the-web/) up to 50% space at the same quality compared to JPG.

Here is the [AVIF specification](https://aomediacodec.github.io/av1-avif/) and some .avif samples from [Netflix](http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/) and [Microsoft](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Microsoft). AVIF files can currently be viewed with [VLC](https://nightlies.videolan.org/) and are going to be supported soon in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863) and [Windows 10](https://github.com/AOMediaCodec/av1-avif/wiki).

**Comment by EwoutH** [comment] 2019-04-14 15:04
[libavif](https://github.com/joedrago/avif) tagged it's first release, [0.1.0](https://github.com/joedrago/avif/releases/tag/v0.1.0).

**Comment by EwoutH** [comment] 2019-05-09 13:23
[libavif](https://github.com/joedrago/avif) tagged a new release, [0.1.3](https://github.com/joedrago/avif/releases/tag/v0.1.3). See [Colorist](https://github.com/joedrago/colorist) for an example [implementation](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by novomesk** [comment] 2020-04-30 13:31
From http://www.imagemagick.org/discourse-server/viewtopic.php?p=172532&sid=29c77b7c1d3fe14155ad1a3d255707b6#p172532 comment, ImageMagick devs would prefer using libheif for AVIF support. Unfortunately the AVIF support stays in experimental branch only and the progress stopped.
I asked [What is the future of AVIF support in libheif?](https://github.com/strukturag/libheif/issues/217) but so far there is no reply.

In order to make libheif to read/write AVIF, there is still need of another dependency: [libaom](https://aomedia.googlesource.com/aom/) - to encode/decode AV1 streams.

I use [libavif](https://github.com/AOMediaCodec/libavif) in my programs. libavif is not very prevalent in Linux distributions yet (so far in Arch, Gentoo, openSUSE according https://repology.org/project/libavif/versions ). As a libavif user I can say that libavif is improving rapidly. Sometimes too rapidly, there were two breaking changes this year already because changes from VIP users (like Google) were incorporated.

My private recommendation is to use libavif and build it locally (it's very easy, I did it many times).

To write AVIF MagickCoder in https://github.com/ImageMagick/ImageMagick/tree/master/coders does not look very difficult.

What do you think?
If I contribute the AVIF coder, would you use it with locally built libavif or you wish to avoid to keep local dependencies at all?

**Comment by dwbuiten** [comment] 2020-05-06 17:00
Why is libheif prefered when it lacks so many (IMO important) features like ICC profiles (or even configOBUs), and requires manually adding an AV1 encoder as a dep (libavif has several backends)?

**Comment by 06needhamt** [comment] 2020-05-07 19:23
Looks like libheif now has AVIF support in the master branch now.

From libheif readme
> The decoder automatically supports both HEIF and AVIF through the same API. No changes are required to existing code to support AVIF. The encoder can be switched between HEIF and AVIF simply by setting `heif_compression_HEVC` or `heif_compression_AV1` to `heif_context_get_encoder_for_format()`.


But I agree that using libavif would be better since it is the official reference library for the AVIF format.

**Comment by dooman87** [comment] 2020-08-08 11:22
I've built imagemagick with with the latest libheif and I can see that AVIF supported:

```
root@2b5192860db2:/imgs# identify -list format |  grep AVIF
     AVIF* rw+   AV1 Image File Format (1.7.0)
```

But I can't figure out how to set the output:

```
root@2b5192860db2:/imgs# convert -verbose test.jpg  test.avif
test.jpg JPEG 1280x853 1280x853+0+0 8-bit sRGB 97602B 0.010u 0:00.011
test.jpg=>test.avif JPEG 1280x853 1280x853+0+0 8-bit sRGB 95101B 0.020u 0:00.023
root@2b5192860db2:/imgs#  
```

It's always generates JPEG...

**Comment by dooman87** [comment] 2020-08-08 12:48
Sorry, looks like I was on the version `7.0.10-23`. I upgraded to `7.0.10-25` and now it generates empty avif file:

```
root@5c3d6d68d956:/imgs# convert -verbose test.jpg test.avif
test.jpg JPEG 1280x853 1280x853+0+0 8-bit sRGB 97602B 0.010u 0:00.011
test.jpg=>test.avif JPEG 1280x853 1280x853+0+0 8-bit YCbCr 0.040u 0:00.014
convert: Success `test.avif' @ error/heic.c/IsHeifSuccess/136.
root@5c3d6d68d956:/imgs# ls -la test.avif 
-rw-r--r-- 1 root root 0 Aug  8 12:47 test.avif
root@5c3d6d68d956:/imgs# 
```

**Comment by dooman87** [comment] 2020-08-08 13:23
And here I am again, sorry for the spam. The problem is libheif using libaom v2, but it's version 1 in Debian 10, so need to build it by myself or find backports.

**Comment by dooman87** [comment] 2020-08-09 10:50
@dlemstra I can confirm that with the version 7.0.10-25 and `libheif` 1.7.0 I managed to convert jpegs/pngs into avif. So, perhaps we can close this one?

**Closed** 2020-08-09 13:00 UTC
Labels: enhancement, up for grabs

**Comment by evgenux** [comment] 2020-08-10 17:23
@dlemstra, on archlinux `imagemagick (7.0.10.25-1)` with `libheif (1.7.0-2)` still generates empty avif file:
```
`--> convert -verbose in.jpg out.avif
in.jpg JPEG 5472x3648 5472x3648+0+0 8-bit sRGB 6561850B 0.810u 0:00.812
in.jpg=>out.avif JPEG 5472x3648 5472x3648+0+0 8-bit YCbCr 1.580u 0:00.856
convert: Success `out.avif' @ error/heic.c/IsHeifSuccess/136.
.-(/tmp)-------------------------------------------------------------------------------------------------------------------------------(evgeny@hasub)-
`--> ls -la in.jpg out.avif
-rw-r--r-- 1 evgenux evgenux 6561850 авг 10 09:58 in.jpg
-rw-r--r-- 1 evgenux evgenux       0 авг 10 10:00 out.avif
```
I've tried it with different formats of input files.

**Comment by dooman87** [comment] 2020-08-11 12:36
@evgenux Could you try to run `heif-enc` from libheif to confirm that it's working?

```
./heif-enc example-1.jpeg -A -o example.avif
```

I had exactly the same error and it turned out `libheif` was configured without `libaom` support. 

There is also a docker image that I maintain ant it now supports AVIF: https://github.com/dooman87/imagemagick-docker. You could look up build steps in `Dockerfile.buster`.

**Comment by evgenux** [comment] 2020-08-11 20:29
@dooman87 
> Could you try to run heif-enc from libheif to confirm that it's working?

Yes, I could. It returns `No HEVC encoder available.` So, the problem in `libheif`.

**Comment by evgenux** [comment] 2020-08-12 10:13
After rebuilding `libheif` with `aom` support on archlinux, IM has managed to convert images into avif.

Thank you for helping to figure out the source of issue!

**Comment by phaistonian** [comment] 2020-10-12 13:23
[ImageMagick does support .avif](https://github.com/ImageMagick/ImageMagick/issues/1432) it seems.

Can we also support it?

**Comment by dlemstra** [comment] 2020-10-12 13:43
@phaistonian This is ImageMagick? Looks like you posted the message in the wrong space.

**Comment by phaistonian** [comment] 2020-10-12 13:44
> @phaistonian This is ImageMagick? Looks like you posted the message in the wrong space.

Sorry.  My bad.

**Comment by shmerl** [comment] 2020-12-20 08:03
I don't get an error but doing the conversion I get the same format in result on Debian testing. What is missing?

```
convert -verbose test.jpg test.avif
test.jpg JPEG 374x423 374x423+0+0 8-bit sRGB 67756B 0.010u 0:00.006
test.jpg=>test.avif JPEG 374x423 374x423+0+0 8-bit sRGB 68217B 0.000u 0:00.006
```

* imagemagick 8:6.9.11.24+dfsg-1+b2
* libaom0 1.0.0.errata1-3
* libheif1 1.9.1-1

**Comment by dooman87** [comment] 2020-12-24 01:04
> * imagemagick 8:6.9.11.24+dfsg-1+b2

You need at least IM v. 7.0.25 to get AVIF working. You can build it manually following steps from this [Dockerfile](https://github.com/dooman87/imagemagick-docker/blob/master/Dockerfile.buster)

**Comment by shmerl** [comment] 2020-12-24 01:06
Oh, I see. Looks like it's seriously out of date even in Debian testing.

**Comment by rubyFeedback** [comment] 2021-02-23 15:08
Creating .avif works, but on my first try using it, the resulting image was larger than
the .jpg. I read on the www how .avif is better but it seems that this may not always
be the case. It would be great if imagemagick could also have some guides to
explain potential uses and non-uses; if I'd only go for the www, I'd ditch my old
.jpg files, but if the compression ratio for smaller images is worse, then it makes
no real sense to convert them to a format that isn't better. But this may be due
to user lack of knowledge - hard to say for me right now. I have only experience
with .jpg and .png.

**Comment by TianyiShi2001** [comment] 2021-04-05 17:40
@rubyFeedback Looks like you're also having the issue that the encoder is not working and the image data was silently copied to the `.avif` file in the same encoding format as the input. This has been mentioned above and I'm also experiencing this issue on Linux (macOS seems fine)
