### ISSUE TITLE
Drawing glitch/artifacts with stroke widths larger than 2

### ISSUE THREAD

**Issue by MarkMurphy** [ImageMagick/ImageMagick#218] opened 2016-06-10 16:43 UTC
The following is reproducible with at least 3 non-equidistant points and a stroke width larger than 2.

**Example**
  
```
convert -size 200x400 xc:white \
-draw 'stroke red stroke-width 20 polyline 100,200 100,250 100,350' \
line.png
```

**Result**
![line](https://cloud.githubusercontent.com/assets/873474/16339353/92d0d336-39f8-11e6-93c3-81bd12678a03.png)

What's odd is that if you tweak the `y` coordinates to be at equal distances apart from one another, this glitch seems to disappear. eg. `polyline 100,100 100,200 100,300`

**Comment by MarkMurphy** [comment] 2016-06-10 16:57
I've also noticed that if you apply `stroke-linecap round` and `stroke-linejoin round`, the artifacts are gone. 

eg.
```
convert -size 200x400 xc:white \
-draw 'stroke red stroke-width 20 stroke-linecap round stroke-linejoin round \
polyline 100,200 100,250 100,350' \
line.png
```

**Comment by mikayla-grace** [comment] 2016-06-11 20:16
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by MarkMurphy** [comment] 2016-06-13 16:44
@mikayla-grace should this be working in v6.9.4-9?

**Comment by mikayla-grace** [comment] 2016-06-23 23:02
Try ImageMagick 6.9.4-10.  Let us know if it wide strokes work as expected.

**Comment by MarkMurphy** [comment] 2016-06-24 14:22
@mikayla-grace Looks like this does indeed work as expected in 6.9.4-10 however, it appears that a new bug may have been introduced.

```
path='M 178,262 L 178,302 L 202,346'

convert -size 400x400 xc:none \
-draw "fill none stroke '#0004' stroke-width 6 stroke-linecap round path '$path'" \
-draw "fill none stroke red stroke-width 2 stroke-linecap round path '$path'" \
path.png
```

![path](https://cloud.githubusercontent.com/assets/873474/16340174/fc36938e-39fc-11e6-9b7a-383618efc4bb.png)

Notice how at the bend, the darker semi-transparent line doesn't line up with the red line even though they both have the exact same points. This was previously working as expected prior to `6.9.4-10`

Subtract 100 from each x,y coordinate and all of a sudden that issue oddly enough, disappears:

```
path='M 78,162 L 78,202 L 102,246'

convert -size 400x400 xc:none \
-draw "fill none stroke '#0004' stroke-width 6 stroke-linecap round path '$path'" \
-draw "fill none stroke red stroke-width 2 stroke-linecap round path '$path'" \
path.png
```

![path](https://cloud.githubusercontent.com/assets/873474/16340248/684040ca-39fd-11e6-824b-d75ed0550fab.png)

I'm not sure if this should be opened as a new issue or if it should be considered part of this issue.

**Comment by mikayla-grace** [comment] 2016-06-24 16:07
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

As before, this is due to numerical stability.  This problem is fixed with a slight adjustment to the epsilon value.

**Comment by MarkMurphy** [comment] 2016-07-11 14:36
Hey guys, I just tried this out with 6.9.5-1 and things have gotten much worse:

```
path='M 78,162 L 78,202 L 102,246'

convert -size 400x400 xc:none \
-draw "fill none stroke '#000' stroke-opacity 0.4 stroke-width 6 stroke-linecap round path '$path'" \
-draw "fill none stroke red stroke-width 2 stroke-linecap round path '$path'" \
path.png
```

![path](https://cloud.githubusercontent.com/assets/873474/16734241/30436eb6-475b-11e6-9522-fe006cff050f.png)

The tapered elbow is much more pronounced and the red stoke color has been completely ignored.

The same result can be achieved with this simplified command:


```
convert -size 400x400 xc:none \
-draw "fill none stroke red stroke-width 2 path 'M 78,162 L 78,202 L 102,246'" path.png
```

**Comment by mikayla-grace** [comment] 2016-07-11 19:34
We caught that a few days ago and fixed the problem.  Try 6.9.5-2.

**Comment by MarkMurphy** [comment] 2016-07-13 15:37
6.9.5-2 looks good.

**Closed** 2016-07-13 15:39 UTC
