### ISSUE TITLE
IM adds additional layers to PSB files

### ISSUE THREAD

**Issue by bediicco** [ImageMagick/ImageMagick#6113] opened 2023-02-27 19:26 UTC
### ImageMagick version

7.1.0-62

### Operating system

Windows

### Operating system, version and so on

Win 10 Pro 64 22H2

### Description

Converting a file (TIFF|PNG) to PSB using `magick in.tif out.psb` adds additional layers. As PSB is **PLANAR ORDER** every layer has 100% of size and in addition it cannot be processed technically like the original. See https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/ for PSB in _Image Data Section_ ("... Image data is stored in planar order: first all the red data, then all the green data, etc. Each plane is stored in scan-line order, with no pad bytes...")

![image](https://user-images.githubusercontent.com/126161988/221660696-b64cb748-249c-4b3d-b019-c17600dbf9c6.png)

![image](https://user-images.githubusercontent.com/126161988/221660729-1850f5cb-920b-483b-a28a-7a61e9c940d3.png)

My real-world images are gigapixel photos with a size of 5 up to 20 GB.

If i convert a 13GB file it becomes 26GB in size (very bad for uploading and saving) and cannot be further processed.

### Steps to Reproduce

`magick in.tif out.psb`
`magick in.png out.psb`

Photoshop: simply create a blank white TIFF file. Save it, open it, save it as PSB.
ImageMagick: `magick`

### Images

Here is a blank white sample (image 1): [images.zip](https://github.com/ImageMagick/ImageMagick/files/10843237/images.zip)

**Comment by fmw42** [comment] 2023-02-27 19:33
I do not see any extra layers in your images. I have viewed them in Photoshop and they all have just one layer. The layer names are different. One has L1 name and the other two have Background name. So I do not see what the issue is other than name changes.

**Comment by bediicco** [comment] 2023-02-27 19:36
As said serveral times to you:

- it becames double in size!
- you must merge to background layer (to resize to one layer in filesize!)
- it can not be further processed by business companies who are processing PSB files automatically!

**Comment by fmw42** [comment] 2023-02-27 19:42
OK. I see the second layer now.

```
magick identify original.tif original.psb
original.tif TIFF 600x600 600x600+0+0 16-bit sRGB 2.07992MiB 0.000u 0:00.001
original.psb[0] PSB 600x600 600x600+0+0 16-bit sRGB 4.12565MiB 0.010u 0:00.002
original.psb[1] PSB 600x600 600x600+0+0 16-bit sRGB 0.000u 0:00.000
```

The PSB has two layers, though the second layer [1] is zero size and the first is about double the size of the tiff. So I am not sure what that is.

One of the IM developers will have to comment.

**Comment by dlemstra** [comment] 2023-02-27 21:55
Closing this because there is no need to start a discussion and an issue.

**Closed by dlemstra** 2023-02-27 21:55 UTC

**Comment by bediicco** [comment] 2023-02-27 22:23
Solved https://github.com/ImageMagick/ImageMagick/discussions/6109

Thank you very much @fmw42 @dlemstra 

👍
