### ISSUE TITLE
Font ligatures not joining on Linux 

### ISSUE THREAD

**Issue by mryoubou** [ImageMagick/ImageMagick#6124] opened 2023-03-02 15:37 UTC
### ImageMagick version

7.1.0-62

### Operating system

Linux

### Operating system, version and so on

Debian 10 and 11, Ubuntu 22.04

### Description

I have noticed that the ligatures are not joining properly on Debian 10 when using ImageMagick 7.1.0-62 and 6 (I have tried multiple 7.1.XX versions same issue as well), while they work fine on Windows 11 or 10. 

I have tried to test this on Debian 11, Ubuntu 22.04, Bitnami Virtual-machine and the same issue persists.

I have created an images which demonstrates the problem

- On Windows :
![ImageMagick Windows](https://user-images.githubusercontent.com/72652218/222470761-c49cbf50-aaf3-48d5-ac84-c9febb9bf8b6.jpg)

- On Linux :
![ImageMagick Debian](https://user-images.githubusercontent.com/72652218/222470546-cfffc40a-e235-4b6b-96e0-266db3dd5fa1.jpg)

**Imagick Configuration on Debian 10 - Ligatures not joining**

$ magick -version

```
Array ( 

    [0] => Version: ImageMagick 7.1.0-61 Q16-HDRI x86_64 6b11831de:20230205 https://imagemagick.org 
    [1] => Copyright: (C) 1999 ImageMagick Studio LLC [2] => License: https://imagemagick.org/script/license.php 
    [3] => Features: Cipher DPC HDRI Modules OpenMP(4.5) 
    [4] => Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib 
    [5] => Compiler: gcc (8.3) 
)
```

$ magick identify -list configure

```
Array ( 
[0] => 
[1] => Path: /usr/local/lib/ImageMagick-7.1.0//config-Q16HDRI/configure.xml 
[2] => 
[3] => Name Value 
[4] => ------------------------------------------------------------------------------- 
[5] => CC gcc 
[6] => CFLAGS -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libraw -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/OpenEXR -I/usr/include/lqr-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/openjpeg-2.3 -I/usr/local/include -I/usr/include/graphviz -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -fopenmp -Wall -O3 -march=native -mtune=core2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 
[7] => CODER_PATH /usr/local/lib/ImageMagick-7.1.0/modules-Q16HDRI/coders 
[8] => CONFIGURE ./configure '--prefix=/usr/local' '--sysconfdir=/etc' 'CFLAGS=-O3 -march=native' 'CXXFLAGS=-O3 -march=native' '--disable-static' '--enable-shared' '--enable-openmp' '--enable-cipher' '--enable-hdri' '--enable-docs' '--disable-opencl' '--with-threads' '--with-modules' '--with-quantum-depth=16' '--with-magick-plus-plus' '--with-perl' '--without-jemalloc' '--without-tcmalloc' '--without-umem' '--without-autotrace' '--with-bzlib' '--with-x' '--with-zlib' '--with-zstd' '--without-dps' '--with-fftw' '--without-flif' '--without-fpx' '--with-djvu' '--with-fontconfig' '--with-freetype' '--with-raqm' '--with-gslib' '--with-gvc' '--with-heic' '--with-jbig' '--with-jpeg' '--with-jxl=yes' '--with-lcms' '--with-openjp2' '--with-lqr' '--with-lzma' '--with-openexr' '--with-pango' '--with-png' '--with-raw' '--with-rsvg' '--with-tiff' '--with-webp' '--with-wmf' '--with-xml' '--with-dejavu-font-dir=/usr/share/fonts/truetype/ttf-dejavu' '--with-gs-font-dir=/usr/share/fonts/type1/gsfonts' '--with-urw-base35-font-dir=/usr/share/fonts/type1/urw-base35' '--with-fontpath=/usr/share/fonts/type1' 'PSDelegate=/usr/bin/gs' 'CC=gcc' 'CXX=g++' 
[9] => CONFIGURE_PATH /etc/ImageMagick-7/ 
[10] => COPYRIGHT Copyright (C) 1999 ImageMagick Studio LLC 
[11] => CPPFLAGS -I/usr/local/include/ImageMagick-7 
[12] => CXX g++ 
[13] => CXXFLAGS -O3 -march=native -pthread 
[14] => DEFS -DHAVE_CONFIG_H 
[15] => DELEGATES bzlib djvu fftw fontconfig freetype gslib heic jbig jng jpeg jxl lcms lqr lzma openexr openjp2 pango png ps raqm raw rsvg tiff video webp wmf x xml zip zlib zstd 
[16] => DISTCHECK_CONFIG_FLAGS 'CC=gcc' 'CFLAGS=-O3 -march=native' 'CXX=g++' --disable-deprecated --with-quantum-depth=16 --with-jemalloc=no --with-umem=no --with-autotrace=no --with-dps=no --with-dejavu-font-dir=/usr/share/fonts/truetype/ttf-dejavu --with-flif=no --with-fpx=no --with-fontpath=/usr/share/fonts/type1 --with-gs-font-dir=/usr/share/fonts/type1/gsfonts --with-urw-base35-font-dir=/usr/share/fonts/type1/urw-base35 
[17] => DOCUMENTATION_PATH /usr/local/share/doc/ImageMagick-7 
[18] => EXEC-PREFIX /usr/local 
[19] => EXECUTABLE_PATH /usr/local/bin 
[20] => FEATURES DPC HDRI Cipher OpenMP Modules 
[21] => FILTER_PATH /usr/local/lib/ImageMagick-7.1.0/modules-Q16HDRI/filters 
[22] => GIT_REVISION 6b11831de:20230205 
[23] => HOST x86_64-pc-linux-gnu 
[24] => INCLUDE_PATH /usr/local/include/ImageMagick-7 
[25] => LDFLAGS -L/usr/local/lib 
[26] => LIB_VERSION 0x710 
[27] => LIB_VERSION_NUMBER 7,1,0,61 
[28] => LIBRARY_PATH /usr/local/lib/ImageMagick-7.1.0 
[29] => LIBS -llcms2 -lfreetype -lraqm -lfreetype -llqr-1 -lglib-2.0 -lfftw3 -lxml2 -lfontconfig -lfreetype -lXext -lSM -lICE -lX11 -lbz2 -lz -lzip -lltdl -lm -lpthread -lgomp 
[30] => NAME ImageMagick 
[31] => PCFLAGS -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 
[32] => PREFIX /usr/local 
[33] => QuantumDepth 16 
[34] => RELEASE_DATE 2023-02-05 
[35] => SHARE_PATH /usr/local/share/ImageMagick-7 
[36] => SHAREARCH_PATH /usr/local/lib/ImageMagick-7.1.0/config-Q16HDRI 
[37] => TARGET_CPU x86_64 [38] => TARGET_OS linux-gnu 
[39] => TARGET_VENDOR pc 
[40] => VERSION 7.1.0 
[41] => WEBSITE https://imagemagick.org 
[42] => [43] => Path: [built-in]
[44] => 
[45] => Name Value 
[46] => ------------------------------------------------------------------------------- 
[47] => DELEGATES bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib 
[48] => FEATURES Cipher DPC HDRI Modules OpenMP(4.5) 
[49] => MAGICK_TEMPORARY_PATH /tmp 
[50] => NAME ImageMagick 
[51] => QuantumDepth Q16 )


```
************************************

**Imagick Configuration on Windows - Ligatures  joining**

$ magick -version

```
Array (
    [0] => Version: ImageMagick 7.1.0-61 Q16-HDRI x64 d396287:20230205 https://imagemagick.org
    [1] => Copyright: (C) 1999 ImageMagick Studio LLC
    [2] => License: https://imagemagick.org/script/license.php
    [3] => Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
    [4] => Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
    [5] => Compiler: Visual Studio 2022 (193431937)
)
```

$ magick identify -list configure

```
Array (
    [0] => 
    [1] => Path: [built-in]
    [2] => 
    [3] => Name                  Value
    [4] => -------------------------------------------------------------------------------
    [5] => DELEGATES             bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
    [6] => FEATURES              Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
    [7] => MAGICK_TEMPORARY_PATH C:/Users/Youssef/AppData/Local/Temp
    [8] => NAME                  ImageMagick
    [9] => QuantumDepth          Q16
    [10] => 
    [11] => Path: C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\configure.xml
    [12] => 
    [13] => Name                  Value
    [14] => -------------------------------------------------------------------------------
    [15] => CC                    VS2022
    [16] => COPYRIGHT             Copyright (C) 1999 ImageMagick Studio LLC
    [17] => CXX                   VS2022
    [18] => DOCUMENTATION_PATH    unavailable
    [19] => GIT_REVISION          d396287:20230205
    [20] => LIB_VERSION           0x710
    [21] => LIB_VERSION_NUMBER    7,1,0,61
    [22] => NAME                  ImageMagick
    [23] => QuantumDepth          1
    [24] => RELEASE_DATE          2023-02-05
    [25] => TARGET_CPU            x64
    [26] => TARGET_OS             Windows
    [27] => VERSION               7.1.0
    [28] => WEBSITE               https://imagemagick.org
)

```

### Steps to Reproduce

I used this functions to create text on image : 

**Imagick::annotateImage**
https://phpimagick.com/Imagick/annotateImage?stroke_color=rgb(0%2C%200%2C%200)&fill_color=white&image_path=Lorikeet

**ImagickDraw::annotation**

https://phpimagick.com/ImagickDraw/setTextAlignment?background_color=rgb(225%2C%20225%2C%20225)&stroke_color=rgb(0%2C%200%2C%200)&fill_color=DodgerBlue2

**Comment by urban-warrior** [comment] 2023-03-03 01:11
And what font are you using?  Set the MAGICK_DEBUG environment variable to `annotate`.

**Comment by mryoubou** [comment] 2023-03-04 10:35
Here are the FreeType versions on each testing environment I tested:

Windows:
```
"C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\CORE_RL_freetype_.dll"  => Version 2.12.1
"D:\XAMPP\apache\bin\CORE_RL_freetype_.dll" => Version 2.10.4
```

Ubuntu :

```
libfreetype-dev/jammy-updates,jammy-security,now 2.11.1+dfsg-1ubuntu0.1 amd64 [installed,automatic]
libfreetype6-dev/jammy-updates,jammy-security,now 2.11.1+dfsg-1ubuntu0.1 amd64 [installed,automatic]
libfreetype6/jammy-updates,jammy-security,now 2.11.1+dfsg-1ubuntu0.1 amd64 [installed]
```

Debian 10

```
libfreetype6-dev/oldstable,now 2.9.1-3+deb10u3 amd64 [installed]
libfreetype6/oldstable,now 2.9.1-3+deb10u3 amd64 [installed,automatic]
```

Text on image using annotate with MAGICK_DEBUG  :
```
root@ubuntu:~/Downloads$ convert -size 800x400 xc:white background.jpg
root@ubuntu:~/Downloads$ convert -debug "annotate" -font Gloock-Regular.ttf -pointsize 200 background.jpg -gravity center -annotate 0 'find fly' text.jpg 

2023-03-03T23:15:56+00:00 0:00.004 0.000u 7.1.0 Annotate convert[6944]: annotate.c/RenderFreetype/1754/Annotate

  Font Gloock-Regular.ttf; font-encoding none; text-encoding none; pointsize 100

2023-03-03T23:15:56+00:00 0:00.005 0.000u 7.1.0 Annotate convert[6944]: annotate.c/GetTypeMetrics/933/Annotate

  Metrics: text: find fly; width: 316; height: 120; ascent: 98; descent: -23; max advance: 128; bounds: -6.70312,-22  64.9062,78; origin: 315.109,0; pixels per em: 100,100; underline position: -12.5; underline thickness: 5

2023-03-03T23:15:56+00:00 0:00.006 0.000u 7.1.0 Annotate convert[6944]: annotate.c/RenderFreetype/1754/Annotate

  Font Gloock-Regular.ttf; font-encoding none; text-encoding none; pointsize 100
```

Output on Ubuntu and Debian :
As you can see the fi and fl not connected :

![IM Linux](https://user-images.githubusercontent.com/72652218/222894402-47aa217a-ee21-4787-8321-d313e0fa5f78.jpg)

But on Windows works fine  see image bellow :

![IM Windows](https://user-images.githubusercontent.com/72652218/222894828-9f853488-b523-4ba8-a8fb-02e561100971.png)

**Comment by urban-warrior** [comment] 2023-03-04 12:25
The issue is likely related to the Freetype delegate library build.   It might be the release level, whether Freetype uses a native font renderer, if subpixels are enabled, whether hinting is enabled and whether patented hinting is enabled, whether the LCD filter is enabled (another patent issue)., etc..  We tried rendering your phrase with another app under Fedora that utilizes Freetype-- it produces the same results as ImageMagick confirming it is a Freetype issue.

**Comment by khaledhosny** [comment] 2023-03-05 07:02
You need to configure ImageMagick with `--with-raqm`, to enable proper text layout, including ligatures. This probably should be the default now since many distributions might not be enabling it.

**Comment by mryoubou** [comment] 2023-03-08 10:12
Hi Cristy, Khaled, Thank you for the suggestion, the image with ligatures issue above is with raqm library installed and ImageMagick configured with --with-raqm. 

```
[29] => LIBS -llcms2 -lfreetype -lraqm -lfreetype -llqr-1 -lglib-2.0 -lfftw3 -lxml2 -lfontconfig -lfreetype -lXext -lSM -lICE -lX11 -lbz2 -lz -lzip -lltdl -lm -lpthread -lgomp 
[47] => DELEGATES bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib 
```
Do ligatures working fine for you on Linux ? 

---
Font used in above image: https://fonts.google.com/specimen/Gloock

**Comment by mryoubou** [comment] 2023-03-14 11:25
Hi everyone,
Just wanted to check if you had a chance to take a look at the issue and let me know if there are any updates or next steps you can share.
Thank you for your time

**Comment by dlemstra** [comment] 2023-03-14 17:21
This is happening because of this commit: 977e449b4190f8d1bc300a44d1e80f89da483ba5. We recently made a fix according to the documentation of Freetype but it looks like they made a mistake in their documentation. I have asked upstream if they can fix it: https://gitlab.freedesktop.org/freetype/freetype/-/issues/1208. I will wait for their response before patching ImageMagick.

**Comment by dlemstra** [comment] 2023-03-15 06:01
This issue will be resolved in the next release.

**Closed by dlemstra** 2023-03-15 06:01 UTC

**Comment by mryoubou** [comment] 2023-03-15 19:59
Hi Dirk, I copied your recent changes and it's working fine right now, waiting for the next release :)
Thank you so much for spending time on fixing this one!
