### ISSUE TITLE
Possible issue with alpha value from %[pixel:...]

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5308] opened 2022-07-08 22:18 UTC
### ImageMagick version

7.1.0.41 Q16 HDRI

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

I have this image below.  What looks white is really transparent.

![tile_ff6](https://user-images.githubusercontent.com/13458218/178076849-adc74cee-5e15-4482-b87d-d1d101ee6aad.png)

Imagemagick  6.9.12-56 (says it is opaque, as it should in the black area, above the transparent area in the center):

`convert tile_ff6.png -depth 8 -format "%[pixel:u.p{44,10}]\n" info:`
graya(0,1)

Imagemagick 7.1.0.41 (says it is transparent in the black area)

`magick  tile_ff6.png -depth 8 -format "%[pixel:u.p{44,10}]\n" info:`
graya(0,0)

**I think that the IM 7 result is in error.**

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment] 2022-07-09 00:19
@snibgo, this likely is a `-fx` bug.  Can you take a look? 

```
$ magick tile_ff6.png -depth 8  -define fx:debug=true -format "%[pixel:u.p{44,10}]\n" info:
Operators:
  += -= *= /= ++ -- + - * / % + - << >> == != <= >= < > && || ! & | ~ ^ ? : ( ) [ ] { } =
Functions:
   abs acosh acos airy alt asinh asin atanh atan2 atan ceil channel clamp cosh cos debug drc erf exp floor gauss gcd hypot int isnan j0 j1 jinc ln logtwo log max min mod not pow rand round sign sinc sinh sin sqrt squish tanh tan trunc do for if while u u0 up s v p sp vp
Image attributes:
   depth extent kurtosis maxima mean median minima page page.x page.y page.width page.height printsize printsize.x printsize.y quality resolution resolution.x resolution.y skewness standard_deviation h n t w z
Symbols:
   hue intensity lightness luma luminance saturation a b c g i j k m o r y
Controls:
   goto ifzerogoto ifnotzerogoto copyfrom copyto zerstk 
UserSymbols (0)
DumpRPN:  numElements=100  usedElements=4  maxUsedOprStack=1  ImgListLen=1  NeedStats=no  GotStats=no  NeedHsl=no
CornerOnly
  0: Constant val=0 'onull' nArgs=0 ndx=0  push
  1: Constant val=44 'onull' nArgs=0 ndx=0  push
  2: Constant val=10 'onull' nArgs=0 ndx=0  push
  3: Function val=0 'up{}' nArgs=3 ndx=0  push
graya(0,0)
```

The old-style `-fx`, embedded in ImageMagick version 6, returns the correct results: `graya(0,1)`.

Thanks,

**Comment by snibgo** [comment] 2022-07-09 01:57
I can reproduce the problem, and will investigate. I expect it will take a couple of days.

**Comment by fmw42** [comment] 2022-07-09 02:22
Thanks. Not urgent.

**Comment by snibgo** [comment] 2022-07-09 05:21
Pre-built 7.1.0-32 has the problem. My home-built 7.1.0-20 doesn't. I will download the latest source and re-build.

It goes wrong when using p[] or p{} or u.p[] or u.p{}. In those, the value comes from InterpolatePixelChannel(). When it goes wrong, the alpha value is taken from the red channel (or gray channel, for grayscale images).

This will take some time to track down.

Meanwhile, "-interpolate integer" seems to be a workaround:
```
magick tile_ff6.png -depth 8 -interpolate integer -format "%[pixel:u.p{44,10}]\n" info:

graya(0,1)  <== correct
```

**Comment by urban-warrior** [comment] 2022-07-09 12:13
The issue is the special handling of the alpha channel when interpolated.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment] 2022-07-09 13:53
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by snibgo** [comment] 2022-07-09 15:59
Good stuff. I will assume that those changes to InterpolatePixelChannel() fix the problem, unless someone tells me otherwise.

**Comment by urban-warrior** [comment] 2022-07-09 16:12
Thanks for narrowing the issue to InterpolatePixelChannel().  The problem was variable channels can be addressed by offset or by channel type.  We had to introduce a mapping from channel type to offset to fix the issue.  Fortunately, InterpolatePixelChannel() is only called from `-fx` so the issue was localized.  Other algorithms use InterpolatePixelChannels() which was and is working correctly.

**Closed** 2022-07-10 06:46 UTC
