### ISSUE TITLE
[regression] converting to PDF does not generate thumbnail properly

### ISSUE THREAD

**Issue by petaflot** [ImageMagick/ImageMagick#7130] opened 2024-02-25 14:48 UTC
### ImageMagick version

7.1.1-25

### Operating system

Linux

### Operating system, version and so on

Gentoo x86_64

### Description

convert an image to pdf creates a PDF as expected, but the embedded thumbnail is only 1x1 pixel  and does not match the content of the file (white or black image, same-same, pixel is always white)

### Steps to Reproduce

`convert image.jpg image.pdf` 

### Images

[test2.pdf](https://github.com/ImageMagick/ImageMagick/files/14396715/test2.pdf)
![test2](https://github.com/ImageMagick/ImageMagick/assets/32837871/974343e3-ad37-4505-ba37-039704609954)

**Comment by petaflot** [comment] 2024-02-25 17:57
```
[I] media-gfx/imagemagick
     Available versions:  6.9.12.89-r1(0/6.9.12-58)^t 6.9.13.2(0/6.9.13-0)^t 6.9.13.3(0/6.9.13-0)^t 7.1.1.11(0/7.1.1-43)^t 7.1.1.24(0/7.1.1-18)^t 7.1.1.25(0/7.1.1-18)^t **9999(0/9999-18)*l^t {X bzip2 corefonts +cxx djvu fftw fontconfig fpx graphviz hardened hdri heif jbig jpeg jpeg2k jpegxl lcms lqr lzma opencl openexr openmp pango perl +png postscript q8 q32 raw static-libs svg test tiff truetype webp wmf xml zip zlib}
     Installed versions:  7.1.1.25(0/7.1.1-18)^t(17:14:20 25. 02. 24)(X bzip2 corefonts cxx jpeg jpeg2k lcms openmp pango png postscript raw svg tiff truetype webp xml zip zlib -djvu -fftw -fontconfig -fpx -graphviz -hardened -hdri -heif -jbig -jpegxl -lqr -lzma -opencl -openexr -perl -q8 -q32 -static-libs -test -wmf)
```
same with (changed used, to test..)
```
[I] media-gfx/imagemagick
    Installed versions:  7.1.1.25(0/7.1.1-18)^t(10:18:02 23. 01. 24)(X bzip2 cxx jpeg jpeg2k lcms openmp pango png svg tiff truetype xml zlib -corefonts -djvu -fftw -fontconfig -fpx -graphviz -hardened -hdri -heif -jbig -jpegxl -lqr -lzma -opencl -openexr -perl -postscript -q8 -q32 -raw -static-libs -test -webp -wmf -zip)
```

version info (proof of regression): tested OK with `6.9.13.3` ; fails with `7.1.1.11`

**Comment by urban-warrior** [comment] 2024-02-26 01:00
From the command-line, try

```
magick image.jpg -define pdf:thumbnail=true image.pdf
```

Thumbnails are hidden by default to reduce the resulting PDF file size.

**Comment by petaflot** [comment] 2024-02-28 08:43
ok, didn't realize this. it works.

I suggest to not include a thumbnail at all without the switch (ie. don't put a 1px placeholder at all) if that is possible : from what I have seen, thumbnailers will use that 1px thumbail instead of generating it dynamically.

**Comment by urban-warrior** [comment] 2024-03-23 22:00
We agree, we should not export a thumbnail by default, it is a known issue.  However, resolving the issue is pending until we can find time to code a workaround.

**Closed by urban-warrior** 2024-03-23 22:00 UTC
