### ISSUE TITLE
Imagemagick errors when converting GIF into animated webp

### ISSUE THREAD

**Issue by dooman87** [ImageMagick/ImageMagick#6047] opened 2023-02-09 10:07 UTC
### ImageMagick version

7.1.0-61

### Operating system

Linux

### Operating system, version and so on

Debian buster

### Description

One of the automated tests started failing when building a docker image with IM 7.1.0-61: 

https://github.com/dooman87/imagemagick-docker/actions/runs/4132741043/jobs/7141803908

The test was green on 7.1.0-56. 

The test is converting GIF into Webp. 

Here is the error message: `convert: ERROR adding frame: Invalid frame dimensions. `/imgs/test-gif.webp' @ error/webp.c/WriteAnimatedWEBPImage/965.`

### Steps to Reproduce

Run convert command:

```
convert test.gif test-gif.webp
```

### Images

![test](https://user-images.githubusercontent.com/124110/217782222-a9f5b3ce-18e0-48ba-8bf0-0bc5053504c2.gif)

**Comment by dlemstra** [comment] 2023-02-09 10:49
Duplicate of #6041.

**Closed by dlemstra** 2023-02-09 10:49 UTC
