### ISSUE TITLE
download imagemagick.org gets connection timeout error

### ISSUE THREAD

**Issue by AnuMano** [ImageMagick/ImageMagick#7320] opened 2024-05-16 12:53 UTC
### ImageMagick version

7.1.1 

### Operating system

Other (enter below)

### Operating system, version and so on

Ubuntu-latest

### Description

I have tried to install the imagemagic from source 
When accessing the below url, got connection timeout error
https://www.imagemagick.org/download/ImageMagick.tar.gz

 

### Steps to Reproduce

When I open the download url in the browser, it cannot be reached.

**Comment by dlemstra** [comment] 2024-05-16 12:56
Duplicate of #7319. Next time please check the current/closed issues before you start a new one.

**Closed by dlemstra** 2024-05-16 12:56 UTC
