### ISSUE TITLE
ERROR adding frame: Invalid frame dimensions.

### ISSUE THREAD

**Issue by Sansekai** [ImageMagick/ImageMagick#6065] opened 2023-02-15 08:05 UTC
### ImageMagick version

7.1.0-62

### Operating system

Windows

### Operating system, version and so on

Windows

### Description

I use command:

`magick APNG:image.png image_o.webp`
And showing error this
`error : Error: Command failed: magick APNG:image.png image_o.webp
magick: ERROR adding frame: Invalid frame dimensions. 'image_o.webp' @ error/webp.c/WriteAnimatedWEBPImage/965.`

### Steps to Reproduce

`magick APNG:image.png image_o.webp`

### Images

![154696149](https://user-images.githubusercontent.com/34540627/218968247-35662aa2-5cb1-4c11-8e4d-631c63b1d4bb.png)

**Comment by dlemstra** [comment] 2023-02-15 09:54
Duplicate of #6041.

**Closed by dlemstra** 2023-02-15 09:54 UTC
