### ISSUE TITLE
Support Keeping Metadata When Converting From TIFF to JXL

### ISSUE THREAD

**Issue by cp2732** [ImageMagick/ImageMagick#5768] opened 2022-11-17 17:56 UTC
### Is your feature request related to a problem? Please describe.

While ImageMagick supports converting from TIFF to JXL, it does not support transferring original metadata information found in the TIFF format.

### Describe the solution you'd like

I would like to see direct conversions from TIFF to JXL, where all metadata is preserved from the TIFF image file.

### Describe alternatives you've considered

When generating a JXL file using the cjxl utility, all metadata information is preserved. However, TIFF is not a supported input file format (only certain files, like PNG, are allowed as input). Therefore, I must convert my TIFF files to PNG using ImageMagick (which does preserve metadata), which then allows me to use the PNG file as an input to cjxl.

I have already requested libjxl to support TIFF as an additional input file format to allow for more flexibility: https://github.com/libjxl/libjxl/issues/1901#issuecomment-1318276259

**Comment by fmw42** [comment] 2022-11-17 18:20
You can use EXIFTOOL to transfer meta data from one file to another.

**Comment by urban-warrior** [comment] 2022-11-25 17:25
We added support to read/write EXIF/XMP JXL metadata in main.  Let us know if to works/fails for you.

**Comment by cp2732** [comment] 2022-11-26 03:15
I tried to convert a couple different files, but did not have luck getting any additional metadata to copy over compared to what I saw earlier when trying to convert using ImageMagick-7.1.0-Q16-HDRI on Windows. In particular, I have ICC Profiles I would like to copy over from my TIFF version, but they do not show up in the JXL one. I have attached a sample input file and the output file I get when doing the conversion. After following the instructions at https://github.com/ImageMagick/ImageMagick-Windows to install the latest version of ImageMagick, the command I used after navigating to ImageMagick-Windows\VisualMagick\bin was `.\magick -define jxl:effort=9 -define jxl:quality=100 input.tif output.jxl`
[input.zip](https://github.com/ImageMagick/ImageMagick/files/10095574/input.zip)
[output.zip](https://github.com/ImageMagick/ImageMagick/files/10095575/output.zip)
![TIFF EXIF Info](https://user-images.githubusercontent.com/5529206/204070129-5d203020-b5ad-4b94-8d80-20a9b9d7d522.PNG)
![JXL EXIF Info](https://user-images.githubusercontent.com/5529206/204070132-1ae530ed-eb41-471d-aa01-cbe4482ff4d8.PNG)
![Convert Process](https://user-images.githubusercontent.com/5529206/204070350-ed10a4b4-f1ff-4ca3-aba5-e95059762f60.PNG)

Please let me know if I should follow a different process or if I am missing a step.

**Comment by urban-warrior** [comment] 2022-11-26 04:06
`exiftool` may be able to extract extensive metadata from TIFF but not with JXL.  Try `identiify -verbose input.tif output.jxl` instead, you'll get similar results.  Note, ImageMagick can currently read/write the ICC, Exif, and XMP profiles to/from the JXL image format.

**Comment by cp2732** [comment] 2022-11-26 16:29
When I try to perform `magick output.jxl output.tif` on both Windows and Mac, it does not appear to generate the output TIFF file (it appears the program aborts). I'm not sure if you see that as well?

I also noticed that the output.jxl file size is the same after performing both of these commands:
`.\magick input.tif output.jxl`
`.\magick -define tiff:exif-properties=true input.tif output2.jxl`

Are you sure the EXIF metadata is currently capable of being carried over from TIFF to JXL? I also tried to open it in XnView MP and it could not identify the EXIF metadata or ICC Profile in the JXL file. Using `identify -verbose output.jxl` does not show anything (see screenshot).
![ICC Profile Not Transferred](https://user-images.githubusercontent.com/5529206/204098776-73e11daa-aef3-4007-b0da-c7fa172915df.PNG)
![ICC Profile Not Transferred 2](https://user-images.githubusercontent.com/5529206/204098785-9f58aa0b-1552-4e3c-851b-72b62a2d768f.PNG)

**Comment by fmw42** [comment] 2022-11-26 16:46
What version of IM?  What platform/OS?

**Comment by urban-warrior** [comment] 2022-11-26 17:06
Your `input.tif` image does not contain an EXIF profile, so none can be read, even with the `-define tiff:exif-properties=true` command-line argument:

```
$ tiffdump input.tif
input.tif:
Magic: 0x4949 <little-endian> Version: 0x2a <ClassicTIFF>
Directory 0: offset 186852 (0x2d9e4) next 0 (0)
ImageWidth (256) SHORT (3) 1<1021>
ImageLength (257) SHORT (3) 1<183>
BitsPerSample (258) SHORT (3) 1<8>
Compression (259) SHORT (3) 1<1>
Photometric (262) SHORT (3) 1<1>
StripOffsets (273) LONG (4) 183<8 1029 2050 3071 4092 5113 6134 7155 8176 9197 10218 11239 12260 13281 14302 15323 16344 17365 18386 19407 20428 21449 22470 23491 ...>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<1>
RowsPerStrip (278) SHORT (3) 1<1>
StripByteCounts (279) LONG (4) 183<1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 1021 ...>
XResolution (282) RATIONAL (5) 1<600>
YResolution (283) RATIONAL (5) 1<600>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<2>
ICC Profile (34675) UNDEFINED (7) 444<00 00 0x1 0xbc 0x41 0x50 0x50 0x4c 0x2 0x20 00 00 0x6d 0x6e 0x74 0x72 0x47 0x52 0x41 0x59 0x58 0x59 0x5a 0x20 ...>
```

We get the occasional abort as well.  If we run the program within `gdb`, it never aborts, perhaps suggesting a threading issue.  The JXL delegate library is pre-production release @ 0.7.0 (production is normally 1.0.0), so we're not sure if ImageMagick is not properly calling the delegate library API  or if there is a bug in the JXL library.

**Comment by cp2732** [comment] 2022-11-26 20:46
@fmw42 The version of ImageMagick I used appears to be `ImageMagick 7.1.0-53 beta Q16-HDRI x64`, since I wanted to build the latest code from the main branch.
```
>.\magick -version
Version: ImageMagick 7.1.0-53 beta Q16-HDRI x64 47cb46829:20221125 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193431933)
```

I built ImageMagick using Visual Studio 2022 on Windows 10 Education edition, version 22H2 (OS build 19045.2251).

@urban-warrior The image viewer I am using (NxView MP) suggests there is EXIF information, since it displays EXIF tags, which include Image Width, Image Height, Bits Per Sample, etc. This is classified under the IFD0 Group, based on what I see here: https://exiftool.org/TagNames/EXIF.html.

I was not sure if it is possible to copy over this information, in addition to the ICC Profile (is `-define tiff:exif-properties=true` supposed to do that or is there a different option I would need)?
![EXIF IFD0](https://user-images.githubusercontent.com/5529206/204108198-1f72d6ee-7859-4185-b342-ea8496b5b018.PNG)

Thanks for mentioning that `gdb` works for you. I will give it a try and see if it helps when converting from JXL to TIFF.

**Comment by fmw42** [comment] 2022-11-26 21:15
Perhaps it is still in development and not yet in the beta

**Comment by urban-warrior** [comment] 2022-11-26 22:59
From the documentation, `tiffdump` displays directory information from a TIFF image file.   An EXIF profile is stored with an ID of 34665.  From the dump above you can see there is no such ID.  Image attributes can come from other TIFF attributes other than an EXIF profile.  Certainly image width, height, depth, resolution, etc., are all available as well defined fields per the TIFF image format specification.

EXIF information can be embedded in a XMP profile also.  For example,

```
      <rdf:Description rdf:about=""
            xmlns:exif="http://ns.adobe.com/exif/1.0/">
         <exif:ExposureTime>1/125</exif:ExposureTime>
         <exif:ShutterSpeedValue>6965784/1000000</exif:ShutterSpeedValue>
         <exif:FNumber>45/10</exif:FNumber>
         <exif:ApertureValue>433985/100000</exif:ApertureValue>
         <exif:ExposureProgram>1</exif:ExposureProgram>
         <exif:DateTimeOriginal>2005-05-03T14:59:13+02:00</exif:DateTimeOriginal>
         <exif:ExposureBiasValue>0/1</exif:ExposureBiasValue>
         <exif:MeteringMode>5</exif:MeteringMode>
         <exif:FocalLength>32/1</exif:FocalLength>
         <exif:ISOSpeedRatings>
            <rdf:Seq>
               <rdf:li>500</rdf:li>
            </rdf:Seq>
         </exif:ISOSpeedRatings>
         <exif:PixelXDimension>3241</exif:PixelXDimension>
         <exif:PixelYDimension>4136</exif:PixelYDimension>
         <exif:ColorSpace>-1</exif:ColorSpace>
         <exif:NativeDigest>36864,40960,40961,37121,37122,40962,40963,37510,40964,36867,36868,33434,33437,34850,34852,34855,34856,37377,37378,37379,37380,37381,37382,37383,37384,37385,37386,37396,41483,41484,41486,41487,41488,41492,41493,41495,41728,41729,41730,41985,41986,41987,41988,41989,41990,41991,41992,41993,41994,41995,41996,42016,0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,22,23,24,25,26,27,28,30;1D39731042A92A1128F4317E45974F2E</exif:NativeDigest>
         <exif:Flash rdf:parseType="Resource">
            <exif:Fired>True</exif:Fired>
            <exif:Return>0</exif:Return>
            <exif:Mode>1</exif:Mode>
            <exif:Function>False</exif:Function>
            <exif:RedEyeMode>False</exif:RedEyeMode>
         </exif:Flash>
      </rdf:Description>
```

If you can prove `input.tif` has metadata that ImageMagick is not reading, we'll take a closer look.   Start with `identify -verbose` and follow with `magick input.tif input.miff`.  The MIFF format usually encapsulates all the metadata ImageMagick knows about.  Some metadata could be lost when written to JXL.  We'll worry about that later.  Instead focus on the former.  Is ImageMagick overlooking metadata in the TIFF image?   

Here's all the news fit to print-- that is, here is the output of `tiffinfo input.tif`:

```
$ tiffinfo input.tif
TIFF Directory at offset 0x2d9e4 (186852)
  Image Width: 1021 Image Length: 183
  Resolution: 600, 600 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 1
  Planar Configuration: single image plane
  ICC Profile: <present>, 444 bytes
```

**Comment by fmw42** [comment] 2022-11-26 23:27
I do not know if this will help, but this is the meta data information that I see in Photoshop for input.tif

![Screen Shot 2022-11-26 at 3 26 35 PM](https://user-images.githubusercontent.com/13458218/204112532-42034037-74dd-48aa-9a5e-b8affde3c252.png)

**Comment by urban-warrior** [comment] 2022-11-27 00:15
Photoshop can build its own XMP proile as they invented the standard.  Try writing the TIFF and see if there is an Photoshop option to embed a XMP or EXIF profile.  If so, post the TIFF image here so we can inspect it.

**Comment by fmw42** [comment] 2022-11-27 00:27
Looks like just saving to a new TIFF creates an XMP file.

![Screen Shot 2022-11-26 at 4 25 26 PM](https://user-images.githubusercontent.com/13458218/204113924-f85e18cd-b83d-4845-962c-8a7c6ae8588c.png)

Here is the newly saved TIFF copy:

[input2.tif.zip](https://github.com/ImageMagick/ImageMagick/files/10097272/input2.tif.zip)

**Comment by urban-warrior** [comment] 2022-11-27 03:16
As expected, `magick identify -verbose` correctly reads the XPM profile.   In addition, converting to TIFF or  JXL correctly saves the XMP profile.   Adobe likely embeds all the Exif tags in the XMP profile so an explicit Exif profile is not needed.  Your `input2.tif` image only preserves these Exif tags:

```
<exif:ColorSpace>65535</exif:ColorSpace>
<exif:PixelXDimension>1021</exif:PixelXDimension>
<exif:PixelYDimension>183</exif:PixelYDimension>
```

We do see plenty of Tiff tags such as the resolution, orientation, photo-metric interpretation, etc.  Given this revelation, is there any reason to believe ImageMagick is deficient in any way in terms of properly reading and embedding metadata?

**Comment by kmilos** [comment] 2022-11-30 16:30
Btw, (recent) exiftool has no problem reading Exif and XMP metadata from JPEG XL images, try the sample here: https://w2w-images.sftcdn.net/image/upload/v1620662834/Ghacks/IMG_20200308_194050.jxl w/ `exiftool -a -u -s -g1` (the -g1 or -G1 switch are very useful in giving you the metadata group)

**Comment by kmilos** [comment] 2022-12-05 16:09
There are still a few problems present w/ Exif transfer to/from JPEG XL (using the latest Windows `ImageMagick-7.1.0-53-Q16-HDRI-x64-dll.exe` installer), as described here and below: https://github.com/ImageMagick/ImageMagick/commit/030f1fa8bedf29886b10753f14e8c3a372910af5#commitcomment-92061777

**Comment by kmilos** [comment] 2022-12-05 17:01
Re the Exif JPEG APP1 header, it should be probably removed by the JPEG coder on read (and re-added on write), [like the XMP one is](https://github.com/ImageMagick/ImageMagick/blob/de94d35d31d9a931efb5bb9f1bbfb04de44f3788/coders/jpeg.c#L679), rather than having to be addressed by every other coder on a case-by-case basis...

**Comment by kmilos** [comment] 2022-12-05 17:19
On the box size and offset calculations, see also https://github.com/ImageMagick/ImageMagick/commit/bb4018a4dc61147b37d3c42d85e5893ca5e2a279 (JPEG XL and HEIF implement the same spec for Exif boxes)

**Comment by kmilos** [comment] 2022-12-06 09:06
I'm not that proficient in IM inner string manipulation methods, but it seems to me that in that last commit you're actually adding the `Exif\0\0` header to the read profile and keeping it when writing to JPEG XL Exif box, is that correct?

**Comment by urban-warrior** [comment] 2022-12-07 01:09
Anything we carry internally with Imagemagick should not have a significant impact as long as its managed consistently and properly.    And as long as the profile is exported properly in each image format that supports the EXIF profile, we should be good.  Given that, we certainly could change how the profile is handled internally if there was a compelling reason.  Support for the EXIF profile within ImageMagick has been around for a long time.  If we change it now, it could break existing legacy scripts.  Note also, that XMP is generally prefixed with a namespace, `http://ns.adobe.com/xap/1.0/`.  Prefixing the EXIF profile with the `Exif` namespace is similar in concept.

**Comment by kmilos** [comment] 2022-12-07 07:11
> XMP is generally prefixed with a namespace, `http://ns.adobe.com/xap/1.0/`

I disagree, it is not prefixed generally. It is only prefixed in the JPEG coder, and handled only there - nicely removed on read, added on write, and not carried around internally to other coders, so XMP is managed more consistently than Exif IMHO.

It's fine if you don't want to change other coders re Exif prefix. But that doesn't mean you absolutely need to introduce that legacy kludge into JPEG XL - I'm only suggesting you treat it as an exception in new code (i.e. remove it if you come across it), rather than a rule.

**Comment by kmilos** [comment] 2022-12-12 14:34
W/ 7.1.0-54, on `magick convert Reagan.jpg foo.jxl` I'm still getting 

```
  | EXIF (SubDirectory) -->
  | - Tag 'Exif' (5716 bytes):
  |     003a: 00 00 00 00 00 00 4d 4d 00 2a 00 00 00 08 00 13 [......MM.*......]
  |     004a: 01 00 00 03 00 00 00 01 00 c8 00 00 01 01 00 03 [................]
  |     005a: 00 00 00 01 00 82 00 00 01 02 00 03 00 00 00 04 [................]
  |     006a: 00 00 00 f2 01 03 00 03 00 00 00 01 00 01 00 00 [................]
  |     007a: 01 06 00 03 00 00 00 01 00 02 00 00 01 0e 00 02 [................]
  |     [snip 5636 bytes]
  | + [TIFF directory]
  | Warning = Unrecognized EXIF box
```

The 6 null bytes should be 4 bytes, or the payload offset should be set to 2 if you for some weird reason insist on keeping this as 6 bytes.

And I don't see how https://github.com/ImageMagick/ImageMagick/commit/1c7af5461d4defbcfcac2a8db3e4fb1a81324861 addresses this in a clean way either, sorry.

**Comment by kmilos** [comment] 2022-12-12 14:47
Furthermore, on the roundtrip back (`magick foo.jxl _Reagan.jpg`) I also see

```
JPEG APP1 (5718 bytes):
    0018: 45 78 69 66 00 00 00 00 4d 4d 00 2a 00 00 00 08 [Exif....MM.*....]
    0028: 00 13 01 00 00 03 00 00 00 01 00 c8 00 00 01 01 [................]
    0038: 00 03 00 00 00 01 00 82 00 00 01 02 00 03 00 00 [................]
    0048: 00 04 00 00 00 f2 01 03 00 03 00 00 00 01 00 01 [................]
    0058: 00 00 01 06 00 03 00 00 00 01 00 02 00 00 01 0e [................]
    0068: 00 02 00 00 01 93 00 00 00 fa 01 0f 00 02 00 00 [................]
    0078: 00 12 00 00 02 8d 01 10 00 02 00 00 00 0a 00 00 [................]
    [snip 5606 bytes]
  Warning = Malformed APP1 EXIF segment
```

**Comment by urban-warrior** [comment] 2022-12-12 17:04
There are additional patches in the Git main repo.  Try main and let us know if it resolves these issues.

**Comment by urban-warrior** [comment] 2022-12-12 17:44
Can you clone the main repo?  We're `00 00 00 00 4d 4d` for foo.jxl.  When we make the round trip with JPEG => JXL => JPEG, we get identical Exif profiles for both JPEG, JXL and the new JPEG.

**Comment by kmilos** [comment] 2022-12-13 08:49
That sounds better indeed.

Unfortunately I don't have the toolchain set up, are there any nightly builds available? I only see https://github.com/ImageMagick/ImageMagick/actions/workflows/release.yml but that does not have the last commits AFAICT?

**Comment by kmilos** [comment] 2022-12-26 09:11
@urban-warrior @dlemstra I'm afraid 7.1.0-55 made things even worse, as I suspected from those code changes:

There is now a regression re HEIFs where the non-zero offset is no longer used, and the payload is indiscriminately copied. Conversion of the sample in https://github.com/ImageMagick/ImageMagick/issues/5604 to e.g. PNG now yields the garbage eXIF chunk:

```
  | Warning = Invalid eXIf chunk
  eXIf = ..U.ExifII*....................................(....2.........i....%..........[snip]
  - Tag 'eXIf' (21892 bytes):
      0000: ff e1 55 80 45 78 69 66 00 00 49 49 2a 00 08 00 [..U.Exif..II*...]
      0010: 00 00 0d 00 00 01 03 00 01 00 00 00 00 10 00 00 [................]
      0020: 01 01 03 00 01 00 00 00 00 0c 00 00 0f 01 02 00 [................]
      0030: 07 00 00 00 aa 00 00 00 10 01 02 00 09 00 00 00 [................]
      0040: b2 00 00 00 12 01 03 00 01 00 00 00 01 00 00 00 [................]
      [snip 21812 bytes]
```

The same offset handling was also removed from the JPEG XL coder on file read it would seem.

On JPEG XL write, the erroneously prepended 2 bytes (why 2?) leads to a gibberish Exif box:

```
  | EXIF (SubDirectory) -->
  | - Tag 'Exif' (21890 bytes):
  |     003b: 00 00 45 78 69 66 00 00 49 49 2a 00 08 00 00 00 [..Exif..II*.....]
  |     004b: 0d 00 00 01 03 00 01 00 00 00 00 10 00 00 01 01 [................]
  |     005b: 03 00 01 00 00 00 00 0c 00 00 0f 01 02 00 07 00 [................]
  |     006b: 00 00 aa 00 00 00 10 01 02 00 09 00 00 00 b2 00 [................]
  |     007b: 00 00 12 01 03 00 01 00 00 00 01 00 00 00 1a 01 [................]
  |     [snip 21810 bytes]
  | + [TIFF directory]
  | Warning = Unrecognized EXIF box
```

Please reopen the issue.

**Comment by urban-warrior** [comment] 2022-12-26 13:38
Try the latest patch @ https://github.com/ImageMagick/ImageMagick/commit/21da4fc514acca9687df8a62b90ecf56742d8c98.

**Comment by kmilos** [comment] 2022-12-29 09:26
@urban-warrior Just tried 56: while it does improve on that particular sample with offset 10, it fails on another sample w/ offset 6 (attached), so the code is not general, [as I noted already.](https://github.com/ImageMagick/ImageMagick/commit/21da4fc514acca9687df8a62b90ecf56742d8c98#r94312251).

[IMG_20200731_210636067.zip](https://github.com/ImageMagick/ImageMagick/files/10318589/IMG_20200731_210636067.zip)

@dlemstra already implemented the correct offset parsing some time ago, so not sure why it was necessary to regress...

Also, it needs to be handled the same for JXLs on read, not only HEIFs, they share the same Exif box specification: https://github.com/libjxl/libjxl/issues/357#issuecomment-1131567595

**Comment by urban-warrior** [comment] 2022-12-29 12:34
We had some use cases that failed if we honored the TIFF offset. Its often the case where we fix one use case just to break another.  We will revisit our use cases, perhaps some of the HEIC images we have include non-conformant EXIF profiles.  If we toss them, we might settle on a robust patch that honors the TIFF offset.  Look for another patch, perhaps within the next few days.

**Comment by kmilos** [comment] 2022-12-29 12:40
> We had some use cases that failed if we honored the TIFF offset.

Please share, and I can also take look w/ exiftool and exiv2.

> We will revisit our use cases, perhaps some of the HEIC images we have include non-conformant EXIF profiles.

None of the samples shared here and in the related issues are non-conformant, and have perfectly valid Exif boxes with correct offsets.

The way I understand it, the current code in heif.c and jxl.c simply does not implement the Exif box spec linked above, i.e. offset is blatantly ignored (or assumed to be some fixed value: 4 in heif.c, 0 in jxl.c).

**Comment by urban-warrior** [comment] 2022-12-29 14:43
Some of my samples come from other sources.   We'll need some time to review the issue and will report back here.

**Comment by urban-warrior** [comment] 2022-12-29 20:04
See the latest commits for a fix for the issue.  We'll do some more testing and once we  confirme the Exif profiles are being read and written properly, we'll schedule a new release.

**Comment by kmilos** [comment] 2022-12-29 20:17
Thanks. The HEIF side now looks up to spec (aside from the completely unnecessary `Exif\0\0` on writing), but the JXL one is utterly confusing me still. They really ought to be identical...

**Comment by urban-warrior** [comment] 2022-12-30 17:18
Removed the spurious Exif namespace from the HEIC coder as you suggested.    We're clueless why dropping 2 bytes from the Exif profile is required by JXL, but that is what produces expected results.

**Closed** 2022-12-30 17:19 UTC

**Comment by kmilos** [comment] 2023-01-03 09:06
@urban-warrior @dlemstra Please reopen again, this is not functioning correctly just yet. I just tested 57, and get this for `magick 883089f0-80e4-45ea-89f9-50213c25ffbb.heic foo.jxl`:
```
  | EXIF (SubDirectory) -->
  | - Tag 'Exif' (21886 bytes):
  |     003b: 69 66 00 00 49 49 2a 00 08 00 00 00 0d 00 00 01 [if..II*.........]
```

The first 4 bytes (offset) are not valid, they should be 0.

It is as if you're adding `Exif\0\0` internally to the payload read by the HEIF coder, then just chopping off those 2 fixed "magic" bytes indiscriminately and writing that as JPEG XL payload so those 6 bytes of unnecessary APP1 prefix become any 4 bytes to line up with the offset bytes. That is not correct and not what the HEIF/JPEG XL spec for the Exif box mandates. Please revisit your APP1 `Exif\0\0` internal handling for all the coders, it is obviously creating a lot of confusion here.

For example, the PNG conversion is correct; the `Exif\0\0` does not appear and the eXIF chunk payload is clean as expected:
```
  Warning = [minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers)
PNG eXIf (21882 bytes):
    c0bcc9: 49 49 2a 00 08 00 00 00 0d 00 00 01 03 00 01 00 [II*.............]
```

**Comment by kmilos** [comment] 2023-01-03 10:21
Furthermore, it would seem [the equivalent check for and the removal of the `Exif\0\0` prefix is still missing in the HEIF coder on write (there is a risk the prefix is there coming e.g. from a JPEG file, but fixed offset of 0 is assumed)](https://github.com/ImageMagick/ImageMagick/blob/main/coders/heic.c#L860-L882), but I haven't been able to check as the Windows package lists HEIF as read-only...

**Comment by kmilos** [comment] 2023-01-03 10:55
[Ok, I found the source of confusion: IM always adds the `Exif\0\0` prefix internally](https://github.com/ImageMagick/ImageMagick/blob/abf01f32c001bc32b450160a29ea51c8613d73ab/MagickCore/profile.c#L1892-L1917) (as if the Exif buffer w/o the prefix is "corrupt", which is the source of misunderstanding; the prefix is JPEG/JFIF specific, and is now a burden on all other formats).

So for HEIF/JPEG XL **_write_** one has a choice: check and remove the 6-byte prefix (like done on PNG write) and use w/ 4-byte offset of 0, or use the payload as is, but use the fixed 4-byte offset of 6.

**Comment by kmilos** [comment] 2023-01-03 13:15
See https://github.com/ImageMagick/ImageMagick/pull/5929 for proposed writing fixes.

I'd still like to understand the 2 mystery bytes for JPEG XL read...

**Comment by AngelaDMerkel** [comment] 2024-01-17 13:10
This issue has been closed, but I still experience significant issues with metadata handling when converting from TIFF to JXL when using 7.1.1-26. 
The problem arises, it seems, because of how TIFF handles its specialised metadata blocks:
```
Unknown field with tag 34152 (0x8568) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
```

**Comment by urban-warrior** [comment] 2024-01-17 20:53
The warning is thrown by the libtiff delegate library.  It's warning you that there is a proprietary metadata tag that it does not understand so it simply ignores it.

**Comment by AngelaDMerkel** [comment] 2024-01-18 13:56
It seems to ignore significant amounts of the available metadata. Using exiftool it's possible to transfer nearly all the data which is relevant over, but using exiftool rather than having it handled integrally is a little bit more cumbersome than ideal

**Comment by urban-warrior** [comment] 2024-01-18 15:29
The ImageMagick team suggests using `exiftool` to manage EXIF profiles. ImageMagick will read the EXIF profile, make updates to one or two fields, and then rewrite it. Unfortunately, our team is unable to dedicate time to ensuring comprehensive EXIF support in ImageMagick. If you have specific needs, we encourage you to post a request on the discussion forum and tag it as "up for grabs." This way, there's a chance that someone from the user community might step in and contribute a pull request.
