### ISSUE TITLE
ImageMagick fails to convert to PDF with "negative or zero image size @ error/resize.c/ResizeImage/3743" error

### ISSUE THREAD

**Issue by atlantos** [ImageMagick/ImageMagick#6272] opened 2023-04-21 17:46 UTC
### ImageMagick version

7.1.1-7

### Operating system

MacOS

### Operating system, version and so on

macOS 13.3.1

### Description

ImageMagick fails to convert to PDF with `negative or zero image size '1.pdf' @ error/resize.c/ResizeImage/3743.` error. The error appears in the latest ImageMagick release 7.1.1-7.

Related bug report https://github.com/NixOS/nixpkgs/pull/227241

### Steps to Reproduce

```
% convert -version                       
Version: ImageMagick 7.1.1-7 Q16-HDRI aarch64 21117 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0) 
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib
Compiler: gcc (4.2)
```

```
% convert -verbose  1.png 1.pdf      
1.png PNG 964x136 964x136+0+0 8-bit TrueColorAlpha sRGB 17913B 0.000u 0:00.003
1.png=>1.pdf PNG 964x136 964x136+0+0 8-bit sRGB 15205B 0.020u 0:00.015
convert: negative or zero image size `1.pdf' @ error/resize.c/ResizeImage/3743.
```

```
% convert -debug ALL 1.png 1.pdf         
2023-04-21T17:39:55+00:00 0:00.001 0.000u 7.1.1 Configure convert[51405]: utility.c/ExpandFilenames/975/Configure
  Command line: convert {-debug} {ALL} {1.png} {1.pdf}
2023-04-21T17:39:55+00:00 0:00.001 0.000u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Module; rights=Unrecognized; pattern="PNG" ...
2023-04-21T17:39:55+00:00 0:00.001 0.000u 7.1.1 Module convert[51405]: module.c/OpenModule/1277/Module
  Searching for module "PNG" using filename "png.la"
2023-04-21T17:39:55+00:00 0:00.001 0.000u 7.1.1 Module convert[51405]: module.c/GetMagickModulePath/548/Module
  Searching for coder module file "png.la" ...
2023-04-21T17:39:55+00:00 0:00.001 0.000u 7.1.1 Module convert[51405]: module.c/OpenModule/1286/Module
  Opening module at path "/opt/homebrew/Cellar/imagemagick/7.1.1-7/lib/ImageMagick/modules-Q16HDRI/coders/png.la"
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Module convert[51405]: module.c/OpenModule/1313/Module
  Method "RegisterPNGImage" in module "PNG" at address 0x10083aa8c
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Module convert[51405]: module.c/OpenModule/1327/Module
  Method "UnregisterPNGImage" in module "PNG" at address 0x100852ae8
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="1.png" ...
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Blob convert[51405]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Cache convert[51405]: cache.c/DestroyPixelCache/1065/Cache
  destroy 
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="1.png" ...
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Blob convert[51405]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Cache convert[51405]: cache.c/DestroyPixelCache/1065/Cache
  destroy 
2023-04-21T17:39:55+00:00 0:00.003 0.000u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Coder; rights=Read; pattern="PNG" ...
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadPNGImage/3952/Coder
  Enter ReadPNGImage()
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="1.png" ...
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Blob convert[51405]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2148/Coder
    Enter ReadOnePNGImage()
    IM version     = 7.1.1-7
    Libpng version = 1.6.39
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2158/Coder
      Zlib version   = 1.2.11
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2170/Coder
      Before reading:
      image->alpha_trait=0
      image->rendering_intent=2
      image->colorspace=23
      image->gamma=0.454545
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/read_user_chunk_callback/1858/Coder
      read_user_chunk: found iTXt chunk
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/read_user_chunk_callback/1858/Coder
      read_user_chunk: found iDOT chunk
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2465/Coder
      PNG width: 964, height: 136
    PNG color_type: 6, bit_depth: 8
    PNG compression_method: 0
    PNG interlace_method: 0, filter_method: 0
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2481/Coder
      Found PNG iCCP chunk.
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2549/Coder
      Reading PNG iCCP chunk.
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2616/Coder
      Got 4032-byte ICC profile not recognized as sRGB
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/2753/Coder
      Reading PNG pHYs chunk: xres: 5669, yres: 5669, units: 1.
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3013/Coder
      image->gamma=0.454545
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3041/Coder
      image->colorspace=23
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3195/Coder
      Reading PNG IDAT chunk(s)
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Pixel convert[51405]: pixel.c/SetPixelChannelMask/6305/Pixel
  1.png[07ffffff]
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6189/Pixel
  1.png[07ffffff]
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    0: red (update)
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    1: green (update)
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    2: blue (update)
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Area: 131104B/0B/64GiB
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Memory: 1.50037MiB/1.50037MiB/16GiB
2023-04-21T17:39:55+00:00 0:00.004 0.000u 7.1.1 Cache convert[51405]: cache.c/OpenPixelCache/3803/Cache
  open 1.png[0] (Heap Memory, 964x136x3 1.50037MiB)
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3221/Coder
      Converting PNG pixels to pixel packets
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/SetPixelChannelMask/6305/Pixel
  1.png[07ffffff]
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6189/Pixel
  1.png[07ffffff]
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    0: red (update,blend)
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    1: green (update,blend)
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    2: blue (update,blend)
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    3: alpha (update)
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Area: 131104B/0B/64GiB
2023-04-21T17:39:55+00:00 0:00.005 0.000u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Memory: 2.00049MiB/3.50085MiB/16GiB
2023-04-21T17:39:55+00:00 0:00.006 0.000u 7.1.1 Cache convert[51405]: cache.c/ClonePixelCacheRepository/860/Cache
  Memory => Memory
2023-04-21T17:39:55+00:00 0:00.006 0.000u 7.1.1 Resource convert[51405]: resource.c/RelinquishMagickResource/1074/Resource
  Memory: 1.50037MiB/2.00049MiB/16GiB
2023-04-21T17:39:55+00:00 0:00.006 0.000u 7.1.1 Cache convert[51405]: cache.c/OpenPixelCache/3803/Cache
  open 1.png[0] (Heap Memory, 964x136x4 2.00049MiB)
2023-04-21T17:39:55+00:00 0:00.006 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3296/Coder
      Looking for cheap transparent pixel
2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3546/Coder
      No transparent pixel was found
2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3559/Coder
    image->storage_class=1

2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadOnePNGImage/3905/Coder
    exit ReadOnePNGImage()
2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadPNGImage/4028/Coder
    page.w: 0, page.h: 0,page.x: 0, page.y: 0.
2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadPNGImage/4032/Coder
    image->colorspace: 23
2023-04-21T17:39:55+00:00 0:00.008 0.000u 7.1.1 Coder convert[51405]: png.c/ReadPNGImage/4037/Coder
  exit ReadPNGImage()
2023-04-21T17:39:55+00:00 0:00.008 0.010u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Module; rights=Unrecognized; pattern="PDF" ...
2023-04-21T17:39:55+00:00 0:00.008 0.010u 7.1.1 Module convert[51405]: module.c/OpenModule/1277/Module
  Searching for module "PDF" using filename "pdf.la"
2023-04-21T17:39:55+00:00 0:00.008 0.010u 7.1.1 Module convert[51405]: module.c/GetMagickModulePath/548/Module
  Searching for coder module file "pdf.la" ...
2023-04-21T17:39:55+00:00 0:00.008 0.010u 7.1.1 Module convert[51405]: module.c/OpenModule/1286/Module
  Opening module at path "/opt/homebrew/Cellar/imagemagick/7.1.1-7/lib/ImageMagick/modules-Q16HDRI/coders/pdf.la"
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Module convert[51405]: module.c/OpenModule/1313/Module
  Method "RegisterPDFImage" in module "PDF" at address 0x10080703c
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Module convert[51405]: module.c/OpenModule/1327/Module
  Method "UnregisterPDFImage" in module "PDF" at address 0x10080e120
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Write; pattern="1.pdf" ...
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Coder; rights=Write; pattern="PDF" ...
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Policy convert[51405]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Write; pattern="1.pdf" ...
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Pixel convert[51405]: pixel.c/SetPixelChannelMask/6305/Pixel
  1.pdf[07ffffff]
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6189/Pixel
  1.pdf[07ffffff]
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    0: red (update)
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    1: green (update)
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Pixel convert[51405]: pixel.c/LogPixelChannels/6286/Pixel
    2: blue (update)
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Area: 131104B/0B/64GiB
2023-04-21T17:39:55+00:00 0:00.016 0.020u 7.1.1 Resource convert[51405]: resource.c/AcquireMagickResource/390/Resource
  Memory: 1.50037MiB/3.50085MiB/16GiB
2023-04-21T17:39:55+00:00 0:00.017 0.020u 7.1.1 Cache convert[51405]: cache.c/ClonePixelCacheRepository/860/Cache
  Memory => Memory
2023-04-21T17:39:55+00:00 0:00.017 0.020u 7.1.1 Resource convert[51405]: resource.c/RelinquishMagickResource/1074/Resource
  Memory: 2.00049MiB/1.50037MiB/16GiB
2023-04-21T17:39:55+00:00 0:00.017 0.020u 7.1.1 Cache convert[51405]: cache.c/OpenPixelCache/3803/Cache
  open 1.pdf[0] (Heap Memory, 964x136x3 1.50037MiB)
2023-04-21T17:39:55+00:00 0:00.023 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/ImageMagick-7/locale.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/lib/ImageMagick//config-Q16HDRI/locale.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/etc/ImageMagick-7/locale.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/doc/ImageMagick-7/locale.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/Users/testuser/.config/ImageMagick/locale.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Configure convert[51405]: locale.c/LoadLocaleCache/1181/Configure
  Loading locale configure file "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/ImageMagick-7/locale.xml" ...
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/ImageMagick-7/english.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/lib/ImageMagick//config-Q16HDRI/english.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/etc/ImageMagick-7/english.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/doc/ImageMagick-7/english.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Locale convert[51405]: locale.c/GetLocaleOptions/824/Locale
  Searching for locale file: "/Users/testuser/.config/ImageMagick/english.xml"
2023-04-21T17:39:55+00:00 0:00.024 0.020u 7.1.1 Configure convert[51405]: locale.c/LoadLocaleCache/1181/Configure
  Loading locale configure file "/opt/homebrew/Cellar/imagemagick/7.1.1-7/share/ImageMagick-7/english.xml" ...
2023-04-21T17:39:55+00:00 0:00.025 0.020u 7.1.1 Exception convert[51405]: resize.c/ResizeImage/3743/Exception
  negative or zero image size `1.pdf'
2023-04-21T17:39:55+00:00 0:00.025 0.020u 7.1.1 Cache convert[51405]: cache.c/DestroyPixelCache/1065/Cache
  destroy 1.pdf[0]
2023-04-21T17:39:55+00:00 0:00.025 0.020u 7.1.1 Resource convert[51405]: resource.c/RelinquishMagickResource/1074/Resource
  Memory: 1.50037MiB/0B/16GiB
convert: negative or zero image size `1.pdf' @ error/resize.c/ResizeImage/3743.
```

**Comment by dlemstra** [comment] 2023-04-21 18:06
Duplicate of #6263

**Closed by dlemstra** 2023-04-21 18:06 UTC
