### ISSUE TITLE
gradient behavior

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#6762] opened 2023-10-06 08:54 UTC
### ImageMagick version

7.1.1-19

### Operating system

Linux

### Operating system, version and so on

SUSE LInux, Tumbleweed

### Description

A while ago I have reported
https://github.com/ImageMagick/ImageMagick/issues/4790
this was then fixed by
https://github.com/ImageMagick/ImageMagick/commit/b51707c08f3dee192d464d38fc507c86051e62e6
but reverted by
https://github.com/ImageMagick/ImageMagick/commit/503333f87ae676f5e327d83e10def04b3ecee5ab

I have checked that the behavior is now the same as 7.0.9-26. I guess a clear statement that this behavior just changed and is expected would be enough for me.

Thank you

### Steps to Reproduce

See #4790 .

**Comment by urban-warrior** [comment] 2023-10-07 00:32
Often when we fix a "bug", it has unintended side-effects such as this one.  In those cases we need to revert the patch and restore the previous behavior.    With the fix, we got reports of broken scripts and unexpected behavior and given your issue can be fixed by explicitly setting the stop color, we decided to revert the patch.

**Closed** 2023-10-07 16:09 UTC

**Comment by pgajdos** [comment] 2023-10-09 07:58
Never mind, so I take it as a clear statement that this behavior is expected.

Thanks!
