### ISSUE TITLE
Wrong changelog entry in 7.1.0-14

### ISSUE THREAD

**Issue by marillat** [ImageMagick/ImageMagick#4487] opened 2021-11-16 13:28 UTC
### ImageMagick version

7.1.0-14

### Operating system

Linux

### Operating system, version and so on

Debian sid

### Description

Changelog  for 7.1.0-14  talk about 7.1.0-15
Which is the latest release -14 or -15 ?
```
021-11-13  7.1.0-15  <quetzlzacatenango@image...>
  * Release ImageMagick version 7.1.0-15 GIT revision 19349:2ba5cdf42:20211114

2021-11-13  7.1.0-15  <quetzlzacatenango@image...>
  * Support '#' modifier to aspect ratio geometry (e.g., 3:2#).

2021-11-11  7.1.0-15  Dirk Lemstra <dirk@lem.....org>
  * The profile of a PSD file will no longer be copied to all the images, only
    the first returned image will contain the profile. To re-enable the old
    behavior add -define psd:replicate-profile=true.
```

### Steps to Reproduce

Nothing, Read the Changelog.

**Comment by dlemstra** [comment] 2021-11-16 13:44
Duplicate of #4479

**Closed by dlemstra** 2021-11-16 13:44 UTC
