### ISSUE TITLE
Conversion from webp starts to be broken after 7.1.0-58

### ISSUE THREAD

**Issue by laggykiller** [ImageMagick/ImageMagick#6055] opened 2023-02-11 22:59 UTC
### ImageMagick version

7.1.0-58

### Operating system

Other (enter below)

### Operating system, version and so on

At least in Windows (Portable) and Linux (AppImage & Arch Linux)

### Description

Conversion of webp file to any video format produces glitch after 7.1.0-58. The last known good version is 7.1.0-57

For example: `magick test.webp test.webm`

Tested with converting to webm and mp4, both are broken.

### Steps to Reproduce

Seems to affect all webp files.

Converting to any video format is broken.

`magick test.webp test.webm`

### Images

Input (webp)
[test.webp.zip](https://github.com/ImageMagick/ImageMagick/files/10714887/test.webp.zip)

Output (webm)
[test.webm](https://user-images.githubusercontent.com/61652821/218284655-2293f34f-6ed1-47c4-969b-56e56795a4be.webm)

**Comment by urban-warrior** [comment] 2023-02-12 15:50
Try this command:

```
magick test.webp -coalesce test.webm
```

Previously, the video coder automatically coalesced the image sequence.  However, that caused issues with other use cases.

**Comment by laggykiller** [comment] 2023-02-12 16:50
I would expect imagemagick would automagically sort that out and not have to supply more flags, but I confirm that `-coalesce` makes the glitch goes away.

**Comment by urban-warrior** [comment] 2023-02-12 17:12
There are certain scenarios where the requirement is to read a video sequence and convert it to another format without any modifications. However, in your case, the goal is to merge the sequence. Enforcing the merging process would prevent the first scenario from being achieved. Allowing the user to choose whether to enable merging or not through the `-coalesce` command line option accommodates both scenarios.

**Comment by dlemstra** [comment] 2023-02-12 17:19
Closing this as duplicate of #6041

**Closed by dlemstra** 2023-02-12 17:19 UTC
