### ISSUE TITLE
Processing specific SVG file hangs ImageMagick forever, possible to leverage DoS

### ISSUE THREAD

**Issue by jkytomaki** [ImageMagick/ImageMagick#7562] opened 2024-08-16 10:39 UTC
### ImageMagick version

7.1.1-36

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

Similarly to issue https://github.com/ImageMagick/ImageMagick/issues/4626, trying to convert this specific SVG file to PNG, hangs ImageMagick, consuming 100% of a CPU core, never finishing the conversion.

### Steps to Reproduce

Using the attached sample SVG, run

```
magick convert  -flatten broken-image.svg out.png
```
The process should take 100% of a CPU core and never exit.

### Images

![broken-image](https://github.com/user-attachments/assets/e928dbd1-e95b-49d8-81e6-3ac41c33047f)

**Comment by dlemstra** [comment] 2024-08-16 11:48
I am unable to reproduce this. Does it also fail when you use the proper command? `magick broken-image.svg -flatten out.png`? And do you have inkscape installed?

**Comment by snibgo** [comment] 2024-08-16 12:29
I confirm the problem, with IM v7.1.1-20 on Windows 11, using MSVG:
```
magick MSVG:radio.svg x.png
```
... where radio.svg is the supplied SVG file.

**Comment by jkytomaki** [comment] 2024-08-16 12:32
> I am unable to reproduce this. Does it also fail when you use the proper command? `magick broken-image.svg -flatten out.png`? And do you have inkscape installed?

It happens also with command
```
magick broken-image.svg -flatten out.png
```

I'm using the ImageMagick AppImage binary version 7.1.1-36 Q16-HDRI x86_64 downloaded from the ImageMagick site on my Ubuntu 22.04. I don't have inkscape installed.

**Comment by urban-warrior** [comment] 2024-08-17 17:19
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Closed** 2024-08-17 18:47 UTC
