### ISSUE TITLE
[jxl] Error converting DNG to JXL

### ISSUE THREAD

**Issue by lp55** [ImageMagick/ImageMagick#3415] opened 2021-03-18 12:27 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3

### Operating system

Windows

### Operating system, version and so on

Windows 10 (latest patches)

### Description

I tried to converting several diferent DNG files, and got the following error:

image.DNG DNG 4936x3272 4960x3300+8+20 16-bit sRGB 14.1151MiB 2.672u 0:02.708
D:\a\ImageMagick\ImageMagick\ImageMagick-Windows\jpeg-xl\lib\jxl\fields.cc:676: JXL_ABORT: AllDefault should never fail

### Steps to Reproduce

I ran the following command:

convert -verbose -quality 100 -compress lossless image.DNG jxl/image.jxl

But even with any of the quality or the compress options the error was the same

As this error occured on any DNG file I had, and not any specific image file, I won't upload anything, unless you are unable to reproduce the error.

**Comment by dlemstra** [comment] 2021-03-18 12:49
Can you reproduce this issue with the tooling of the jxl library? Or do they not support reading from DNG? And it would be helpful to include the file that can be used to reproduce this.

**Comment by nar2634** [comment] 2021-03-18 13:16
@dlemstra 

I can also reproduce this issue.

`convert image.dng image.jxl`, the errors are:
```
/usr/src/packages/BUILD/libjpeg-xl/src/jpeg-xl/lib/jxl/image_metadata.cc:65: JXL_FAILURE: Invalid bits_per_sample: 32
/usr/src/packages/BUILD/libjpeg-xl/src/jpeg-xl/lib/jxl/fields.cc:677: JXL_ABORT: AllDefault should never fail
```

`cjxl` does not support DNG as input.
It only accepts PNG, APNG, GIF, JPEG, EXR, PPM, PFM, and PGX (according to `cjxl -h -v`).

The DNGs I used for reproducing the issue are produced by [FreeDcam](https://github.com/KillerInk/FreeDcam) (FOSS Android camera app).

**Comment by lp55** [comment] 2021-03-18 14:30
@dlemstra 

As @nar2634 said, the jxl library doesn't support DNG. My idea is to convert my lossless raws (in DNG format) to lossless jxl to save space (in theory) while keeping all the image information.

One thing @nar2634 example complains about invalid bits per sample (32). My images were 16. If jxl library doesn't support 32 bit images, it would be nice for ImageMagick to convert to 16 or at least warn of this issue when processing 32 bit images, until the jxl library adds support for this bit format.

**Comment by dlemstra** [comment] 2021-03-18 21:18
Please attach an image I can use to reproduce the issue. Please both upload an image @nar2634 and @lp55 that I can use to reproduce your issue. With a random DNG file that I have on my machine I am unable to reproduce your issue. You might need to zip the file to upload it here.

**Comment by nar2634** [comment] 2021-03-19 02:37
https://fileupload.ggc-project.de/download/eedad785efc1238d/#GWS3WimgAQ2KUtguImKYBw

(Link expires after 1 download or 24 hours)

**Comment by dlemstra** [comment] 2021-03-19 09:01
Please zip the DNG file @nar2634  and upload it in a new message. Someone already decided that they should download the file.

**Comment by dlemstra** [comment] 2021-03-20 11:07
It seems that @nar2634 deleted their account and their messages are gone but I did fix the 32-bit initalization. This will be resolved in the next release. Can you please upload your image @lp55 or email me a link if you don't want to share it publicly.

**Comment by lp55** [comment] 2021-03-22 10:50
I attached a random image (it has light issues but it's not a problem to test this issue)

[img.zip](https://github.com/ImageMagick/ImageMagick/files/6181482/img.zip)

**Comment by dlemstra** [comment] 2021-04-17 21:59
I can reproduce your issue with the latest version of ImageMagick @lp55. Will need to test if upgrading the library will resolve the issue.

**Comment by dlemstra** [comment] 2021-04-24 12:23
I just upgraded jpeg-xl in ImageMagick for Windows and I no longer get the `JXL_ABORT` error message. This should be resolved in the next release of ImageMagick.

**Closed by dlemstra** 2021-04-24 12:23 UTC
