### ISSUE TITLE
Convert to AVIF with limited memory doesn't work

### ISSUE THREAD

**Issue by Petah** [ImageMagick/ImageMagick#4486] opened 2021-11-16 04:52 UTC
### ImageMagick version

ImageMagick 7.1.0-14 Q16 x86_64 2021-10-28

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04.6 LTS

### Description

Trying to convert a JPG to AVIF with limited RAM and using disk cache causes OOM an kills ImageMagick.

### Steps to Reproduce

Using a clean install of Ubuntu (with 2GB RAM) compile ImageMagick (using IMEI)
Download sample image https://www.learningcontainer.com/wp-content/uploads/2020/07/Large-Sample-Image-download-for-Testing.jpg
Edit policy.xml with
```
<?xml version="1.0" encoding="UTF-8"?>
<policymap>
    <policy domain="resource" name="temporary-path" value="/tmp"/>
    <policy domain="resource" name="memory" value="1MiB"/>
    <policy domain="resource" name="map" value="1MiB"/>
    <policy domain="resource" name="disk" value="32GiB"/>
</policymap>
```
Run `convert sample.jpg test.avif`
Output is simply `Killed`

There is some more details including debug output, memory output etc here: https://github.com/ImageMagick/ImageMagick/discussions/4473

**Comment by fmw42** [comment] 2021-11-16 04:59
Unless you have a symbolic link set up, I suggest using magick not convert when on IM 7.

**Comment by Petah** [comment] 2021-11-16 05:13
Hi, yea it does set the symlink for convert, also tried with `magick` with the same result.

![image](https://user-images.githubusercontent.com/134799/141924867-7813718c-663e-4c7e-a515-32eac67254e1.png)

**Comment by fmw42** [comment] 2021-11-16 05:47
Do you have OpenMP enabled?  You might try compiling without or `convert -limit thread 1 .... ` Probably won't help, but worth a try.

**Comment by fmw42** [comment] 2021-11-16 05:48
You could also try recompiling as Q8 to save RAM

**Comment by dlemstra** [comment] 2021-11-16 07:06
Duplicate of #4473

**Closed by dlemstra** 2021-11-16 07:06 UTC

**Comment by Petah** [comment] 2021-11-16 07:17
I have tried limiting threads to 1 before, but I tried again anyway (compiling using `--without-threads`, and added `<policy domain="resource" name="thread" value="1"/>` to the policy.xml).

I also added `--with-quantum-depth=8` which I assume is what you mean by Q8.

However still had the same result. But I don't really think the issue is trying to fit the conversion within the amount of RAM the system, after all I can always add more RAM or swap. Its more that specifically the AVIF encoder doesn't (maybe cant?) use the disk cache.

![image](https://user-images.githubusercontent.com/134799/141938569-5b34f860-0f4c-46fd-a6fe-3e3864d9c2d4.png)

**Comment by Petah** [comment] 2021-11-16 08:34
@dlemstra not sure if I did something wrong, #4473 was a discussion, this was an issue.

**Comment by dlemstra** [comment] 2021-11-16 09:38
There is no need to talk about the same thing in both a discussions and an issue. So please continue this in the discussion.

**Comment by Petah** [comment] 2021-11-16 11:49
@dlemstra sorry I thought based on the discussions this would be regarded as a bug.
