### ISSUE TITLE
Incorrect  json output with image having a clipping path embedded

### ISSUE THREAD

**Issue by ptitpix** [ImageMagick/ImageMagick#149] opened 2016-03-12 10:42 UTC
Hello,
When a jpg has an embedded clipping path, the json produced by `convert image.jpg json:` is invalid : 
`"clipping path" : { "<svg ....." }`
It should be : 
`"clipping path" : "<svg ...."`

**Comment by mikayla-grace** [comment] 2016-03-12 16:22
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ptitpix** [comment] 2016-03-13 19:29
Do you plan to fix it in the ImageMagick-6 branch ? I've made a pull request to do so if it helps.

**Comment by dlemstra** [comment] 2016-03-13 20:00
I just cherry picked your commit in the IM6 branch. It should show up on github later today.

**Comment by blop** [comment] 2017-03-10 14:22
Seems the patch is not working on all platforms.

It's still not working on Version: ImageMagick 7.0.5-0 Q16 x86_64 2017-02-21 on MacOS (from brew).
Linux version seems not affected.

Seems this case should be reopened.

**Comment by dlemstra** [comment] 2017-03-11 04:06
Can you specify where our json output is invalid?

**Comment by blop** [comment] 2017-03-11 07:30
Same as above.

With this command : 
`convert Twist504.jpg json:`

I get : 
`    "clipping path": {
"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"742\" height=\"412\">\n<g>\n<path .....\"/>\n</g>\n</svg>\n"
    },
`

Those extra {} are not present when executing the same command, same file under linux.

**Comment by dlemstra** [comment] 2017-03-11 08:36
It appears our IM7 code still has this broken. Thanks for reporting this.

**Comment by blop** [comment] 2017-03-11 08:41
Oh yes, it seems related to version 7.

Also, I get some strange invalid iptc records in the JSON : 
`      "iptc": {
      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      City[1,90]: ["0x00000000: 254700                                        -%"],      unknown[2,0]: [null],        "length": "63"
      },
`

And, btw IM7 gives an array as root object, IM6 the object inside, but I guess that's a normal change from 6 to 7?

**Comment by pbsladek** [comment] 2017-05-03 21:23
I have the same issue with iptc
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-04-25 http://www.imagemagick.org
```
{
	"iptc": {
		Keyword[2, 25]: ["Lights"],
		Keyword[2, 25]: ["Tea lights"],
		Keyword[2, 25]: ["candle"],
		Keyword[2, 25]: ["zen"],
		unknown[2, 0]: [null],
		"length": "52"
	}
}

**Comment by dlemstra** [comment] 2017-08-22 18:20
@pbsladek Do you have an image available that we can use to reproduce the issue?

**Comment by pbsladek** [comment] 2017-08-22 18:25
@dlemstra I'll see if i can create one real quick. Only have customer ones at the moment.

**Comment by pbsladek** [comment] 2017-08-22 20:27
@dlemstra https://gist.github.com/pbsladek/52698817587e5e218369800785f2d103/

**Comment by rrozek** [comment] 2017-09-21 11:03
i was just about to report that clipping path issue but i see its already there. I would add one more case. JSON file is broken when dealing with multipage images (tif in my case)
I could possibly fix that if you could point me to some code chunk in your sources ;)
test file: http://www.filedropper.com/3imagetif
issued command:
`magick convert 3imageTif.tif[1x1+0+0] json:`
json result:
`
[{
  "image": {
    "name": null,
    "baseName": "3imageTif.tif",
    "format": "TIFF",
    "formatDescription": "TIFF",
    "mimeType": "image/tiff",
    "class": "DirectClass",
    "geometry": {
      "width": 1,
      "height": 1,
      "x": 0,
      "y": 0
    },
    "resolution": {
      "x": 300,
      "y": 300
    },
    "printSize": {
      "x": 0.0033333333333333335,
      "y": 0.0033333333333333335
    },
    "units": "PixelsPerInch",
    "type": "Bilevel",
    "baseType": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 1,
    "baseDepth": 8,
    "channelDepth": {
      "gray": 1
    },
    "pixels": 3,
    "channelStatistics": {
      "Gray": {
        "min": "255",
        "max": "255",
        "mean": "255",
        "standardDeviation": "0",
        "kurtosis": "-3",
        "skewness": "0"
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "matteColor": "#BDBDBD",
    "backgroundColor": "#FFFFFF",
    "borderColor": "#DFDFDF",
    "transparentColor": "#00000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 991,
      "height": 276,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "iterations": 0,
    "scene": 0
    "scenes": 3
    "compression": "None",
    "orientation": "TopLeft",
    "properties": {
      "date:create": "2017-09-21T12:52:22+02:00",
      "date:modify": "2017-09-21T12:52:22+02:00",
      "signature": "cc143326a2646c605ea66139d7b440df7cbde18c050f1f8cf4dd30f42cfe7123",
      "tiff:alpha": "unspecified",
      "tiff:endian": "lsb",
      "tiff:photometric": "RGB",
      "tiff:rows-per-strip": "69"
    },
    "tainted": true,
    "filesize": "0B",
    "numberPixels": "1",
    "pixelsPerSecond": "100B",
    "userTime": "0.016u",
    "elapsedTime": "0:01.010",
    "version": "C:\\Program Files (x86)\\ImageMagick-7.0.6-Q16\\\\index.html"
  }
}
,
[{
  "image": {
    "name": "json:",
    "baseName": "3imageTif.tif",
    "format": "TIFF",
    "formatDescription": "TIFF",
    "mimeType": "image/tiff",
    "class": "DirectClass",
    "geometry": {
      "width": 1,
      "height": 1,
      "x": 0,
      "y": 0
    },
    "resolution": {
      "x": 300,
      "y": 300
    },
    "printSize": {
      "x": 0.0033333333333333335,
      "y": 0.0033333333333333335
    },
    "units": "PixelsPerInch",
    "type": "Bilevel",
    "baseType": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 1,
    "baseDepth": 8,
    "channelDepth": {
      "gray": 1
    },
    "pixels": 3,
    "channelStatistics": {
      "Gray": {
        "min": "255",
        "max": "255",
        "mean": "255",
        "standardDeviation": "0",
        "kurtosis": "-3",
        "skewness": "0"
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "matteColor": "#BDBDBD",
    "backgroundColor": "#FFFFFF",
    "borderColor": "#DFDFDF",
    "transparentColor": "#00000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 3022,
      "height": 1488,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "iterations": 0,
    "scene": 1
    "scenes": 3
    "compression": "None",
    "orientation": "TopLeft",
    "properties": {
      "date:create": "2017-09-21T12:52:22+02:00",
      "date:modify": "2017-09-21T12:52:22+02:00",
      "signature": "cc143326a2646c605ea66139d7b440df7cbde18c050f1f8cf4dd30f42cfe7123",
      "tiff:alpha": "unspecified",
      "tiff:endian": "lsb",
      "tiff:photometric": "RGB",
      "tiff:rows-per-strip": "372"
    },
    "tainted": true,
    "filesize": "0B",
    "numberPixels": "1",
    "pixelsPerSecond": "20B",
    "userTime": "0.062u",
    "elapsedTime": "0:01.049",
    "version": "C:\\Program Files (x86)\\ImageMagick-7.0.6-Q16\\\\index.html"
  }
}
,
[{
  "image": {
    "name": "json:",
    "baseName": "3imageTif.tif",
    "format": "TIFF",
    "formatDescription": "TIFF",
    "mimeType": "image/tiff",
    "class": "DirectClass",
    "geometry": {
      "width": 1,
      "height": 1,
      "x": 0,
      "y": 0
    },
    "resolution": {
      "x": 300,
      "y": 300
    },
    "printSize": {
      "x": 0.0033333333333333335,
      "y": 0.0033333333333333335
    },
    "units": "PixelsPerInch",
    "type": "Bilevel",
    "baseType": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 1,
    "baseDepth": 8,
    "channelDepth": {
      "gray": 1
    },
    "pixels": 3,
    "channelStatistics": {
      "Gray": {
        "min": "255",
        "max": "255",
        "mean": "255",
        "standardDeviation": "0",
        "kurtosis": "-3",
        "skewness": "0"
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "matteColor": "#BDBDBD",
    "backgroundColor": "#FFFFFF",
    "borderColor": "#DFDFDF",
    "transparentColor": "#00000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 2992,
      "height": 1529,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "iterations": 0,
    "scene": 2
    "scenes": 3
    "compression": "None",
    "orientation": "TopLeft",
    "properties": {
      "date:create": "2017-09-21T12:52:22+02:00",
      "date:modify": "2017-09-21T12:52:22+02:00",
      "signature": "cc143326a2646c605ea66139d7b440df7cbde18c050f1f8cf4dd30f42cfe7123",
      "tiff:alpha": "unspecified",
      "tiff:endian": "lsb",
      "tiff:photometric": "RGB",
      "tiff:rows-per-strip": "382"
    },
    "tainted": true,
    "filesize": "0B",
    "numberPixels": "1",
    "pixelsPerSecond": "11B",
    "userTime": "0.094u",
    "elapsedTime": "0:01.090",
    "version": "C:\\Program Files (x86)\\ImageMagick-7.0.6-Q16\\\\index.html"
  }
}
]
`
errors in json format:
1. missing coma separators when dealing with 'scene' and 'scenes' properties in lines 79, 179, 279 (3 images)
2. there is like additional array envelope between separate images in json. Image #1 is defined fine with 
`["image": {}, (...)`
but next images are defined with extra array like
`["image": {}, [{"image": {}`
NOTE - missing close ']' bracket.

removing this extra opening array '[' bracket from before images #2 and #3 resolves all issues with JSON structure.

my imagemagick version:
`$ magick -version
Version: ImageMagick 7.0.6-3 Q16 x86 2017-07-24 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib
`

**Comment by dlemstra** [comment] 2017-09-21 11:26
Can you upgrade to the latest version and give it another try?

p.s. When you use `#1` you will link another unrelated issue.

**Comment by dlemstra** [comment] 2017-09-21 11:39
It appears these were still valid issues. This will be resolved in the next version of ImageMagick.

**Comment by rrozek** [comment] 2017-09-21 12:11
thank you for your quick research!

**Comment by dlemstra** [comment] 2017-09-21 15:07
@blop and @pbsladek I just pushed some changes to resolve the duplicate name issue with the iptc profile. I now get the following output:

```json
"iptc": {
  "Keyword[2,25]": ["Lights","Tea lights","candle","zen"],
  "Unknown[2,0]": [null],
  "length": "64"
}
```

I also applied a patch to make sure IM6 also returns an array. When the result contained more than 1 image you would get invalid output.

Can we now close this issue?

**Comment by pbsladek** [comment] 2017-09-21 16:21
@dlemstra Thanks! Looks good to me.
Tested with Version: ImageMagick 7.0.7-4 Q16 x86_64 2017-09-21
```json
"iptc": {
    "Keyword[2,25]": ["Lights","Tea lights","candle","zen"],
    "Unknown[2,0]": [null],
    "length": "64"
}
```

**Closed** 2017-09-21 19:20 UTC
Labels: bug

**Comment by rrozek** [comment] 2017-09-30 11:21
Hey Dirk!
I just downloaded new windows artifacts from current build. Your fixes are applied, however clipping path is still invalid in terms of json structure. Clipping path is added as an object and the actual clipping path description is recognized as a 'name' of a json property.
It looks like this:
`"clipping path": 
			"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"2000\" height=\"1282\">\n<g>\n<path fill-rule=\"evenodd\" style=\"fill:#000000;stroke:#000000;stroke-width:0;stroke-antialiasing:false\" d=\"\nM 173.243 975.336\nL 429.932 831.077\nL 979.138 523.052\nL 1176.87 413.724\nL 1497.96 235.895\nL 1823.58 50.3546\nC 1823.58 50.3546 1834.47 46.2718 1843.99 49.9009\nC 1853.51 53.5301 1866.67 59.4274 1879.82 74.8513\nC 1892.97 90.2753 1903.85 110.236 1905.22 115.226\nC 1906.58 120.216 1914.74 149.703 1913.83 158.322\nC 1912.93 166.941 1908.84 173.292 1905.22 178.282\nC 1901.59 183.272 1862.59 207.316 1858.05 210.038\nC 1853.51 212.759 1678 313.469 1678 313.469\nL 1377.78 487.668\nL 1058.05 674.116\nL 719.728 868.73\nL 156.463 1193.54\nC 156.463 1193.54 148.299 1198.98 143.311 1200.34\nC 138.322 1201.7 138.775 1203.97 130.159 1199.44\nC 121.542 1194.9 97.9592 1173.58 81.1793 1149.99\nC 64.3991 1126.4 37.6416 1068.79 53.0612 1043.84\nC 84.8073 1022.97 129.705 998.472 146.485 990.76\nC 163.265 983.048 173.243 975.336 173.243 975.336 Z\n\"/>\n</g>\n</svg>\n"
		},`

i think that valid json should look more like this:
`"clipping path": {
			"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"2000\" height=\"1282\">\n<g>\n<path fill-rule=\"evenodd\" style=\"fill:#000000;stroke:#000000;stroke-width:0;stroke-antialiasing:false\" d=\"\nM 173.243 975.336\nL 429.932 831.077\nL 979.138 523.052\nL 1176.87 413.724\nL 1497.96 235.895\nL 1823.58 50.3546\nC 1823.58 50.3546 1834.47 46.2718 1843.99 49.9009\nC 1853.51 53.5301 1866.67 59.4274 1879.82 74.8513\nC 1892.97 90.2753 1903.85 110.236 1905.22 115.226\nC 1906.58 120.216 1914.74 149.703 1913.83 158.322\nC 1912.93 166.941 1908.84 173.292 1905.22 178.282\nC 1901.59 183.272 1862.59 207.316 1858.05 210.038\nC 1853.51 212.759 1678 313.469 1678 313.469\nL 1377.78 487.668\nL 1058.05 674.116\nL 719.728 868.73\nL 156.463 1193.54\nC 156.463 1193.54 148.299 1198.98 143.311 1200.34\nC 138.322 1201.7 138.775 1203.97 130.159 1199.44\nC 121.542 1194.9 97.9592 1173.58 81.1793 1149.99\nC 64.3991 1126.4 37.6416 1068.79 53.0612 1043.84\nC 84.8073 1022.97 129.705 998.472 146.485 990.76\nC 163.265 983.048 173.243 975.336 173.243 975.336 Z\n\"/>\n</g>\n</svg>\n"
		,`

so just to drop 'object' envelope

**Comment by dlemstra** [comment] 2017-09-30 11:41
@rrozek Thanks for reporting this. I just pushed two fixes to resolve this in both IM6 and IM&.

**Comment by rrozek** [comment] 2017-09-30 16:00
Thank you!
