### ISSUE TITLE
webp:target-size= does not work

### ISSUE THREAD

**Issue by rawriddims** [ImageMagick/ImageMagick#5181] opened 2022-05-30 22:36 UTC
### ImageMagick version

7.1.0-36 Q16-HDRI x64 be0bdc3:20220530

### Operating system

Windows

### Operating system, version and so on

10 - 64bit - x64

### Description

When I'm running `magick in.jpg -resize 1768 -define webp:target-size=235000 out.webp`

webp:target-size= has no effect.

On the other hand when I convert to webp with -quality is properly working.

convert -list format is showing for my IM version: libwebp 1.2.2 [020F]

### Steps to Reproduce

`magick in.jpg -resize 1768 -define webp:target-size=235000 out.webp`

**Comment by dlemstra** [comment] 2022-05-30 22:43
Duplicate of #4923

**Closed by dlemstra** 2022-05-30 22:43 UTC
