### ISSUE TITLE
Why IM disable thread support in decoding HEIC image

### ISSUE THREAD

**Issue by giantpoplar** [ImageMagick/ImageMagick#1239] opened 2018-08-06 08:42 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I don’t understand why IM disable decoder thread support when RegisterHEICImage in coders/heic.c in line 378. I consult libheif author about thread safe problem in decoding hevc image. He wrote “As long as each thread works on its own heif_context, you should be safe”. 
[https://github.com/strukturag/libheif/issues/55](url)
 Since IM decode images with separate heif_context, so I believe this restriction could be removed.
### System Configuration

- ImageMagick version:
7.0.8-6
- Environment (Operating system, version and so on):
centos7.1
- Additional information:

**Comment by dlemstra** [comment] 2018-08-06 09:38
Duplicate of #1131

**Closed by dlemstra** 2018-08-06 09:38 UTC
Labels: duplicate
