### ISSUE TITLE
How to create optimised and progressive Images (JPG, PNG)

### ISSUE THREAD

**Issue by palaiyacw** [ImageMagick/ImageMagick#411] opened 2017-03-28 13:00 UTC
Interlace value seems to be lost. When an image is being read from the disk having interlace value set to be `plane`.  For more detail Kindly refer this  [Issue](https://github.com/gographics/imagick/issues/125#issuecomment-289403944)

**Comment by dlemstra** [comment] 2017-03-28 13:11
Do you have a command and an image that we can use to reproduce your issue?

**Comment by palaiyacw** [comment] 2017-03-29 17:40
@dlemstra I have used the progressive image given [here](http://pooyak.com/p/progjpeg/). Moreover, I was using Go wrapper as mentioned above. So, when i try to read the image in Go lang using  `mw.ReadImageBlob()` . As, i see there is no changes related to interlace property done in the [method](https://github.com/gographics/imagick/blob/v3.1.0/imagick/magick_wand_image.go#L1788) . But still, It loses the interlace property checked by this command `identity -v image.jpg`. So, is there any issue with the Image magick library? I also asked creator of Go wrapper for image magick but he also couldn't understand what's the issue. For more details about the discussion kindly refer [this](https://github.com/gographics/imagick/issues/125#issuecomment-289145191)

**Comment by dlemstra** [comment] 2017-03-30 14:35
I checked our code and it turns out that we don't preserve the progressive option when writing the image. We will only write a progressive image when we are told to do so. I think you can preserve it in `Go` with the following code:
```go
package main

import "gopkg.in/gographics/imagick.v2/imagick"

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
        defer mw.Destroy()

	if err := mw.ReadImage("jpegload.cgi.jpg"); err != nil {
		panic(err)
	}

        // This preserves the original interlace scheme.
	mw.SetInterlaceScheme(mw.GetImageInterlaceScheme())

	if err := mw.WriteImage("out.jpg"); err != nil {
		panic(err)
	}
}
```

**Comment by palaiyacw** [comment] 2017-03-30 20:00
@dlemstra I already did what you suggested earlier but it doesn't work out. And it's preserving the interlace value in your case reason being you are not doing `mw.Clear()` between the read and the write.

**Comment by palaiyacw** [comment] 2017-03-30 20:02
@dlemstra Again i am saying kindly again go through the issue which i posted [here](https://github.com/gographics/imagick/issues/125#issuecomment-289403944).  @justinfx He also did the same mistake which you did here.

**Comment by dlemstra** [comment] 2017-03-30 20:29
I am sorry but I don't understand why you would want to call `Clear` on the `mw`? Maybe I am not understanding your issue correctly. Do you not want to preserve the `interlace` when you read and write the image?

**Comment by justinfx** [comment] 2017-03-30 20:59
( @palaiyacw I am actually just a volunteer maintainer trying to keep the Go bindings active for others )

The `Clear()` being referred to is not applicable to your example, @dlemstra. Not sure why it is being recommended. In my example from the references imagick issue, I was reusing the MagickWand to read the image back in.

This bit is interesting:

```go
mw.SetInterlaceScheme(mw.GetImageInterlaceScheme())
```
If we do not do this step, we end up getting `NoInterlace` when we read back in the progressive image. Now, when we write a progressive image using `PlaneInterlace`, it does produce the right progressive jpeg, but when using your approach and reading the scheme we end up with `JPEGInterlace`. That is to be expected, correct? It uses "Plane" to tell the writer to do progressive, but reading it back in ends up with a more specific interlace scheme?

Can you explain why that snippet of code ends up producing the usable values? If the initial results of getting the interlace scheme is `NoInterlace`, which is it that setting it and then getting it again produces `JpegInterlace`?

**Comment by dlemstra** [comment] 2017-03-31 06:55
There are two `interlace` members stored inside the MagickWand (`mw`). One is stored on the image and the other one is stored on the image_info. The latter is used when the image is being written. `GetImageInterlaceScheme` will get the interlace value of the image that was read and calling `SetInterlaceScheme` will set that inside the image_info. Let me know if you need more information. I do think we can close this issue now though since my suggestion seems to be producing the correct result?

**Comment by palaiyacw** [comment] 2017-03-31 08:54
@dlemstra Ok, Thanks. Could you please also tell me how do I set the interlace value to be `plane` after reading the image for those which had interlace value `none` earlier. I tried setting using this `mw.SetImageInterlaceScheme(imagick.INTERLACE_PLANE)`. But when I checked the image using `identify -verbose IMAGE_NAME` and it still gives me the `none` value

**Comment by dlemstra** [comment] 2017-03-31 10:56
You will need to do `mw.SetInterlaceScheme` and you will need to write the image.

**Comment by palaiyacw** [comment] 2017-03-31 12:28
@dlemstra Sorry, but i have one more doubt. What's the difference between `mw.SetInterlaceScheme` and `mw.SetImageInterlaceScheme`?

**Comment by dlemstra** [comment] 2017-03-31 13:35
My other post has an explanation about the difference. Let me know if you need more info.

**Comment by palaiyacw** [comment] 2017-03-31 18:13
> My other post 
Could you please give the link and then we can close this issue

**Comment by dlemstra** [comment] 2017-03-31 19:52
This one: https://github.com/ImageMagick/ImageMagick/issues/411#issuecomment-290632452

**Comment by justinfx** [comment] 2017-03-31 21:00
@dlemstra , thank you for pointing out the difference between the two sets of getters/setters. That does resolve the issues listed [here](https://github.com/gographics/imagick/issues/125#issuecomment-290828285)

**Closed** 2017-03-31 21:55 UTC
