### ISSUE TITLE
Regression: delegates gone in 7.0.7-23

### ISSUE THREAD

**Issue by MichaelDaum** [ImageMagick/ImageMagick#995] opened 2018-02-20 10:10 UTC
I just tried 7.0.7-23 (as well as ImageMagick/master) and tried to list all supported formats using

`convert -list format`

and it returned nothing. Basically the thing has forgotten about its delegates, even for simple PNGs.

Going back to the 7.0.7-22er branch fixed it again.

**Comment by dlemstra** [comment] 2018-02-20 10:35
I suspect this is a duplicate of #991.

**Comment by urban-warrior** [comment] 2018-02-21 13:21
Unfortunately, we still cannot reproduce the problem. Can you post the output of this command: convert -list configure? Once we can reproduce the problem we will have a fix promptly.

**Comment by MichaelDaum** [comment] 2018-02-21 13:44
I configured it using:

`
./configure --prefix=${HOME}/local --with-perl=${HOME}/.plenv/shims/perl --enable-shared --disable-openmp --disable-opencl --without-x
`

Here is the output of `convert -list configure`:

```
Path: /home/www-data/local/lib/ImageMagick-7.0.7//config-Q16HDRI/configure.xml

Name           Value
-------------------------------------------------------------------------------
CC             gcc -std=gnu99 -std=gnu99
CFLAGS         -I/usr/include/libxml2     -I/usr/include/libpng12    -pthread -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12       -I/usr/include/graphviz   -I/usr/include/freetype2   -I/usr/include/freetype2   -pthread       -g -O2 -Wall -mtune=core-avx2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
CODER_PATH     /home/www-data/local/lib/ImageMagick-7.0.7/modules-Q16HDRI/coders
CONFIGURE      ./configure  '--prefix=/home/www-data/local' '--with-perl=/home/www-data/.plenv/shims/perl' '--enable-shared' '--disable-openmp' '--disable-opencl' '--without-x'
CONFIGURE_PATH /home/www-data/local/etc/ImageMagick-7/
COPYRIGHT      Copyright (C) 1999-2018 ImageMagick Studio LLC
CPPFLAGS       -I/home/www-data/local/include/ImageMagick-7
CXX            g++
CXXFLAGS       -g -O2 -pthread
DEFS           -DHAVE_CONFIG_H
DELEGATES      bzlib djvu mpeg fontconfig freetype jbig jng jpeg lcms lzma pango png ps tiff webp wmf xml zlib
DISTCHECK_CONFIG_FLAGS  --disable-deprecated  --with-quantum-depth=16  --with-jemalloc=no  --with-umem=no  --with-autotrace=no  --with-gslib=no  --with-fontpath=  --with-rsvg=no  --with-perl=/home/www-data/.plenv/shims/perl 
DOCUMENTATION_PATH /home/www-data/local/share/doc/ImageMagick-7
EXEC-PREFIX    /home/www-data/local
EXECUTABLE_PATH /home/www-data/local/bin
FEATURES       DPC HDRI Cipher
FILTER_PATH    /home/www-data/local/lib/ImageMagick-7.0.7/modules-Q16HDRI/filters
GIT_REVISION   22973:fe6c919ff:20180218
HOST           x86_64-pc-linux-gnu
INCLUDE_PATH   /home/www-data/local/include/ImageMagick-7
LDFLAGS        -L/home/www-data/local/lib 
LIB_VERSION    0x707
LIB_VERSION_NUMBER 7,0,7,24
LIBRARY_PATH   /home/www-data/local/lib/ImageMagick-7.0.7
LIBS            -ljbig -llcms2   -ltiff -lfreetype    -ljpeg   -lpng12    -ldjvulibre      -lfontconfig -lfreetype     -lwebp   -lwmflite      -llzma   -lbz2   -lpangocairo-1.0 -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0     -lxml2   -lgvc -lcgraph -lcdt   -lz   -lltdl  -lm     
NAME           ImageMagick
PCFLAGS        -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
PREFIX         /home/www-data/local
QuantumDepth   16
RELEASE_DATE   2018-02-21
SHARE_PATH     /home/www-data/local/share/ImageMagick-7
SHAREARCH_PATH /home/www-data/local/lib/ImageMagick-7.0.7/config-Q16HDRI
TARGET_CPU     x86_64
TARGET_OS      linux-gnu
TARGET_VENDOR  pc
VERSION        7.0.7
WEBSITE        http://www.imagemagick.org

Path: [built-in]

Name           Value
-------------------------------------------------------------------------------
FEATURES       
NAME           ImageMagick
QuantumDepth   16
```

**Comment by ennss** [comment] 2018-02-21 16:39
(Let me know what other info. would be helpful.)  I can confirm a delegates access/usage issue on cygwin that's new with .23, correct delegates listed but not accessible to convert when trying to read a file:

$ convert dde.jpg t.png
convert: no decode delegate for this image format `JPEG' @ error/constitute.c/Re
adImage/509.
convert: no images defined `t.png' @ error/convert.c/ConvertImageCommand/3275.

Same config as used with .22:

  ./configure --with-windows-font-dir=/cygdrive/c/windows/fonts --with-quantum-depth=32

$ convert -list configure

Path: /usr/local/lib/ImageMagick-7.0.7//config-Q32HDRI/configure.xml

Name           Value
-------------------------------------------------------------------------------
CC             gcc
CFLAGS         -I/usr/include/libxml2   -I/usr/include/libraw -I/usr/include/libpng16  -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16  -I/usr/include/lqr-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/openjpeg-2.2  -I/usr/local/include -I/usr/include/graphviz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16    -pthread -fopenmp -g -O2 -Wall -mtune=athlon64-sse3 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=32
CODER_PATH     /usr/local/lib/ImageMagick-7.0.7/modules-Q32HDRI/coders
CONFIGURE      ./configure  '--with-windows-font-dir=/cygdrive/c/windows/fonts' '--with-quantum-depth=32' '--with-fftw=yes'
CONFIGURE_PATH /usr/local/etc/ImageMagick-7/
COPYRIGHT      Copyright (C) 1999-2018 ImageMagick Studio LLC
CPPFLAGS       -I/usr/local/include/ImageMagick-7
CXX            g++
CXXFLAGS       -g -O2 -pthread
DEFS           -DHAVE_CONFIG_H
DELEGATES      bzlib djvu mpeg fftw fontconfig freetype heic jbig jng jpeg lcms lqr lzma openjp2 pango png ps raw tiff webp x xml zlib
DISTCHECK_CONFIG_FLAGS  --disable-deprecated  --with-quantum-depth=32  --with-jemalloc=no  --with-umem=no  --with-autotrace=no  --with-gslib=no  --with-fontpath=  --with-rsvg=no  --with-windows-font-dir=/cygdrive/c/windows/fonts  --with-perl=no 
DOCUMENTATION_PATH /usr/local/share/doc/ImageMagick-7
EXEC-PREFIX    /usr/local
EXECUTABLE_PATH /usr/local/bin
FEATURES       DPC HDRI Cipher OpenCL OpenMP
FILTER_PATH    /usr/local/lib/ImageMagick-7.0.7/modules-Q32HDRI/filters
GIT_REVISION   13566
HOST           x86_64-unknown-cygwin
INCLUDE_PATH   /usr/local/include/ImageMagick-7
LDFLAGS        -L/usr/local/lib  
LIB_VERSION    0x707
LIB_VERSION_NUMBER 7,0,7,23
LIBRARY_PATH   /usr/local/lib/ImageMagick-7.0.7
LIBS            -ljbig -llcms2 -ltiff -lfreetype  -ljpeg  -llqr-1 -lglib-2.0 -lintl -lpng16 -lz  -ldjvulibre -lfftw3   -lfontconfig -lfreetype -L/usr/local/lib -lde265 -lwebpmux -lwebp -lwebp   -lXext -lXt   -lSM -lICE -lX11  -llzma -lbz2  -lopenjp2 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo -lraw_r -fopenmp  -lxml2 -lgvc -lcgraph -lcdt -lz -lltdl -lgdi32 -lm -lgomp -lOpenCL  -lm   
NAME           ImageMagick
PCFLAGS        -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=32
PREFIX         /usr/local
QuantumDepth   32
RELEASE_DATE   2018-02-20
SHARE_PATH     /usr/local/share/ImageMagick-7
SHAREARCH_PATH /usr/local/lib/ImageMagick-7.0.7/config-Q32HDRI
TARGET_CPU     x86_64
TARGET_OS      cygwin
TARGET_VENDOR  unknown
VERSION        7.0.7
WEBSITE        http://www.imagemagick.org

Path: [built-in]

Name           Value
-------------------------------------------------------------------------------
FEATURES       OpenMP 
NAME           ImageMagick
QuantumDepth   32

**Comment by urban-warrior** [comment] 2018-02-21 22:56
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by MichaelDaum** [comment] 2018-02-22 08:24
Tried master: works again. Thanks a lot.

**Closed** 2018-02-24 19:37 UTC
