### ISSUE TITLE
Can't built with --disable-dependency-tracking --enable-osx-universal-binary

### ISSUE THREAD

**Issue by vidjuheffex** [ImageMagick/ImageMagick#6837] opened 2023-10-31 19:59 UTC
### ImageMagick version

7.1.1-21

### Operating system

MacOS

### Operating system, version and so on

M2 Mac Ventura 13.6 (Term is set to be x86 simulated)

### Description

Can't build with this input 

`./configure --without-x --disable-installed --enable-osx-universal-binary --disable-dependency-tracking`

Get:

`configure: error: in `/Users/jherrera/code/ImageMagick':
configure: error: cannot make gcc report undeclared builtins
See `config.log' for more details`

### Steps to Reproduce

Download or code latest version

run:
`./configure --without-x --disable-installed --enable-osx-universal-binary --disable-dependency-tracking`

**Comment by dlemstra** [comment] 2023-10-31 20:03
Closing this as duplicate of #5426.

**Closed by dlemstra** 2023-10-31 20:03 UTC
