### ISSUE TITLE
Orientation tag bug in tiff image decoding.

### ISSUE THREAD

**Issue by AlexRozen** [ImageMagick/ImageMagick#7147] opened 2024-03-05 14:19 UTC
### ImageMagick version

7.1.1-29

### Operating system

Windows

### Operating system, version and so on

Windows 10 x64

### Description

Tiff image decoding seems to have totally no or totally incorrect respect of Orientation tag (274) depending of source file.

I have produced 2 test files. One from LZW-compressed image and another from JPEG-compressed image.
Both contain 5 frames that should produce clockwise rotation of image by changing the orientation tag in it's IFD:
TopLeft -> RightTop -> BottomRight -> LeftBottom -> TopLeft

When I view this images in some modern viewer, then it displays every frame according the embedded Orientation tag. 
(Checked in FastStone Image Viewer, XnView MP, IrfanView 64).

When I convert by ImageMagick such LZW-compressed tiff image to PNG's or PDF file then it produces 5 pages **without any rotation**.
When I convert such JPEG-compressed tiff image to PNG's or PDF file then it produces 5 pages **with page horizontal and vertical flipping** instead of rotation.

I'm sure that decoding of source tiff _should have the correct processing of orientation tag in any compatible compression format_ of tiff page, producing the different image orientation in target file pages. Especially when converting to pdf.

P.S. Also I checked these test images with ImageGlass viewer, which is based on ImageMagick's dll. It seems that viewer's programmers have implemented rotating of tiff page _after decoding_, but combining with unexpected flipping of jpeg-compressed pages **produces unpredictable results**.

### Steps to Reproduce

```
magick convert test_RotateClockwize_jpeg.tiff test_RotateClockwize_jpeg.pdf
magick convert test_RotateClockwize_lzw.tiff test_RotateClockwize_lzw.pdf

magick identify -verbose  test_RotateClockwize_jpeg.tiff > test_RotateClockwize_jpeg.tiff.txt
magick identify -verbose  test_RotateClockwize_lzw.tiff > test_RotateClockwize_lzw.tiff.txt

``` 

### Images

[Tiff rotation.zip](https://github.com/ImageMagick/ImageMagick/files/14496282/Tiff.rotation.zip)

**Comment by AlexRozen** [comment] 2024-03-05 16:11
> You didn't use `auto-orient`.

You are right, shame on me. 
But the sample jpeg-based tiff pages are still wrong-processed even with -auto-orient flag.

**Comment by AlexRozen** [comment] 2024-03-06 15:48
conversion 
```
magick convert -auto-orient test_RotateClockwize_jpeg.tiff test_RotateClockwize_jpeg.pdf
``` 
shows wrong results

**Comment by fmw42** [comment] 2024-03-06 16:57
In IM 7, use magick, not magick convert.  Then put -auto-orient after reading the input image and before the output.

`magick test_RotateClockwize_jpeg.tiff-auto-orient test_RotateClockwize_jpeg.pdf`

**Comment by fmw42** [comment] 2024-03-06 17:05
I can confirm that not all pages get auto-oriented properly on IM 7.1.1.29 Mac Ventura with

`magick test_RotateClockwize_jpeg.tiff -auto-orient test_RotateClockwize_jpeg.png`

**Comment by urban-warrior** [comment] 2024-03-10 13:39
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by urban-warrior** [comment] 2024-03-10 22:23
See http://www.vb-helper.com/howto_net_read_exif_orientation.html.  Here is an overview of EXIF-orientation values:

```
1: Normal (no rotation required)
2: Flipped horizontally
3: Upside-down (180 degrees rotation)
4: Flipped vertically
5: Rotated 90 degrees counterclockwise and flipped horizontally
6: Rotated 90 degrees counterclockwise
7: Rotated 90 degrees clockwise and flipped horizontally
8: Rotated 90 degrees clockwise
```

EXIF and TIFF have corresponding orientation values. 

This script proves ImageMagick is behaving properly for the set of orientations:

```
magick -gravity center -pointsize 100 -font Courier-10-Pitch-Regular -size 120x120 label:F F.png
magick convert F.png -orient top-left TopLeft.png
magick convert F.png -flop -orient top-right TopRight.png
magick convert F.png -rotate 180 -orient bottom-right BottomRight.png
magick convert F.png -flip -orient bottom-left BottomLeft.png
magick convert F.png -transpose -orient left-top LeftTop.png
magick convert F.png -rotate 270 -orient right-top RightTop.png
magick convert F.png -transverse -orient right-bottom RightBottom.png
magick convert F.png -rotate 90 -orient left-bottom LeftBottom.png
montage -pointsize 16 -label %t -tile 8x1 TopLeft.png TopRight.png BottomRight.png BottomLeft.png LeftTop.png RightTop.png RightBottom.png LeftBottom.png auto-orient.png
display auto-orient.png
display -auto-orient TopLeft.png TopRight.png BottomRight.png BottomLeft.png LeftTop.png RightTop.png RightBottom.png LeftBottom.png
```

which suggests that `test_RotateClockwize_jpeg.tiff` does not have the proper scanline orientation for certain orientation tags:

```
1 = The 0th row represents the visual top of the image, and the 0th column represents the visual left-hand side.
2 = The 0th row represents the visual top of the image, and the 0th column represents the visual right-hand side.
3 = The 0th row represents the visual bottom of the image, and the 0th column represents the visual right-hand side.
4 = The 0th row represents the visual bottom of the image, and the 0th column represents the visual left-hand side.
5 = The 0th row represents the visual left-hand side of the image, and the 0th column represents the visual top.
6 = The 0th row represents the visual right-hand side of the image, and the 0th column represents the visual top.
7 = The 0th row represents the visual right-hand side of the image, and the 0th column represents the visual bottom.
8 = The 0th row represents the visual left-hand side of the image, and the 0th column represents the visual bottom.
```

**Comment by AlexRozen** [comment] 2024-03-19 15:38
I can't confirm the patch. 
According to ``` Identify ``` command both test files (``` test_RotateClockwize_jpeg.tiff ```  and ``` test_RotateClockwize_lzw.tiff ``` ) have the same orientation tags sequence: 
```
  Orientation: TopLeft
  Orientation: RightTop
  Orientation: BottomRight
  Orientation: LeftBottom
  Orientation: TopLeft
``` 
After applying the patch the  ``` test_RotateClockwize_lzw.tiff ``` **have broke** it's previously working auto-orientation. Also ``` test_RotateClockwize_jpeg.tiff ``` still rotates **even without** the ``` --auto-orient ``` switch but doesn't rotate with it.

I have inspected the ``` AutoOrientImage ``` and it seems, that unpatched code was logically correct. Problem seems to be somewhere in JPEG-decoding (some unexpected transformation seems to be applied).

P.S. I have attached 4 pdf files, made with and without ``` --auto-orient ``` flag from both sample files.
[test_RotateClockwize_lzw.pdf](https://github.com/ImageMagick/ImageMagick/files/14652810/test_RotateClockwize_lzw.pdf)
[test_RotateClockwize_lzw_auto-orient.pdf](https://github.com/ImageMagick/ImageMagick/files/14652815/test_RotateClockwize_lzw_auto-orient.pdf)
[test_RotateClockwize_jpeg.pdf](https://github.com/ImageMagick/ImageMagick/files/14652819/test_RotateClockwize_jpeg.pdf)
[test_RotateClockwize_jpeg_auto-orient.pdf](https://github.com/ImageMagick/ImageMagick/files/14652821/test_RotateClockwize_jpeg_auto-orient.pdf)

**Comment by AlexRozen** [comment] 2024-03-21 15:45
After applying the patch it is no more respecting the orientation tag with 
``` -auto-orient ```  option even in pure jpeg file itself.

Look at sample file. All viewers display it rotated with sky at right side. 
Release version of ImageMagick identifies it's orientation as RightTop and converts it with sky at top without ``` -auto-orient ``` and with sky at right using ``` -auto-orient ```.

But patched version doesn't apply any rotation with  ``` -auto-orient ```.


![Cliff_90](https://github.com/ImageMagick/ImageMagick/assets/14195783/0da3c946-5559-41ff-9b90-a73a18ef4b38)

**Comment by dlemstra** [comment] 2024-03-21 19:27
We reverted to patch because it was incorrect. The code behaves properly now.

**Closed** 2024-03-23 21:58 UTC
