### ISSUE TITLE
coders/dng.c: error: 'libraw_data_t' has no member named 'rawparams'

### ISSUE THREAD

**Issue by yawnbox** [ImageMagick/ImageMagick#6969] opened 2023-12-24 22:10 UTC
### ImageMagick version

7.1.1-23

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04 Server

### Description

make, after configure, results in:

```
...
  CC       coders/dng_la-dng.lo
coders/dng.c: In function 'SetLibRawParams':
coders/dng.c:336:13: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  336 |   raw_info->rawparams.max_raw_memory_mb=8192;
      |             ^~~~~~~~~
      |             params
coders/dng.c:339:15: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  339 |     raw_info->rawparams.max_raw_memory_mb=(unsigned int)
      |               ^~~~~~~~~
      |               params
make[1]: *** [Makefile:10716: coders/dng_la-dng.lo] Error 1
make[1]: Leaving directory '/home/user/ImageMagick-7.1.1-23'
make: *** [Makefile:6244: all] Error 2
```

### Steps to Reproduce

`git clone https://github.com/ImageMagick/ImageMagick.git ImageMagick-7.1.1-23`

`cd ImageMagick-7.1.1-23`

`./configure --with-modules --enable-file-type --with-quantum-depth=32 --with-jpeg=yes --with-png=yes --with-gif=yes --with-webp=yes --with-heic=yes --with-raw=yes --with-tiff=yes --with-openjp2 --with-freetype=yes --with-webp=yes --with-openexr=yes --with-gslib=yes --with-gif=yes --with-rsvg=yes`

`make`

**Comment by urban-warrior** [comment] 2023-12-25 03:39
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by kekePower** [comment] 2023-12-25 21:23
Hi. Getting the same error on 7.1.1-24 on Mageia Cauldron.

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./config -I. -I. -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32 -I/usr/include/libxml2 -I/usr/include/webp -I/usr/include/webp -I/usr/include/webp -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/pixman-1 -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/webp -pthread -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libxml2 -I/usr/include/pixman-1 -I/usr/include/libraw -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/pixman-1 -pthread -I/usr/include/OpenEXR -pthread -I/usr/include/Imath -I/usr/include/lqr-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/openjpeg-2.5 -DHWY_SHARED_DEFINE -I/usr/include/webp -I/usr/include/graphviz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -pthread -fopenmp -Wall -O2 -g -pipe -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -fno-strict-aliasing -fPIC -DIMPNG_SETJMP_IS_THREAD_SAFE -mtune=generic -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32 -c coders/dng.c  -fPIC -DPIC -o coders/.libs/dng_la-dng.o
coders/dng.c: In function 'SetLibRawParams':
coders/dng.c:337:13: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  337 |   raw_info->rawparams.max_raw_memory_mb=8192;
      |             ^~~~~~~~~
      |             params
coders/dng.c:340:15: error: 'libraw_data_t' has no member named 'rawparams'; did you mean 'params'?
  340 |     raw_info->rawparams.max_raw_memory_mb=(unsigned int)
      |               ^~~~~~~~~
      |               params
make[1]: *** [Makefile:10718: coders/dng_la-dng.lo] Error 1
make[1]: Leaving directory '/home/iurt/rpmbuild/BUILD/ImageMagick-7.1.1-24'
make[1]: *** Waiting for unfinished jobs....
```

Complete build log can be found here https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20231225205649.kekepower.duvel.3407716/imagemagick-7.1.1.24-1.mga10/build.x86_64.0.20231225205712.log

**Comment by dlemstra** [comment] 2023-12-25 21:47
It looks like we need to check for version `0.20` instead.

**Closed** 2023-12-28 15:41 UTC

**Comment by melanopsis** [comment] 2024-01-03 00:25
Same issue with v7.1.1-25

**Comment by urban-warrior** [comment] 2024-01-03 00:28
The version check is in Github main.  The -26 release is not scheduled for a few weeks.
