### ISSUE TITLE
unicode file paths

### ISSUE THREAD

**Issue by digital-flowers** [ImageMagick/ImageMagick#283] opened 2016-10-01 11:23 UTC
Hi i think there is something wrong with this if statement 
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/utility-private.h#L145

after i remove this condition i could successfully read files with non-ascii characters in filenames under Windows, please check the following issue:
https://github.com/jcupitt/libvips/issues/294

**Comment by digital-flowers** [comment] 2016-10-01 11:24
maybe it should be something like 
#if !(defined(MAGICKCORE_WINDOWS_SUPPORT) || defined(__CYGWIN__) || defined(__MINGW32__) || defined(__MINGW64__))

**Comment by dlemstra** [comment] 2016-10-10 07:30
How are you building ImageMagick? I cannot reproduce your issue. And it seems that you referenced a bugfix from 2014 in your other post. This was not fixed since 7.0.3-1, it was fixed in the first public release of IM7, and it has been fixed since 6.8.8-8 in IM6.

**Comment by digital-flowers** [comment] 2016-10-10 12:38
sorry! yes you are right regard version 6.8.8.
i am building imagemagick to use it with libvips, libvips building it using jhbuild using this moduleset https://github.com/jcupitt/build-win64/blob/master/8.4/vips.modules, all modules works fine except imagemagick doesn't read files with korean names under windows when i put that if condition to false everything works fine

**Comment by dlemstra** [comment] 2017-03-13 05:48
Do you still have this issue @digital-flowers?

**Comment by digital-flowers** [comment] 2017-03-13 11:55
hi @dlemstra sorry this issue was very old i didn't checked it after that if you want you can close it.

**Closed** 2017-03-13 13:14 UTC
