### ISSUE TITLE
-combine -colorspace sRGB gives grayscale output

### ISSUE THREAD

**Issue by LesiaF** [ImageMagick/ImageMagick#1835] opened 2020-01-16 17:29 UTC
**Prerequisites**

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

**Description**

I want to make a level adjustment on the RGB image, but as output I get a grayscale image.
I applied the level adjustment to each band individually and after merged all three bands with `gdal` and it worked, but in this case I would like to work only with `ImageMagick`. I used ` ImageMagick 7.0.9` and  `ImageMagick 6.9.10` versions, for both cases it results a grayscale image.

**Steps to Reproduce**

1. Multiband image split into separate RGB bands;
2. Applying `ImageMagick` with next command:
   `convert  -monitor red.tif green.tif blue.tif -combine -colorspace sRGB -level 0,11565,2.0 TIFF64:raw_output.tif`;
3. Greyscale output.

**System Configuration**

- ImageMagick version:  ImageMagick 7.0.9-16 Q16 x86_64 2020-01-12 and ImageMagick 6.9.10
- Environment (Operating system, version and so on): macOS Catalina 10.15.2

**Comment by fmw42** [comment] 2020-01-16 18:03
I can verify this with IM 7.0.9.16 as follows:

```
magick logo: -separate +adjoin x.tif
magick x-0.tif x-1.tif x-2.tif -combine -colorspace sRGB newx.tif
```


[newx.tif.zip](https://github.com/ImageMagick/ImageMagick/files/4072936/newx.tif.zip)

**Comment by OlesiaFM** [comment] 2020-01-20 14:37
Thank you for fast fix! 
I tested the latest beta release and it works now.

**Comment by AndroYD84** [comment] 2020-02-12 09:05
Using the latest beta version: ImageMagick 7.0.9-23 Q8 x64 2020-02-11

This bug still exists, it was fixed only for the "convert" command, but still happens with the "mogrify" command, you can reproduce the problem with [this picture here](https://github.com/AndroYD84/Files/blob/master/000001.png), put it in an empty folder and run:

`mogrify -channel A -transparent #0000FF -negate +channel -background black -alpha remove -alpha off -fill white -opaque #0000FF -set colorspace:auto-grayscale false -colorspace sRGB -type TrueColor PNG24:*.png`

Then check with `magick identify 000001.png` and it will return `000001.png PNG 1920x1080 1920x1080+0+0 8-bit Gray 2c 3089B 0.000u 0:00.000`

While running the exact same thing with "convert":

`convert 000001.png -channel A -transparent #0000FF -negate +channel -background black -alpha remove -alpha off -fill white -opaque #0000FF -set colorspace:auto-grayscale false -colorspace sRGB -type TrueColor PNG24:000001-convert.png`

And checking with `magick identify 000001-convert.png`  will return the correct value `000001-convert.png PNG 1920x1080 1920x1080+0+0 8-bit sRGB 10619B 0.000u 0:00.000`

Hope this gets fixed soon, also, there's no "Q16-X64-dll.exe" version for the latest beta, only "Q8"

**Comment by fmw42** [comment] 2020-02-12 16:47
It fails also for IM 6.9.10.92 Q16 Mac OSX. Note that for PNG, only the PNG24: prefix will control the output color vs grayscale.

**Comment by AndroYD84** [comment] 2020-03-18 09:49
This problem was reported two months ago and it's still present on the current latest version, including the beta, because this simple operation is broken I have to do the equivalent of rotating an entire house just to screw a lightbulb, it's so tiring and makes certain pipelines unnecessarily complicated. Can someone please fix this? I beg you, make this pain go away.

**Comment by urban-warrior** [comment] 2020-03-18 22:05
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Closed** 2020-08-24 18:50 UTC
