### ISSUE TITLE
Compile 7.0.11-11 | 7.0.11-12 missing separator

### ISSUE THREAD

**Issue by totoestcontent** [ImageMagick/ImageMagick#3664] opened 2021-05-11 07:37 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

Linux

### Operating system, version and so on

Ubuntu 16.04 | 18 | 20

### Description

When i execute configure, i have an error "missing separator".
I can compile 7.0.11-10 but not 7.0.11-11+.
If i activate "--disable-dependency-tracking", i can configure but compile throw same error.

I compare 7.0.11-10 and 7.0.11-11, and i see that Makefile.in was modified line 13615,
an tabulation was changed by two spaces.
If i replace two spaces by tabulation at this line after "@MAGICKCORE_ZERO_CONFIGURATION_SUPPORT_TRUE@", i can configure et compile.

![image](https://user-images.githubusercontent.com/55127910/117774608-ffd59700-b239-11eb-88e9-89580411b85c.png)

### Steps to Reproduce

- git clone https://github.com/ImageMagick/ImageMagick.git
- git checkout 7.0.11-12
- ./configure --enable-hdri=no \
			--disable-static \
			--without-modules \
			--enable-zero-configuration \
			--with-bzlib=yes \
			--with-autotrace=no \
			--with-djvu=yes \
			--with-dps=no \
			--with-fftw=yes \
			--with-flif=no \
			--with-fpx=no \
			--with-fontconfig=yes \
			--with-freetype=yes \
			--with-gslib=yes \
			--with-gvc=no \
			--with-heic=yes \
			--with-jbig=yes \
			--with-jpeg=yes \
			--with-jxl=no \
			--with-lcms=yes \
			--with-lqr=yes \
			--with-lzma=yes \
			--with-magick-plus-plus=no \
			--with-openexr=yes \
			--with-openjp2=yes \
			--with-pango=yes \
			--with-perl=no \
			--with-png=yes \
			--with-raqm=no \
			--with-raw=yes \
			--with-rsvg=no \
			--with-tiff=yes \
			--with-webp=yes \
			--with-wmf=yes \
			--with-xml=yes \
			--with-zip=yes \
			--with-zlib=yes \
			--with-zstd=true \

Result:
![image](https://user-images.githubusercontent.com/55127910/117777009-75dafd80-b23c-11eb-9bdf-5a57078127a8.png)

**Comment by dlemstra** [comment] 2021-05-11 08:42
Duplicate of #3659

**Closed by dlemstra** 2021-05-11 08:42 UTC
