### ISSUE TITLE
Red stripes in alpha channel when resizing black sRGB tiff image

### ISSUE THREAD

**Issue by josbalcaen** [ImageMagick/ImageMagick#7078] opened 2024-01-30 13:00 UTC
### ImageMagick version

13.5.0

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

When loading, resizing, saving a black sRGB image with alpha, the alpha has red stripes in it.
Attached zip with input and output image.

### Steps to Reproduce

```
using MagickImage outputImage = new MagickImage(outputFilePath);
outputImage.Resize(512, 512);
outputImage.RePage();
outputImage.Write(destinationFilePath);
```

### Images

[redstripesinalphaafterresize.zip](https://github.com/ImageMagick/ImageMagick/files/14098049/redstripesinalphaafterresize.zip)

**Comment by fmw42** [comment] 2024-01-30 17:08
I do not see any stripes in either image in the alpha channels of your images.

**Comment by urban-warrior** [comment] 2024-01-31 01:02
You can check the characteristics of the input and output images with `identify -verbose`.  Both the input and output is all black.   There is an unspecified extra channel which is all zeros for both the input and output.

**Comment by josbalcaen** [comment] 2024-01-31 12:14
Sorry, the output image I attached is the wrong one. Please see updated attached image
[outputblackwithredstripesalpha.zip](https://github.com/ImageMagick/ImageMagick/files/14111476/outputblackwithredstripesalpha.zip)

**Comment by dlemstra** [comment] 2024-01-31 14:50
I suspect your issue is related to this issue: https://github.com/dlemstra/Magick.NET/issues/1523. This will probably be resolved in the next release but I think I will need to check if that is the case.

**Comment by dlemstra** [comment] 2024-02-08 06:49
I cannot reproduce your issue with the latest beta build. This should be resolved in the next release.

**Closed by dlemstra** 2024-02-08 06:49 UTC
