### ISSUE TITLE
Use CMake as build system

### ISSUE THREAD

**Issue by igormironchik** [ImageMagick/ImageMagick#5991] opened 2023-01-21 06:39 UTC
### Is your feature request related to a problem? Please describe.

The problem is that we don't have Conan package on Windows platform. And in total building on Windows is something 3rdparty.

### Describe the solution you'd like

Use CMake as build system.

**Comment by dlemstra** [comment] 2023-01-21 09:38
Closing as duplicate of #5102

**Closed by dlemstra** 2023-01-21 09:38 UTC
